feat: 상세 탐색 정보 칩 viewModel에 저장
Team-WSS/WSS-Android pull request #107
Opened 2024-07-09 04:09 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #68 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 상세 탐색 정보 뷰에서 선택한 칩을 뷰모델에서 상태를 저장할 수 있도록 수정했습니다.
- 장르 칩을 제외하고 별점 / 연재상태 칩은 `material Chip` 사용해서 최대한 MVVM 패턴을 지키려고 노력했습니다. 근데 코드가 넘 마음에 안 들어요 ㅠ
- 장르 칩은 웹소소 칩으로, 뷰모델 상태를 observe 해서 ui업데이트 하는 로직은 아닙니다.
> 일단 구현한 로직은, 초기 세팅에서 웹소소 칩을 세팅(selector 사용해서 클릭 시 ui 변경) -> 클릭했을 때 뷰모델에 선택한 칩에 대해서 장르 넘김 -> 뷰모델에서 기존 선택된 장르 칩 리스트에 방금 선택한 칩이 있을 경우 제거, 없을 경우에 기존 선택된 장르 칩 리스트 + 선택 칩 장르 로 구현했습니다.

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
N/A

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
코드 너무 마음에 안 들어서 일단 구현해놓은 것 + 브랜치 까먹지 않기 위해 PR 오픈해뒀고, 코드리뷰 받고
필요하다면 추가 브랜치 리팩토링 거치면서 차차 수정해나가볼게요

2024-07-09 08:36 UTC, librarywon approved these changes
LGTM 리뷰 확인해주세요

2024-07-09 08:36 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +                    seriesStatusChips.filter { it != chip }.forEach { it.isChecked = false }
코틀린스러워서 좋네요

2024-07-09 08:36 UTC, librarywon commented on app/src/main/res/layout/fragment_detail_explore_info.xml
> +            android:id="@+id/chip_detail_explore_info_status_in_series"
c:
```suggestion
            android:id="@+id/chip_detail_explore_info_series_status"
```

2024-07-09 08:36 UTC, librarywon commented on app/src/main/res/layout/fragment_detail_explore_info.xml
> +            style="@style/HarryMoongChi.Chip.Choice"
a: 이름이 좀 킹받긴 하네요 ㅋㅋ

2024-07-09 08:36 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +    }
a: 이슈 해결되면 이것도 변경이 되는건가요?

2024-07-09 08:39 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +    }
얘네는 material Chip 에 사용되는 애들이라 이슈 해결하고는 따로 변경 없을 것 같은데 추후에 코드 리팩하면서 손댈 듯 합니다!

2024-07-09 08:39 UTC, m6z1 commented on app/src/main/res/layout/fragment_detail_explore_info.xml
> +            style="@style/HarryMoongChi.Chip.Choice"
ㅋㅋ 해리뭉치칩~

2024-07-12 14:07 UTC, s9hn approved these changes

2024-07-12 14:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +    fun updateSelectedGenres(genre: String) {
c: how about this?
```suggestion
    private val _selectedGeres: MutableLiveData<MutableList<String>> = MutableLiveData()
   ...
   if (selectedGernres.contains(genre)) return // 제거해야한다면 remove
   _selectedGenres.add(genre)
```

2024-07-12 14:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +    private lateinit var ratingChips: List<Chip>
c: 지연초기화하는 이유가 있나요?

2024-07-12 14:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +    }
a: 이부분은 로직 수정 예정이라고 하니 기다리겠습니다

2024-07-19 01:29 UTC, m6z1 commented on app/src/main/res/layout/fragment_detail_explore_info.xml
> +            android:id="@+id/chip_detail_explore_info_status_in_series"
`in_series` 라는 게 연재중이라는 걸 뜻해서 `chip_detail_explore_info_in_series`로 하겠습니다~

2024-07-19 01:57 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +    private lateinit var ratingChips: List<Chip>
그러게요 지연초기화를 사용할 이유가 없을 것 같은데 수정하겠습니다

2024-07-19 08:08 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +    val selectedGenres: LiveData<List<String>> get() = _selectedGenres.map { it.toList() }
c: what? 이렇게 써지는건 신기하네
해당 장르도 livedata로 관리해야하나요? 해야한다면 _selectedGenres.value.toList()는 어떤지

2024-07-19 08:08 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +        if (selectedGenres.value?.contains(genre) == true) {
c: 이거 == true 없어도 되지않나요???

2024-07-19 08:08 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +        if (selectedGenres.value?.contains(genre) == true) {
얼리리턴으로 else 없애보시죠

2024-07-19 08:08 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +        Log.d("123123", selectedGenres.value.toString())
r: 세훈표 로그도 지워주셈요

2024-07-19 08:10 UTC, s9hn requested changes

2024-07-19 08:10 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +    private var ratingChips: List<Chip> = emptyList()
r: 액티비티에 필요한 전역프로퍼티인가요?

2024-07-22 07:14 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +    val selectedGenres: LiveData<List<String>> get() = _selectedGenres.map { it.toList() }
해당 장르 외부에서 사용할 일이 없더라구요 ㅎㅎ 제거하겠습니다

2024-07-22 07:27 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +        if (selectedGenres.value?.contains(genre) == true) {
== true 없으면 type mismatch 떠서 추가했습니다. 얼리리턴 반영했습니다

2024-07-22 07:28 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +    private var ratingChips: List<Chip> = emptyList()
지금 로직에서는 필요해서 추가했는데 추후에 상태 로직 리팩하면서 수정해보겠습니다

2024-07-22 07:37 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +        if (selectedGenres.value?.contains(genre) == true) {
오잉 contains 반환값이 Boolean타입아닌가유?

2024-07-22 07:38 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/DetailExploreViewModel.kt
> +        if (selectedGenres.value?.contains(genre) == true) {
boolean 타입 맞는데 null 체크에서 걸렸어요

2024-07-22 07:42 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/info/DetailExploreInfoFragment.kt
> +    private var ratingChips: List<Chip> = emptyList()
지금 pr 에서 수정했는데 한 번 더 확인 가능하신가유 ㅎㅎ

2024-07-22 07:49 UTC, s9hn approved these changes
띵지TM

2024-07-22 08:48 UTC, merged