feat: 상세 탐색 키워드 어댑터 연결
Team-WSS/WSS-Android pull request #112
Opened 2024-07-12 04:17 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #103 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 
-

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-07-12 14:44 UTC, s9hn requested changes

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +    private lateinit var detailExploreKeywordAdapter: DetailExploreKeywordAdapter
c: by lazy 안쓰신 이유가 ..?

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +    private fun setupRecyclerView() {
c: setupAdapter는어떤가요

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            detailExploreKeywordAdapter.submitList(it.keywordModel.categories)
c: 제가 uistate에서 둘을 분리한 이유입니다! 해당 옵저버가 호출될때마다 모든칩을 다시 초기화하고 세팅하게돼요!!

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            WebsosoChip(binding.root.context).apply {
c: 여기선 그냥 requireContext 줘도 될것같아요

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordAdapter.kt
> +        return DetailExploreKeywordViewHolder(binding, onKeywordClick)
c: 뷰홀더도 팩토리메서드 적용하기로 하지않았었나요!?

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordAdapter.kt
> +                    return oldItem.keywords.map { it.isSelected } == newItem.keywords.map { it.isSelected }
c: areContentsTheSame과 조금 성격이 맞지않는 비교로직일 것 같아요

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +            setupWebsosoChips(category)
c: 바인드함수가 호출될때마다 모든 칩을 다시 초기화해줍니다

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/model/DetailExploreKeywordModel.kt
> +        categories.flatMap {
a: flatMap할일이 있나요? true애들만 따로 모은건가요?

2024-07-12 14:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/model/DetailExploreKeywordUiState.kt
> +    val keywordModel: DetailExploreKeywordModel = DetailExploreKeywordModel(emptyList()),
a: 모델의 기본생성자는 모델내부에서 하는건 어떠신가요?

2024-07-13 06:58 UTC, librarywon reviewed
고생하셨습니다 코드리뷰 반영해주세요!

2024-07-13 06:58 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/remote/response/KeywordResponseDto.kt
> +        data class KeywordResponseDto(
c: `KeywordResponseDto` 둘중 하나 이름을 변경하는 것이 어떠신지 혼동의 여지가 있어보여요

2024-07-13 06:58 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            )
c: 이 Adapter도 팩토리 메서드 패턴이 적용되어야 하지 않나요?

2024-07-13 06:58 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordViewModel.kt
> +                    }
a: 산군에서도 봤는데 저도 이 로직 잘 써먹겠습니다.

2024-07-19 02:02 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +    private lateinit var detailExploreKeywordAdapter: DetailExploreKeywordAdapter
ㅎㅎ .. 자꾸 습관성으로 lateinit var 를 사용하네요 ㅎㅎ ;; ㅎ

2024-07-19 02:04 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/remote/response/KeywordResponseDto.kt
> +        data class KeywordResponseDto(
최상단 클래스가 Keywords였는데 s 가 빠졌나보네요 찾아주셔서 감삼다

2024-07-19 02:05 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            detailExploreKeywordAdapter.submitList(it.keywordModel.categories)
이 부분은 다시 고민해보겠습니다! 지적해주셔서 감사해요

2024-07-19 11:40 UTC, yeonjeen reviewed
안녕 뭉치~ 어프는 아니지만 한 번 와봤엉:) 파이팅이얌

2024-07-22 05:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/model/DetailExploreKeywordModel.kt
> +        categories.flatMap {
넵 숙고 코드인데 아마 코드 의도는 아마 선택된 애들만 모아서 업데이트 하려고 한 것 같아요

2024-07-22 05:51 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +            setupWebsosoChips(category)
초기 한 번만 세팅해줬을 때 선택된 칩들에서 x 버튼 눌렀을 경우 리사이클러뷰의 칩들의 상태가 해제가 안 되며.. 숙고 피셜 초기화를 해주어야 칩들의 위아래 디자인이 예쁘게 반영된다고 합니다...

2024-07-25 04:48 UTC, junseo511 reviewed
상부상조메타 야무지네요~~!! 범위를 반씩 쪼개면서 해당 키워드의 id보다 큰지 작은지 탐색하면 복잡도를 logn까지 줄일 수 있을거같아요...! 근데 전체적인 연산에서 유의미한 차이는 없을듯?

2024-07-25 04:48 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/mapper/KeywordMapper.kt
> +        keywordId = keywordId.toInt(),
c: Int 타입으로 변환해주시는 이유가 있나요?

2024-07-25 04:48 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/model/KeywordsEntity.kt
> +}
c: 저 처음에 이렇게 묶어서 쓰다가 분리함,,, 생각보다 얘 쓸곳이 많더라구요...? 작품평가만 그런가?

2024-07-25 04:48 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +    }
a: 오호 바인드를 없애는건 신박하군요

2024-07-25 05:01 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/mapper/KeywordMapper.kt
> +        keywordId = keywordId.toInt(),
오 꼼꼼하시네요 int 타입이 맞습니다. 이거 숙고님 코드 가져온 건데 숙고님도 코드 고치셔야 할 듯용 ㅋ.ㅋ 키워드 id 는 명세에 int로 되어있슴다~!

2024-07-25 05:03 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/KeywordsEntity.kt
> +}
전 아직 잘 모르겠어서 ? ?

2024-07-25 05:05 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +    }
`bind` 라는 의미로 통용적으로 사용하긴 하던데 굳이 제 로직에서는 `bind` 로 사용하지 않아도 될 것 같아서요! 무조건 뷰홀더에서 '`bind` 함수를 써야한다' 는 아닌 것 같습니다~

2024-07-26 11:56 UTC, s9hn approved these changes
띵지티엠~

2024-07-26 11:56 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +        val currentSelectedKeywords: List<DetailExploreKeywordModel.CategoryModel.KeywordModel> = selectedKeywords
a: 매개변수랑 같은거 아닌가용 .. ?

2024-07-26 11:56 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +    val isChipSetting: Boolean get() = _isChipSetting
c: ㅋ.ㅋboolean 백킹까진 안써도 될거같아요

2024-07-26 11:56 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +                chip.isSelected = keywordSelectionMap[chip.text] ?: false
c: 흠! 제 생각에~.. 저도 과거에 이런 칩그룹 기능들을 구현할때 UI 상호작용 할때마다 뷰모델 상태업데이트하고 이거 관찰해서 리스트로받아서 순회하고 칩업데이트 해줬습니다. 이번에 웹소소 구현할 때는 해당 방식이 비효율적이라고 생각해서, 누르는 즉시 UI를 업데이트하고 뷰모델은 상태만 업데이트합니다(옵저빙x). 그리고 작품찾기같은 다음 트랜잭션이 발생할 때 서버통신을 시키는 식으로 구현했는데 이건 어떤가요?

2024-07-28 06:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +    val isChipSetting: Boolean get() = _isChipSetting
넣으면 안 대나요. ?

2024-07-28 06:28 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +                chip.isSelected = keywordSelectionMap[chip.text] ?: false
조은 생각인 것 같습니다. 특히 사용자가 칩을 수십 개를 on/off 할 수 있고 그 때마다 업데이트 해야하는 로직이 번ㄱㅓ로운 것 같아요! 해당 내용 오늘 자세히 알려주심 감사합니다.

2024-07-28 12:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +    val isChipSetting: Boolean get() = _isChipSetting
하나의 프로퍼티로 어떻게 해야 같은 효과를 낼 수 있을까요

2024-07-28 12:40 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +        val currentSelectedKeywords: List<DetailExploreKeywordModel.CategoryModel.KeywordModel> = selectedKeywords
그렇네요 왜 ㄹ이렇게 했을까...

2024-08-01 07:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
> +                chip.isSelected = keywordSelectionMap[chip.text] ?: false
근데 이건 성공 못했ㅁ음 ㅋㅋㅋ ㅠㅠㅋㅋㅋ ㅠㅠㅠㅠㅠ😭

2024-08-01 07:38 UTC, yeonjeen approved these changes

2024-08-01 07:39 UTC, junseo511 approved these changes

2024-08-02 12:07 UTC, s9hn approved these changes

2024-08-02 12:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +        DetailExploreKeywordAdapter(detailExploreKeywordViewModel::updateClickChipState)
r: clicked or selected

2024-08-02 12:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +        }
c: you know 'sequence'? 
```kotlin
val selectedKeywords = categories.asSequence()
    .flatMap { it.keywords.asSequence() }
    .filter { it.isSelected }
    .map { it.keywordName }
    .toList()
```

2024-08-02 12:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordViewModel.kt
>                  } else {
c: 난 얼리리턴이나 when문이 더 좋더라 ..

2024-08-02 12:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/adapter/DetailExploreKeywordViewHolder.kt
>          for (i in 0 until binding.wcgNovelRatingKeyword.childCount) {
c: forEach같은 순회함수가 throw에 더 안전해보여요!

2024-08-02 12:19 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordViewModel.kt
>                  } else {
쩝

2024-08-02 12:41 UTC, merged