feat: 작품상세 뷰 API 연결
Team-WSS/WSS-Android pull request #132
Opened 2024-07-24 18:46 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #44

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 직렬화 버전 업
- API 모듈 패키지 구성
- 작품 정보 조회, 좋아요 기능 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/490f8572-919b-4f0d-ade4-27c5304fe03b

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-07-28 08:41 UTC, m6z1 approved these changes
SukGo~ TM

2024-07-28 08:41 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
> +    ): Response<Unit>
a: responsde<unit> 있어야 하나요?

2024-07-28 08:41 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +    private val serverGenres: List<String> by lazy {
c: `serverGenre` 변수명이 어떤 것을 뜻하나요?

2024-07-28 08:41 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +    @ApplicationContext private val context: Context,
r: 유스케이스에서는 뷰를 알고 있으면 안 될 것 가타요

2024-07-28 08:41 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +    private val koreanUiGenres: List<String> by lazy {
a: koreanUiGenres 네이밍이 몬가 다른 게 없을까여?

2024-07-28 08:41 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +        serverGenres.zip(koreanUiGenres).toMap()
a: zip 문법에 대해서 설명해주실 수 있나여 ? 처음 본느 친구에여

2024-07-28 08:41 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +            }.onFailure {}
a: onFailure 은 왜 아직 안 넣으셨나여

2024-07-28 08:41 UTC, m6z1 commented on app/src/main/res/layout/activity_novel_detail.xml
> +            type="kotlin.jvm.functions.Function0" />
a: 오 이건 매개변수가 없으면 0으로 사용할 수 있는 건가보네요

2024-07-28 08:48 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
> +    ): Response<Unit>
나한테도 달지않음? ㅋㅋ 
a: ResponseDto Model이 별도로 없는 경우에 Response<Unit> 형식으로 Result를 받아야했습니다만, 지금 사용중인 레트로핏 버전이 최신버전인데 이 버전부터 아예 표기 안해도 응답 받을 수 있도록 업데이트 된 걸로 얼핏 들은거같아용. 
서버통신 지금 연결되시면 한번 반환타입 아예 없애고 해보시죠( 결과 알려주삼. 나도 바꿔야함 )

2024-07-28 09:38 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
> +    ): Response<Unit>
그래서 없어두 된다구 생각해서 단 거엿슴 ㅎㅎ 제가 통신해서 쓸 때는 안 썼던 것 같아서

2024-07-28 10:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
> +
r: 
```suggestion

    @Provides
    @Singleton
    fun providesNovelApi(retrofit: Retrofit): NovelApi = retrofit.create()
```
이렇게만 써도 된단 사실.. ㅎㅎ  
Retrofit 라이브러리에서 create타입만 명시해주면 알아서 서비스 객체를 만들어주는 확장함수를 제공합니다.

2024-07-28 10:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
> +    suspend fun postUserInterest(novelId: Long) {
a: post 요청만 보내면 클라이언트에선 끝일까요?

2024-07-28 10:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +    @ApplicationContext private val context: Context,
r: 도메인 모듈에서 안드로이드 의존성을 가진 테스트를 어떻게 진행하죠?

2024-07-28 10:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +            formattedGenres(novelDetailEntity.novelGenres.split(",")),
c: 확장함수로 만드는게 가독성은 좀 더 이쁠듯용

2024-07-28 10:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    private val userNovelRepository: UserNovelRepository,
r: 힐트 사용 시 다음처럼 NovelRepository, GetNovelDetailUseCase(NovelRepository) 사용하게 되면 어떤 문제가 발생할 수 있을까용

2024-07-28 10:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                novelDetailUseCase.invoke(novelId)
c: invoke를 호출하는 이유가 있나요?

2024-07-28 10:53 UTC, s9hn commented on app/src/main/res/layout/activity_novel_detail.xml
> +            type="kotlin.jvm.functions.Function0" />
a: 우리가 아는 람다는 Function 타입의 구현체들입니다.

2024-07-29 00:43 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/repository/NovelRepository.kt
> +    suspend fun postUserInterest(novelId: Long) {
이부분 로직좀 살짝 수정할듯요

2024-07-29 00:47 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/remote/api/NovelApi.kt
> +    ): Response<Unit>
레트로핏 버전 냠냠굿~

2024-07-29 00:49 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +    @ApplicationContext private val context: Context,
저도 고민했는데 그냥 이거 도메인 말고 뷰에서 처리하는게 나을듯

2024-07-29 01:34 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +    private val serverGenres: List<String> by lazy {
서버에서 명시해준 장르명들인데 날릴듯싶네요~~

2024-07-29 01:35 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +            }.onFailure {}
좋아요에 실패했을때에 대한 로직이 따로 없어서 비워뒀습니다

2024-07-29 01:40 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +            }.onFailure {}
따로 UI에 자연스러운 변화정도는 주면 좋을듯 싶네요~~

2024-07-29 01:42 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +        serverGenres.zip(koreanUiGenres).toMap()
<img width="742" alt="image" src="https://github.com/user-attachments/assets/27fad5a4-f10f-446c-aab3-eaceb1082dc7">

공식문서를 가져왔습니다!

2024-07-29 01:45 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
> +
굉장히 편리한 친구가 있었군요 개쩔탱 👍

2024-07-29 01:47 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    private val userNovelRepository: UserNovelRepository,
음... 의존성이 꼬일 수가 있나용? 그럼 레포지토리랑 유즈케이스를 별도로 사용해야 할때는 어떻게 불러오나요?!

2024-07-29 07:36 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    private val userNovelRepository: UserNovelRepository,
캐싱하는 경우 데이터 동기화가 되지 않는 문제가 발생할 수도 있습니다!
지금 코드는 별도의 캐싱을 하지 않으니 이런 문제는 없겠지만, 단순히 api를 호출하는 레포지토리 인스턴스를 2개나 만들 필요는 없겠죠?

2024-07-29 07:44 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    private val userNovelRepository: UserNovelRepository,
아 생각해보니 지금은 api만 연결하고 있군요!! 현재는 체감을 잘 못하지만 점점 규모가 늘어날수록 Domain의 역할이 커진다고 현업자분이 말씀하시긴 했습니다 헣헣 🤔 함 고민해보죠

2024-08-01 01:06 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +    private val koreanUiGenres: List<String> by lazy {
이부분 통째로 날렸습니다 긁적 산군 카테고리 들고왔어용~

2024-08-01 01:15 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +            formattedGenres(novelDetailEntity.novelGenres.split(",")),
산군거 잘쓰겠습니다 냠

2024-08-01 01:15 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                novelDetailUseCase.invoke(novelId)
근데 붙이는거하고 안붙이는거 어떤 차이인지 아직 잘 모르겟삼 생략해도 똑같이 동작하는건가

2024-08-01 03:02 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +            formattedGenres(novelDetailEntity.novelGenres.split(",")),
제가 무엇을..만들었죠

2024-08-01 06:59 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +            formattedGenres(novelDetailEntity.novelGenres.split(",")),
ㅋㅋㅋㅋㅋ 비슷한게 있어서 가져와서 냠냠 수정햇어요

2024-08-02 06:17 UTC, librarywon requested changes
수고했숩니다요!

2024-08-02 06:17 UTC, librarywon commented on app/build.gradle.kts
> +        buildConfigField("String", "BASE_URL", gradleLocalProperties(rootDir).getProperty("base.url"))
a: 감사합니두

2024-08-02 06:17 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/ApiModule.kt
> +
저도 이거 리뷰 받고 알았습니다

2024-08-02 06:17 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +object NetworkModule2 {
r: NetworkModule2??????

2024-08-02 08:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +object NetworkModule2 {
ㅋㅋㅋㅋㅋㅋㅋ 아씨 산군의 점진적 리팩토링 강습이었습니다

2024-08-02 09:12 UTC, librarywon approved these changes
고생하셨습니다!

2024-08-02 12:16 UTC, s9hn approved these changes

2024-08-02 12:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/model/NovelRatingEntity.kt
> +    val novelTitle: String? = null,
c: null로 두신이유가 있나요?

2024-08-02 15:16 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/model/NovelRatingEntity.kt
> +    val novelTitle: String? = null,
api가 비슷한 역할을 하고 보내는 형태도 유사한데 보내는 형태가 달라야할 때가 잇어서 기본값으로 null을 두었습니다

2024-08-03 08:08 UTC, merged