feat: 마이페이지 내 서재 장르취향 ui 구현
Team-WSS/WSS-Android pull request #149
Opened 2024-07-31 17:49 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #146 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 장르취향 xml
- 하위 나머지 장르 리스트뷰 구현
- 토글 visible 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/b05a9d2c-3dc9-4260-82f0-9b23ec2a7f6f

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
리스트의 아이콘이 왜 저렇게 뜰까요?

1.  아이콘 파일의 문제인가? > 이미지 파일로 교체해보고, 다른 아이콘 파일로도 해봤는데 안되는걸로 보아 리소스 파일의 문제는 아닌 것 같아요...
2. scaleType의 문제인가? > centerInside, fitCenter로 다 해봤는데 해결 놉
3. 아이템이 유동적으로 늘어나지 않는 것인가? > height를 wrap_content로 해놨어요...
4. 리스트뷰 안에 있는 이미지의 크기는 고정적인데 그에 비해 내가 가진 아이콘이미지가 너무 커서 그런건가? > 아이템 이미지뷰의 크기를 바꾸면 네모의 크기도 달라져요. 즉 리스트뷰 아이템 안에 있는 이미지뷰도 크기가 유동적으로 변할 수 있는거죠.

그렇다면 대체 뭐가 문제일까용...

2024-08-01 00:06 UTC, m6z1 reviewed
수정해야 할 부분들이 있어서 수정 후에 멘션 주시묜 어프루브 해드리겠습니다👍❤️

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    private val myLibraryBinding get() = _binding ?: error("error: myLibraryBinding is null")
r: BindingFragment 쓰면 이 친구들은 쓸 필요 없어요 바인딩 프래그먼트 구조 한 번 보시면 조을 듯 합니다🙌

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    private fun setUpObserveViewModel() {
r: setupObserver

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        onGenrePathToggled()
r: 클릭리스너에 대한 네이밍은 컨벤션 찾아서 수정하시면 좋을 것 같아요

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
r: 장르 어댑터를 초기화해주는 로직인데 메서드 네이밍과는 맞지 않은 것 같아요 한 번 수정해보시면 어떨까요?

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    private fun updateRestGenrePreferenceVisibility(isVisible: Boolean) {
c: restGenrePreference 혹은 restPreferenceGenre 중에 통일성 있게 지으면 좋을 것 같슴다

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        )
a: 이 친구들은 나중에 서버에서 내려주면 변경될 예정인가욤?

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
> +class MyLibraryViewModel : ViewModel() {
r: 힐트 어노테이션 붙여줘야 함니다

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
> +    fun toggleGenreListVisibility() {
c: updateToggleGenresVisibility 요런 건 어때요?

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +):BaseAdapter() {
r: 포맷팅 부탁드려용

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +):BaseAdapter() {
a: 요 baseAdapter는 어던 친구인가요??

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/res/layout/fragment_my_library.xml
> +                <androidx.appcompat.widget.LinearLayoutCompat
a: linearLayoutCompat이 무엇인가요?? LinearLayout을 쓰지 않으신 이유도 궁금해요!

2024-08-01 00:06 UTC, m6z1 commented on app/src/main/res/layout/item_rest_genre.xml
> +            android:src="@{genrePreference.genreIcon}"
a: 리스트 아이콘이 제대로 뜨지 않는 이유는 이 친구 때문인 것 같아요 지금 genreIcon이 int타입으로 되어있고 뷰모델에서 더미데이터로 사용하려고 했던 것 같은데 src는 데바로 이렇게 사용 못 하는 걸로 알고 있어요

2024-08-01 00:25 UTC, s9hn requested changes

2024-08-01 00:25 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        myLibraryBinding.lvMyLibraryRestGenre.adapter = adapter
r: 해당 함수가 호출될 때마다 어댑터 인스턴스를 재생성하고 있습니다

2024-08-01 00:25 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
> +    val isGenreListVisible: LiveData<Boolean> = _isGenreListVisible
r: liveData 값 초기화에 apply를 사용할 필요없이 인자에 바로 넣어주면 됩니다

2024-08-01 00:25 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +    var items:List<GenrePreferenceEntity>
r: 생성자가 가변일 필요가 있을까요?

2024-08-01 00:25 UTC, s9hn commented on app/src/main/res/layout/item_rest_genre.xml
> +            android:text='@{String.format("%d편", genrePreference.genreCount)}'
r: string resource로 관리해보시죠. genrePreference.genreCount만 넘겨도 될 수 있게요!

2024-08-01 00:26 UTC, junseo511 reviewed
고생하셨습니당~~!!!!

2024-08-01 00:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
c: 데바를 사용해 보시는건?

2024-08-01 00:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    private fun setUpObserveViewModel() {
r: 저희 한창 논쟁했던 컨벤션...!

2024-08-01 00:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        )
c: 이친구도 데이터바인딩 붙이는거 어떠신가요~~ 저희 거의 데이터 바인딩으로 이루어져 있는데

2024-08-01 00:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +        binding.executePendingBindings()
a: 오호 이친구는 어떤 역할이죠

2024-08-01 00:26 UTC, junseo511 commented on app/src/main/res/layout/item_rest_genre.xml
> +            android:src="@{genrePreference.genreIcon}"
c: 이거 추후에도 로컬에서 가지고 있는 정보인가요? 바인딩 어댑터를 잘 사용해보시면 좋을듯 ㅇㅂㅇ

2024-08-01 00:26 UTC, junseo511 commented on app/src/main/res/layout/item_rest_genre.xml
> +            android:text='@{String.format("%d편", genrePreference.genreCount)}'
c: 이친구 텍스트 추출해주시면 좋을듯요

2024-08-01 00:29 UTC, s9hn commented on app/src/main/res/layout/fragment_my_library.xml
> +                    android:layout_height="wrap_content"
r: recyclerview 혹은 listview의 height가 wrap이면 해당 위젯이 어떻게 높이를 측정해야할까요?

2024-08-01 05:53 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    private fun setUpObserveViewModel() {
수정했슴당

2024-08-01 05:55 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +        binding.executePendingBindings()
리스트뷰가 영역은 잡히는데 뜨지 않는다는 문제가 있었어서 이 메서드가 대기중인 바인딩을 실행시켜주는 역할을 한다고해서 추가해봤습니당

2024-08-01 06:03 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    private val myLibraryBinding get() = _binding ?: error("error: myLibraryBinding is null")
수정하겠슴당

2024-08-01 06:04 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
> +    fun toggleGenreListVisibility() {
아핳.. 그게 더 좋을 것 같아용 반영하겠슴당

2024-08-01 06:13 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +):BaseAdapter() {
산군께서 알려주셨는뎅 어댑터 패턴을 사용해서 데이터소스를 리스트뷰에 바인딩하기 위해서 사용되는 추상 클래스입니당

2024-08-01 06:17 UTC, yeonjeen commented on app/src/main/res/layout/fragment_my_library.xml
> +                <androidx.appcompat.widget.LinearLayoutCompat
진짜.. 죄송하지만 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ linear까지만 치고 자동완성으로 입력되어서 이걸 사용한 줄도 몰랐거든요?.....죄송해여,,,, 그래서 한 번 알아봤는데~ 보통 저희가 사용하는 LinearLayout은 최신 Android SDK를 타겟팅하고 있고, 이전 버전과의 호환성이 크게 문제가 되지 않는 경우 사용하고, LinearLayoutCompat은 이전 버전의 Android와의 호환성을 유지해야 하거나, Support Library 또는 AndroidX Library의 다른 기능들을 이미 사용하고 있는 경우 사용한다고 합니당. 제가 따로 Support Library 나 AndroidX Library을 추가하지 않았는데 아무 문제 없이 실행되는걸로 보아 이미 해당 라이브러리가 추가되서 사용되고 있었던 것 같아용 Android의 다양한 API 레벨에서 일관된 동작을 보장하기 위해 사용된다고 하니 사용해도 문제가 없지 않을까용...?

2024-08-01 06:32 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        onGenrePathToggled()
수정완햇습니당

2024-08-01 06:41 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        )
이 부분도 데바를 사용해서 수정해보려고 합니당

2024-08-01 06:42 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    private fun updateRestGenrePreferenceVisibility(isVisible: Boolean) {
수정했습니당

2024-08-01 06:45 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
initializeGenreAdapter로 수정했는데 어떤가용?

2024-08-01 06:53 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        )
서버에서 내려주는거랑 토글 visible이랑 어떤 관련이 있을까용?

2024-08-01 07:01 UTC, yeonjeen commented on app/src/main/res/layout/item_rest_genre.xml
> +            android:src="@{genrePreference.genreIcon}"
더미데이터 이미지를 url이미로 수정해서 해볼게용

2024-08-01 07:09 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        )
지금 제가 언급한 코드는 토글 가시성이 아니라, 토글 가시성에 따른 이미지 변경이예욥

2024-08-01 07:11 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
그것두 좋구 setupGenreAdapter() ? 다 괜찮은 것 같아욤

2024-08-01 08:56 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +    var items:List<GenrePreferenceEntity>
수정완했슴당

2024-08-01 08:59 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        myLibraryBinding.lvMyLibraryRestGenre.adapter = adapter
그러면 해당 함수는 한 번만 호출하고 데이터가 변경하게 된다면 어뎁터의 데이터를 업데이트 하는 방향으로 수정하면 될까용?

2024-08-01 09:13 UTC, yeonjeen commented on app/src/main/res/layout/item_rest_genre.xml
> +            android:text='@{String.format("%d편", genrePreference.genreCount)}'
수정했슴당

2024-08-01 09:26 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
적용완했슴당~

2024-08-01 09:57 UTC, yeonjeen commented on app/src/main/res/layout/fragment_my_library.xml
> +                    android:layout_height="wrap_content"
내부 아이템들에 따라서 동적으로 높이 측정을 해야합니다! 혹시 이게 성능의 문제를 줄까요?

2024-08-01 11:43 UTC, m6z1 approved these changes

2024-08-01 19:29 UTC, yeonjeen commented on app/src/main/res/layout/fragment_my_library.xml
> +                    android:layout_height="wrap_content"
방금 확인해봤을 때 리스트뷰를 펼치지 않은 상태에서는 내부 스크롤이 일어나는데 리스트뷰가 visible 되면 스크롤이 안된다는 문제가 있었습니다! 또 내부 스크롤 후에 리스트뷰를 visible 하니까 첫 번재 아이템만 뜨고 나머지 아이템들은 뜨지 않는다는 문제가 잇었는데 이게 모든 자식항목들 높이의 합이 전체 부모 레이아웃의 높이로 설정되지 않아서 일어나는 일이었을까요...? > 내부 아이템들에 따라서 동적으로 높이 측정이 안되고 있어서 그랬던 것 같아요... 그래서 따로 확장 함수를 만들어서 문제는 해결했는데 맞는 방법인지는 잘 모르겠어서;;; 확인 부탁드립니당(꾸벅)

2024-08-02 06:09 UTC, librarywon requested changes
리뷰 확인해주세요!

2024-08-02 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +) : BaseAdapter() {
c: BaseAapter는 처음봐서 채택하시느 이유가 무엇인가요?

2024-08-02 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/util/ViewExtensions.kt
> +}
r: 줄바꿈이나 코드 정렬이 되었으면 좋겠네요

2024-08-02 06:13 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/util/ViewExtensions.kt
> +}
수정하겠슴당

2024-08-02 06:23 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/RestGenrePreferenceAdapter.kt
> +) : BaseAdapter() {
(저도 산군의 권유로 사용하게 되었는데 그래서 공부해본 결과 이런 장점이 있다고 합니다...!) 기존에 기본적으로 제공해주는 어댑터 클래스들도 있지만 이들은 주로 단순한 데이터 세트를 처리하는 데 사용됩니다! 하지만 BaseAdapter를 사용하면 데이터가 더 복잡한 경우에도 적합한 어댑터를 작성할 수 있어서 필요에 맞게 어댑터를 커스텀 할 수 있다는 장점이 있습니다. 그래서 제가 만든 리스트뷰의 경우에 하나의 아이템 안에 텍스트와 이미지뷰가 여러개 들어가 있는데 이런 경우 baseadpater을 사용하는게 더 이롭다고 생각했습니당! 또한 성능을 최적화할 수 있는 다양한 방법을 구현할 수 있는데 저같은 경우는  convertView가 null일 때만 새로운 뷰를 생성하고, 그렇지 않으면 기존의 convertView를 재사용하는 패턴을 이용해서 성능을 최적화 할 수 잇도록 했습니다!

2024-08-02 09:03 UTC, librarywon approved these changes
연진 티엠 👍

2024-08-04 14:49 UTC, s9hn approved these changes
어려운 뷰였는데 잘해냈네요 고생해씁미다

2024-08-04 14:50 UTC, merged