Feature/record UI
Team-WSS/WSS-Android pull request #18
Opened 2024-01-06 16:34 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #8 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- xml 구현
- 리사이클러뷰 구현
- null 화면 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
- NovelCount가 0일 때
<img width="465" alt="image" src="https://github.com/Team-WSS/WSS-Android/assets/144861180/d727b1b3-f9e0-4226-bb64-8d1d85b06c99">
![image](https://github.com/Team-WSS/WSS-Android/assets/144861180/afd32e99-2bf7-474d-bc21-4cc3738bcd5e)

- NovelCount가 1이상일 때
<img width="720" alt="image" src="https://github.com/Team-WSS/WSS-Android/assets/144861180/37df4f3e-205b-453d-b10c-571783e9dbfb">
Screen_recording_20240107_013136.webm

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
서버연결 전이라서 리사이클러뷰의 데이터나 작품의 수는 제가 임의로 넣었습니다!

2024-01-06 16:56 UTC, junseo511 approved these changes
고생하셨습니당~~

2024-01-06 16:56 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        val novelCount = "0"
오호 novelCount를 String으로 넘겨받기로 한건가요?

2024-01-06 16:56 UTC, junseo511 commented on app/src/main/res/layout/fragment_record.xml
> +
선생님 여기 줄바꿈이 이상합니다

2024-01-06 16:56 UTC, junseo511 commented on app/src/main/res/layout/fragment_record.xml
> +
여기도요!

2024-01-06 17:55 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        val novelCount = "0"
넵 여러가지 자료들을 보았을 때 이 방법이 가장 많았던 것 같아요.

2024-01-06 17:55 UTC, yeonjeen commented on app/src/main/res/layout/fragment_record.xml
> +
아이.. 이런

2024-01-06 17:55 UTC, yeonjeen commented on app/src/main/res/layout/fragment_record.xml
> +
수정했슴다

2024-01-07 09:22 UTC, librarywon requested changes
고생했습니다. 리뷰 확인해주세요!

2024-01-07 09:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +    override fun onBindViewHolder(holder: RecordViewHolder, position: Int) {
함수들 사이에 개행 부탁드립니다!

2024-01-07 09:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +    }
```suggestion
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecordViewHolder {
    val inflater = LayoutInflater.from(parent.context)
    val binding = ItemMemoBinding.inflate(inflater, parent, false)
    return RecordViewHolder(binding)
}
```
Adapter의 매개변수로 context를 받지 않고 `LayoutInflater.from(parent.context)`로 받아오는 것이 좋을 것 같습니다.

그리고 `RecordViewHolder` 인스턴스를 `RecordAdapter`에서 만들고 있는데 `RecordViewHolder`에서 만드는 방법을 알아보시는 것이 좋을 것 같습니다. 

제 3차과제 PR과 공부했어요 노션을 참고해주세요

2024-01-07 09:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewHolder.kt
> +        binding.tvMemoContent.text = memo.novelContent
```suggestion
        with(binding) {
                tvMemoDate.text = memo.novelDate
                tvMemoTitle.text = memo.novelTitle
                tvMemoContent.text = memo.novelContent
        }
```

2024-01-07 09:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +    private val mockMemoList = listOf<Memo>(
이 안에 더미 값은 companion object로 빼는것이 좋을 것 같습니다

2024-01-07 09:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +    private fun handleNovelCount() {
함수의 이름이 모호한 것 같습니다 novelCount를 handle한다고 생각이 드는데 NovelCount에 따른 UI변경에 관한 이름으로 변경해보시겠어요?

2024-01-07 09:22 UTC, librarywon commented on app/src/main/res/layout/fragment_record.xml
> +        android:layout_height="wrap_content"
제약조건을 자세히 걸고 0dp로 설정해주세요 나머지 TextView,ImageView를 제외한 나머지 뷰들 동일합니다.

2024-01-07 09:22 UTC, librarywon commented on app/src/main/res/layout/item_memo.xml
> +        app:layout_constraintTop_toBottomOf="@id/tvMemoTitle" />
4줄이 넘어가면 ...으로 보이는 기능을 추가했나요?

2024-01-07 09:31 UTC, m6z1 approved these changes
고생했더요

2024-01-07 09:33 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        }
```suggestion
when (novelCount.toIntOrNull()) {
    0 -> {
        binding.lyRecordNull.visibility = View.VISIBLE
        binding.lyRecord.visibility = View.GONE
    }
    else -> {
        binding.lyRecord.visibility = View.VISIBLE
        binding.lyRecordNull.visibility = View.GONE
    }
}
```
코틀린스럽게 수정 가능하겠네요

2024-01-07 10:03 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +
수정했습니다!

2024-01-07 10:05 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +    override fun onBindViewHolder(holder: RecordViewHolder, position: Int) {
넵 수정했습니다!

2024-01-07 10:06 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +    fun setFriendList(memoList: List<Memo>) {
수정했습니다!

2024-01-07 11:59 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +    }
제가 정확하게 이해한건지 모르겠지만 viewholder와 adapter를 분리하여 viewholder 내부에서 viewholder를 직접 선언하고 가독성과 유지보수성을 향상시키는 방법이 맞을까요? 코드 수정했습니다! 확인해보시고 답변 부탁드립니다!

2024-01-07 12:02 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewHolder.kt
> +        binding.tvMemoContent.text = memo.novelContent
이렇게 하면 객체를 호출할 때마다 하나 하나 작성할 필요가 없겠네요! 감사합니다:)

2024-01-07 12:14 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +    }
데일리 스크럼 끝나고 설명드리겠습니다!

2024-01-07 12:28 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +    private fun handleNovelCount() {
handleNovelCountUiChanges() 로 함수명을 바꾸었습니다! 확인 부탁드립니다!!

2024-01-07 12:40 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +    private val mockMemoList = listOf<Memo>(
넵! 수정했습니다! 감사합니다:)

2024-01-07 13:00 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        }
그러네용! when으로 수정했습니다!

2024-01-07 13:03 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        val novelCount = "0"
아아!! 맞아요!! 서버에서 받아온 값을 string에 있는 %d랑 연결할겁니다!!

2024-01-07 13:22 UTC, librarywon reviewed
리뷰확인부탁드립니다.

2024-01-07 13:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        memoAdapter.setFriendList(mockMemoList)
어뎁터 init() 설정도 함수로 분리해보시면 좋을 것 같네요

2024-01-07 13:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        val novelCount = "6"
이런 상수값도 compnion에 정의하면 추후 유지보수에 도움이 될 것 같고 
생각해보니 viewModel을 아직 만들지 않으신 이유가 있을까요?

2024-01-07 13:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewHolder.kt
> +    }
이걸 설명하려고 했는데 이미 잘 적용하셨네요!

2024-01-07 13:38 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        memoAdapter.setFriendList(mockMemoList)
한다고 했는데 깜빡했네요...! 수정했습니다!!

2024-01-07 13:42 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +        val novelCount = "6"
아 뷰모델을 사용하면 되네요...; 아직도 viewModel을 제대로 활용하지 못하고 있는 것 같습니다..! 적용해보겠습니다!

2024-01-07 16:12 UTC, s9hn approved these changes

2024-01-07 16:12 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/Memo.kt
> +data class Memo(
구현중인 뷰의 디렉터리 내부의 Model 패키지에 위치시켜도 될 것 같습니다!

2024-01-07 16:12 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +    private var memoList: List<Memo> = emptyList()
어째서 variable인가요~? 
추가로 프로퍼티명에 원시타입 사용은 지양해주세요 !

2024-01-07 16:12 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +    private fun init() {
개발자는 함수이름만 보고도 어떤 일을 하는지 알아야합니다!
init 함수는 무엇을 init하는지 알 수가없습니다

2024-01-07 16:12 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
>          fun newInstance() = RecordFragment()
@librarywon  함수가 아니여도 될 것 같군요 !

2024-01-07 16:12 UTC, s9hn commented on app/src/main/res/layout/fragment_record.xml
> +        android:id="@+id/lyRecord"
PRND 컨벤션 복기하기 !

2024-01-07 16:12 UTC, s9hn commented on app/src/main/res/layout/item_memo.xml
> +        android:id="@+id/vMemoLongLine"
v는 view입니다!

2024-01-07 16:33 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
> +    private fun init() {
리사이클러뷰를 초기화하고 메모리스트를 설정하는 함수입니다! 그래서 setupRecyclerViewWithMemo()로 변경하였습니다!

2024-01-07 16:38 UTC, yeonjeen commented on app/src/main/res/layout/fragment_record.xml
> +        android:id="@+id/lyRecord"
수정했습니다! 감사합니다!

2024-01-07 16:40 UTC, yeonjeen commented on app/src/main/res/layout/item_memo.xml
> +        android:id="@+id/vMemoLongLine"
수정했습니다!

2024-01-07 16:47 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/Memo.kt
> +data class Memo(
넵! 반영했습니다!!

2024-01-07 16:59 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
> +    private var memoList: List<Memo> = emptyList()
일단 var로 선언한 이유는 리스트가 초기화되고 업데이트되면서 리스트가 변경될 수 있어야 하기 때문에 variable로 선언했습니다. 프로퍼티명은 memoItems로 수정하겠습니다!

2024-01-07 17:58 UTC, m6z1 commented on app/build.gradle.kts
> +
굿이에용

2024-01-07 18:09 UTC, m6z1 approved these changes

2024-01-07 18:17 UTC, librarywon approved these changes
수고하셨습니다 Merge it!

2024-01-07 18:18 UTC, merged