feat: 탐색 뷰 메인화면 구현
Team-WSS/WSS-Android pull request #19
Opened 2024-04-10 15:13 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #7 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 탐색 뷰 메인화면 뷰 구현했습니다.
- ui 단에서 목데이터 만들어서 리사이클러뷰 연결했습니다.
- Recyclerview 높이 잘림 현상 발견해서 수정 중입니다. > 첫 뷰홀더에 들어가는 아이템 너비 / 높이 값으로 재활용돼서 잘림 (밑 사진 참고 - 첫번째 아이템의 작품 이름이 한 줄이라 마지막 아이템에 들어가야 할 `역대급영지설계사입니다어쩌구저쩌구` 텍스트가 두 줄이 안 되고 1줄로 잘림)
<img width="323" alt="스크린샷 2024-04-11 오전 12 05 11" src="https://github.com/Team-WSS/WSS-Android/assets/114990782/33e4d6c8-9772-43fc-a4ac-921b767ad924">
- 그 외 아직 작업 X

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
<img width="350" alt="스크린샷 2024-04-11 오전 12 05 11" src="https://github.com/Team-WSS/WSS-Android/assets/114990782/6f29d340-fc74-401f-9183-5d134d175f34">

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-04-11 09:09 UTC, s9hn reviewed
앱잼 때 코드 스타일과 조금 다른느낌이네요?

2024-04-11 09:09 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/explore/ExploreFragment.kt
> +    private lateinit var sosoPickAdapter: SosoPickAdapter
lateinit 쓰시는 이유가 있으십니까 ?

2024-04-11 09:09 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/explore/ExploreFragment.kt
> +            addItemDecoration(SosoPickItemDecoration(SOSO_PICK_ITEM_RIGHT_OFFSET))
프래그먼트에서 오프셋을 주입해주는 이유가 있나요?
범용적인 데코레이션 객체를 만들기 위함이었나요?
데코레이션 객체를 사용하기 위한 필수조건이 rightOffsetDp값만인가요?
그렇다면 팀원들은 해당 객체를 사용하기 위해 rightOffsetDp값이 필수임을 알 수 있을까요?
이를 좀 더 명시적으로 바꿔볼 수 있을까요?

2024-04-11 09:09 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/explore/adapter/SosoPickAdapter.kt
> +    private val sosoPickData: List<SosoPickData> = SosoPickData.sosoMockData
목데이터도 레포지터리에서 관리해보시죠 !

2024-04-11 09:09 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/explore/adapter/SosoPickViewHolder.kt
> +    RecyclerView.ViewHolder(binding.root) {
불필요한 개행

2024-04-11 09:09 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/explore/adapter/SosoPickViewHolder.kt
> +        binding.tvExploreSosoPickNovelTitle.text = sosoPickData.title
데이터바인딩을 사용하지 않은 이유가 무엇인가요 ?

2024-04-11 09:09 UTC, s9hn commented on app/src/main/res/layout/fragment_explore.xml
> +    <ScrollView
스크롤뷰를 사용하신 이유가 무엇인가요?

2024-04-11 09:09 UTC, s9hn commented on app/src/main/res/layout/fragment_explore.xml
> +                style="@style/headline1"
textAppearance를 사용하지 않은 이유는 무엇인가요 ?

2024-04-11 09:09 UTC, s9hn commented on app/src/main/res/layout/fragment_explore.xml
> +                    app:layout_constraintHorizontal_bias="0"
불필요해보입니다 !

2024-04-11 09:09 UTC, s9hn commented on app/src/main/res/layout/fragment_explore.xml
> +            <androidx.recyclerview.widget.RecyclerView
스크롤뷰와 같이쓰면 어떤 문제가 발생할까요 ?

2024-04-11 10:40 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/explore/adapter/SosoPickAdapter.kt
> +    private val sosoPickData: List<SosoPickData> = SosoPickData.sosoMockData
fakeRepo로 쓰다가 바꿔치기하고 한 번에 붙는 쾌감..(느껴보고 싶다)

2024-04-11 10:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/explore/adapter/SosoPickViewHolder.kt
> +        binding.ivExploreSosoPickNovelCover.load(sosoPickData.image)
얘도 제가 추가한 바인딩 어뎁터로 적용하면 좋을 것 같네요

2024-04-12 00:13 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/explore/ExploreFragment.kt
> +    private lateinit var sosoPickAdapter: SosoPickAdapter
그냥 지연초기화하고 싶어서 썼는데 다시 생각해보니 어댑터라서 값이 변경될 필요가 없으니 lazy 로 변경해보겠슴다.

2024-04-12 00:33 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/explore/ExploreFragment.kt
> +            addItemDecoration(SosoPickItemDecoration(SOSO_PICK_ITEM_RIGHT_OFFSET))
> 프래그먼트에서 오프셋을 주입해주는 이유가 있나요?
범용적인 데코레이션 객체를 만들기 위함이 맞아요

> 데코레이션 객체를 사용하기 위한 필수조건이 rightOffsetDp값만인가요?
다시 생각해보니 범용적으로 만드려면 무조건 rightOffsetDp로 하면 안 되겠군요 . . . 

> 그렇다면 팀원들은 해당 객체를 사용하기 위해 rightOffsetDp값이 필수임을 알 수 있을까요? 이를 좀 더 명시적으로 바꿔볼 수 있을까요?
수정해보겠슴다

2024-04-12 00:34 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/explore/adapter/SosoPickViewHolder.kt
> +    RecyclerView.ViewHolder(binding.root) {
![image](https://github.com/Team-WSS/WSS-Android/assets/114990782/4aee92f5-c75f-4625-a23b-7959c515d818)

2024-04-12 00:36 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/explore/adapter/SosoPickViewHolder.kt
> +        binding.tvExploreSosoPickNovelTitle.text = sosoPickData.title
서버 api 붙일 때 바꾸려고 했는데 fake repo 사용하면서 데바로 바꾸겠슴다 ~.~

2024-04-12 00:39 UTC, m6z1 commented on app/src/main/res/layout/fragment_explore.xml
> +                style="@style/headline1"
`textAppearance` 사용할 생각을 못하고 있었어요 ㅎ `style` 과 `textAppearance` 의 차이에 대해 찾아보니 지금 설정된 값들과 뷰가 텍스트 뷰인 점을 참고하여 textAppearance 쓰는 게 더 맞을 것 같아서 변경하겠슴다

https://stackoverflow.com/questions/38517090/what-is-the-difference-between-textviews-style-and-androidtextappearance-attri

2024-04-12 16:36 UTC, junseo511 reviewed
벌써 예쁘게 만드셧군요,,,! 허허 저는 아직도 난항입니다 😭

2024-04-12 16:36 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/explore/ItemIntervalDecoration.kt
> +        }
toPx를 따로 만들어서 함께 쓰면 어떤가요

2024-04-12 16:36 UTC, junseo511 commented on app/src/main/res/layout/fragment_explore.xml
> +                    android:contentDescription="@null"
노란줄 불편으로 넣으신건가요? ㅋㅋㅋㅋ

2024-04-12 16:36 UTC, junseo511 commented on app/src/main/res/layout/item_soso_pick.xml
> +            android:gravity="top|start"
아니 그래비티도 | 가 써지는지 지금 알았네요

2024-04-28 08:01 UTC, m6z1 commented on app/src/main/res/layout/fragment_explore.xml
> +                    android:contentDescription="@null"
넴

2024-04-28 08:02 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/explore/ItemIntervalDecoration.kt
> +        }
이 클래스 삭제하고 아이템 데코레이션 없이 만들어볼 예정이라, 나중에 범용적인 아이템 데코레이션 만들 때 반영하겠습니다

2024-04-30 06:12 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/explore/ExploreFragment.kt
> +            addItemDecoration(SosoPickItemDecoration(SOSO_PICK_ITEM_RIGHT_OFFSET))
#19 피알에서는 데코레이션 사용 X
#42 상세 탐색 결과 기능 구현에서 범용적인 데코레이션 사용 예정

2024-05-02 09:22 UTC, s9hn requested changes
아예 싹 다른코드가 됐네요 ㅋㅋ 고생하셨씁미다
MJTM

2024-05-02 09:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/model/SosoPickEntity.kt
> +data class SosoPickEntity(
이름이 의미하는 바가 무엇인지 모르겠습니다

2024-05-02 09:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/model/SosoPicksEntity.kt
> +)
```kotlin
data class SosoPicksEntity(
  val novels: List<NovelEntity>,
) {

  data class NovelEntity(
     val novelId: Long,
...
  )
}

```

와 같은건 어떠신가요

2024-05-02 09:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +                LinearLayoutManager(requireContext(), LinearLayoutManager.HORIZONTAL, false)
이거 그냥 xml로 빼면 안돼요? ㅋㅋ

2024-05-02 09:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +}
조금 이거 복붙냄새가 나네 ..

2024-05-02 09:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreViewModel.kt
> +    private val fakeSosoPickRepository: FakeSosoPickRepository
트레일링 콤마

2024-05-02 09:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/adapter/SosoPickAdapter.kt
> +    private val sosoPickItemClickListener: (Long) -> Unit,
람다로 넘겨주는 인자가 무엇인지도 명시해주면 더욱 이해하기 편하겠네요.

2024-05-02 09:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/adapter/SosoPickAdapter.kt
> +        return oldItem == newItem
아래 함수와 같은 로직인데요?

2024-05-02 09:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/adapter/SosoPickViewHolder.kt
> +        binding.root.setOnClickListener {
아이템이 10000개이면, 10000번의 onBind함수 호출마다 클릭리스너를 넣어줘야할까요?
데이터바인딩으로 람다를 넘길수는 없나요?

2024-05-02 10:10 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/SosoPickEntity.kt
> +data class SosoPickEntity(
얘 이름이 소소픽인데 .... 어떤 네이밍을 원하시는 건지 잘 모르겠습니다
통일성 맞춰서 진행한 건데 다른 걸로 바꾸는 게 나을까요 ?
> ex) SosoPickNovelEntity ? ..
<img width="369" alt="스크린샷 2024-05-02 오후 6 26 03" src="https://github.com/Team-WSS/WSS-Android/assets/114990782/5e4ffed9-82b0-43fd-b815-62e8dbd96f4c">

2024-05-02 10:10 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +}
ㅋㅎㅎ 잘 썼습니다~

2024-05-02 10:10 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/SosoPicksEntity.kt
> +)
그렇게 될 경우, 추후에 Novel<< 이라는 네이밍을 사용하시는 분들이 계실 것 같아 중복의 우려가 있어, 차라리 `SosoPickNovelEntity` 라는 네이밍은 어떤가요 ?
```kotlin
data class SosoPicksEntity(
  val novels: List<SosoPickNovelEntity>,
) {

  data class SosoPickNovelEntity(
     val novelId: Long,
...
  )
}

```

2024-05-02 10:10 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +                LinearLayoutManager(requireContext(), LinearLayoutManager.HORIZONTAL, false)
산군님 그렇게 하셨으니 얼라인 맞출게요. 수정하겠습니다.

2024-05-02 10:10 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/adapter/SosoPickAdapter.kt
> +        return oldItem == newItem
ㅋㅋㅋㅋ 그렇네여 ; ㅎㅎ

2024-05-02 10:33 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/adapter/SosoPickViewHolder.kt
> +        binding.root.setOnClickListener {
함수 타입으로 넘겨서 수정했습니다.
<img width="528" alt="스크린샷 2024-05-02 오후 7 32 47" src="https://github.com/Team-WSS/WSS-Android/assets/114990782/bb2dc47f-0b8c-45a6-96af-09712aea4984">

2024-05-02 10:57 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/model/SosoPicksEntity.kt
> +)
중복 우려가 있나요?

2024-05-02 10:59 UTC, s9hn approved these changes
굿

2024-05-02 10:59 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/adapter/SosoPickAdapter.kt
> +    private val sosoPickItemClickListener: (novelID: Long) -> Unit,
novelId .

2024-05-02 10:59 UTC, s9hn commented on app/src/main/res/layout/fragment_explore.xml
> +            type="com.teamwss.websoso.ui.main.explore.adapter.SosoPickAdapter" />
이건 뭔데 어댑터를 넘겨받나요?

2024-05-02 11:02 UTC, m6z1 commented on app/src/main/res/layout/fragment_explore.xml
> +            type="com.teamwss.websoso.ui.main.explore.adapter.SosoPickAdapter" />
이거 지웠어요 잘못 넣었던 거

2024-05-02 11:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/SosoPicksEntity.kt
> +)
그럴리 없겠네요 ㅎ 반영하겠습니다

2024-05-03 06:23 UTC, librarywon approved these changes
명지 정말 수고했습니당

2024-05-03 06:23 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +                LinearLayoutManager(requireContext(), LinearLayoutManager.HORIZONTAL, false)
이거 최소 10번은봄 ㅋㅋ

2024-05-03 06:23 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +    }
함수 만들어두기

2024-05-03 06:23 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/model/SosoPickUiState.kt
> +)
새로운 방식 잘 배우고 갑니다요

2024-05-03 06:27 UTC, merged