feat: 차단유저 목록 api 연결
Team-WSS/WSS-Android pull request #204
Opened 2024-08-14 12:48 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #203

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 차단유저 목록 보기 api 연결했습니다.
- 차단유저 해제하기 api 연결했습니다.
- 목록이 비어있을 때 뷰 구현했습니다.

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/a7663f8d-891b-4c48-bbb0-01a6b3cacd15

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-08-14 15:14 UTC, librarywon requested changes
고생했습니다!

2024-08-14 15:14 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/model/BlockedUsersEntity.kt
> +
c: 원래 여기 비우나요?

2024-08-14 15:14 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersViewModel.kt
> +                    blockedUsers = emptyList(),
c: `blockedUsers.isNotEmpty()`인데 또 빈 리스트를 넣어줄 필요가 있나요?

2024-08-14 15:14 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersViewModel.kt
> +                    blockedUsers = emptyList(),
null일수도 있으니까?

2024-08-14 15:34 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/BlockedUsersEntity.kt
> +
저는 비우긴 했어염

2024-08-14 15:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/BlockedUsersEntity.kt
> +
그치만 제거하겠습니다 ^.^ 다른 것들 보니 붙여놨네요

2024-08-14 15:44 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/blockedUsers/BlockedUsersViewModel.kt
> +                    blockedUsers = emptyList(),
테스트 할 때 들어간 거 안 지웠네요 매의 눈 굿

2024-08-14 15:57 UTC, librarywon approved these changes

2024-08-15 06:43 UTC, junseo511 approved these changes

2024-08-15 06:48 UTC, merged