Feat/207
Team-WSS/WSS-Android pull request #208
Opened 2024-08-15 08:56 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 
-

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-08-15 14:08 UTC, junseo511 approved these changes
거의 UI 공장이시네요 요즘 ㄷㄷ 고생하셨습니다

2024-08-15 14:08 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
> +        userApi.patchProfileStatus(userProfileStatusEntity.toRemote())
a: 아 서버로 보내는건 toRemote인가요? 이런 저도 바꿔야겠네요

2024-08-15 14:59 UTC, s9hn approved these changes
좋은코드!

2024-08-15 14:59 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
> +        userApi.patchProfileStatus(userProfileStatusEntity.toRemote())
a: 서버에 보내는 함수 컨벤션도 있나요 ..?

2024-08-15 14:59 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
> +    private var initIsProfilePublic: Boolean = false
a: isInitializeOfProfilePublic 이런건 어떤가용

2024-08-15 20:52 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
> +        userApi.patchProfileStatus(userProfileStatusEntity.toRemote())
넹 카톡에 사진 올림

2024-08-15 20:56 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
> +                    error = false,
a: 에러 true로 수정하기

2024-08-16 04:41 UTC, librarywon requested changes
고생하셨습니다 리뷰 확인해주세요!

2024-08-16 04:41 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/remote/response/UserProfileStatusResponseDto.kt
> +data class UserProfileStatusResponseDto(
c: 여기는 또 개행을 안하시네요?

2024-08-16 04:41 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
> +    }
a: `updateIsCompleteButtonEnabled()` 함수가 먼저 등장할 것을 기대하고 읽었는데 activity에서 쓰이는 함수가 불렸네요 순서를 바꿔보심은 어떠신지

2024-08-16 04:41 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
> +                val isProfilePublicValue = isProfilePublic.value ?: initIsProfilePublic.not()
c: 프로필 공개여부가 null이였을 때 공개여부를 not()으로 주신 이유가 궁금합니다.

2024-08-16 04:41 UTC, librarywon commented on app/src/main/res/layout/activity_profile_disclosure.xml
> +                android:src="@drawable/btn_account_info_check_unselected"
r: 이미지 리소스 이름이 시작이 img말고 btn이 들어가는게 맞을까요?

2024-08-16 05:43 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/remote/response/UserProfileStatusResponseDto.kt
> +data class UserProfileStatusResponseDto(
답변 나겼는데 개행 안 하는 걸로 수정했습니다

2024-08-16 05:49 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
> +                val isProfilePublicValue = isProfilePublic.value ?: initIsProfilePublic.not()
이 부분은 잘 짠 로직이라 생각하는데요 ㅎㅎ, 이 함수가 호출 되는 경우는 무조건 기존 상태에서 반대의 경우일 때 호출이 됩니다. (기존 상태에서 변경됐을 시 완료 버튼을 눌러 새로운 상태를 업데이트 할 수 있음) 그래서 이 함수가 호출됐는데 정말 만약 null값일 경우에도 기존 상태의 반댓값으로 업데이트 시키게 하는 것이죠 그래서 기존상태의 반대인 .not()을 붙였습니다

2024-08-16 05:50 UTC, m6z1 commented on app/src/main/res/layout/activity_profile_disclosure.xml
> +                android:src="@drawable/btn_account_info_check_unselected"
처음엔 btn이 맞았는데, 컨레 전체 클릭으로 바꾸면서 img로 바꾸는 게 맞을 것 같습니다 ~

2024-08-16 05:51 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileDisclosure/ProfileDisclosureViewModel.kt
> +                val isProfilePublicValue = isProfilePublic.value ?: initIsProfilePublic.not()
사실 그거 인줄 알고 물어봤습니다 체고체고

2024-08-16 07:01 UTC, librarywon approved these changes
명지TM

2024-08-16 07:01 UTC, merged