Feat/11
Team-WSS/WSS-Android pull request #21
Opened 2024-04-10 17:28 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #11

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 마이페이지 프로필 xml 
- 서재/피드 뷰페이저 구현
- 서재 보관함, 선호장르 xml 
- 

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
프래그먼트 파일 오류나서 해결하고 커밋할거구요... xml 아직 다 못했구여... 코리는 다 하면 요청 드릴게여 아직 많이 남아서용..;; 너무 졸려서 오늘은 잘게요...

2024-06-16 06:08 UTC, m6z1 requested changes
고생하셨어요! 코멘트들 확인해주시면 감사하겠슴다 ㅎ.ㅎ
그리고 resource 파일명 네이밍에 where 넣기로 했었는데 안 들어간 곳이 많은 것 같아서 확인 부타캐요

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/AndroidManifest.xml
> -        android:name=".WebsosoApp"
이거 지우면 안 되어여 빌드가 안 될 텐데

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/AndroidManifest.xml
> -            android:exported="false" />
이 액티비티들은 왜 다 삭제하셨죠??

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/AttractivePointData.kt
> +    val pointCount : Int,
포맷팅을 습관화하시면 좋을 것 같슴다

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/GenrePreferredData.kt
> +    data class GenreTop(
`GenreTop` 과 `GenreBottom` 이라는 네이밍이 어색한 것 같아요.
뷰를 보니 장르 top3 와 top3 아닌 것들을 얘기하는 것 같은데 뷰를 모른다면 알기 어려운 네이밍이라구 생각함니다.
그리구 Top과 Bottom의 데이터 클래스 구조가 아예 같은데 따로 분리해서 사용해야 하는 이유가 있는지도 궁금해여

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/GenrePreferredData.kt
> +sealed class GenrePreferredData {
data 레이어에서 사용하는 Data class의 네이밍은 XXXEntity 로 끝나야 합니다!
<img width="261" alt="스크린샷 2024-06-16 오후 2 33 19" src="https://github.com/Team-WSS/WSS-Android/assets/114990782/ec2567e9-8298-454c-b780-0d00470f89b7">

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +class MyPageFragment : Fragment() {
`Hilt` 랑 `BindingFragment` 를 왜 제거하셨나요??

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageViewModel.kt
> +    private val _myPageProfile = MutableLiveData<MyPageProfileData>().apply {
타입을 명시해주면 좋을 것 같아요!

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myfeed/MyFeedFragment.kt
> +class MyFeedFragment : Fragment() {
여기도 `BindingFragment` 있는데 `Fragment` ?!

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private fun observeViewModel() {
`initializeViews`에서 호출한 함수를 `initializeViews` 바로 밑에 선언하면 좋을 것 같아요

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        })
```suggestion
libraryViewModel.genres.observe(viewLifecycleOwner) { genres ->
            updateGenreBottomList(genres)
        }
```

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        })
마찬가지로 밑에 사용하고 있는 observe 함수들도 수정해주시면 좋을 것 같아요 👍

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        libraryViewModel.attractivePoints.value?.let { attractivePoints ->
얘는 왜 observe 패턴을 사용하지 않았나용?

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private fun createChip(data: AttractivePointData): Chip {
`createChip`보다 `observe`함수에서 사용한 `updateXXX`함수들이 우선적으로 선언되어야 할 것 같아요

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        binding.listPreferredGenreBottom.visibility = if (isVisible) View.VISIBLE else View.GONE
```suggestion
        binding.listPreferredGenreBottom.isVisible = isVisible
```

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    }
클릭리스너에 대한 함수라면 네이밍을 수정하는 게 좋을 것 같아요!
<img width="967" alt="스크린샷 2024-06-16 오후 2 53 19" src="https://github.com/Team-WSS/WSS-Android/assets/114990782/5deac27d-2856-4357-96d9-a062ac7bb065">

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryViewModel.kt
> +            GenrePreferredData.GenreBottom(R.drawable.ic_novel_detail_genre_test, "로판", 3),
추후에 장르 아이콘은 서버에서 내려주는 건가요? 
만약에 맞다면, string 값을 내려줄 것 같은데
지금 데이터 레이어에 있는 `GenreBottom` 데이터클래스에서는 GenreIcon이 Int 타입이더라구여. Int는 drawable 파일에 있는 리소스를 사용하기 위함이라면 ui에 사용될 데이터 모델을 따로 추가해주는 게 맞는 것 같아요!

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
> +    }
이 바인딩 어댑터는 어디에 왜 사용되는 건가염?

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/res/drawable/bg_gray50_radius_14.xml
bg_`where`_gray50_radius_14`dp`

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/res/drawable/bg_primary50_radius_12.xml
여기도 where이랑 dp 추가!

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/res/layout/fragment_my_page.xml
> +                android:id="@+id/iv_go_to_settings"
우리 컨벤션이 component_`where`_description 이라서 where 전체적으로 써주시면 좋을 것 같아요

2024-06-16 06:08 UTC, m6z1 commented on app/src/main/res/values/ids.xml
이 파일은 어디에서 사용되고 있는 건가요?? 그리고 네이밍이 파일 네이밍이 ids,,?

2024-06-16 07:51 UTC, yeonjeen commented on app/src/main/AndroidManifest.xml
> -        android:name=".WebsosoApp"
커밋이 안된 것 같아용! 커밋했습니당

2024-06-16 07:51 UTC, yeonjeen commented on app/src/main/AndroidManifest.xml
> -            android:exported="false" />
여기도 커밋이 안된 부분이었어용...

2024-06-16 08:04 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/model/GenrePreferredData.kt
> +    data class GenreTop(
네이밍 부분은 수정이 필요할 것 같네용... 음 FavoriteGenre / RestGenre라는 네이밍은 어떨까요? 그리고 데이터 클래스 구조를 다르게 한 건 서버 통신 할 때 따로 통신이 될 예정이라서 그렇게 한건데 문제가 될까요?

2024-06-16 08:16 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/model/GenrePreferredData.kt
> +    data class GenreTop(
네이밍은 수정이 필요한 부분일 것 같아용.. BestPreferredGenre / RestPreferredGenre 라는 네이밍은 어떤가요? 그리고 따로 분리해서 사용한 건 2개가 따로 서버통신을 할 예정이라 분리했던 것도 띵지님 말씀처럼 구조가 같아서 같이 사용해도 될 것 같아용!

2024-06-16 08:16 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/model/GenrePreferredData.kt
> +sealed class GenrePreferredData {
앗.. 수정하겠습니당!

2024-06-16 08:31 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +class MyPageFragment : Fragment() {
제가..제거하지..않았.... 뭘까여..... 수정하겠습니당

2024-06-16 10:24 UTC, librarywon reviewed
수고했습니다 코드리뷰 차근차근 반영해주세요!

2024-06-16 10:24 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myfeed/MyFeedFragment.kt
> +package com.teamwss.websoso.ui.myPage.myfeed
myPage는 이렇게 카멜케이스인데 myfeed는 적용이 안되어 있는거 같네요 library처럼

2024-06-16 10:24 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    private val binding get() = _binding!!
`_binding!!` !!를 적용하신 이유가 있으신가요?

2024-06-16 10:24 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +            if (isVisible) R.drawable.ic_upper_path else R.drawable.ic_lower_path
데바를 사용하고 selector를 사용하면 이렇게 적용 안해도 되긴합니다!

2024-06-16 10:24 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
> +    }
저는 듣지 못했던 바인딩 어뎁터 추가인데 혹시 언급을 하셨을까요?

2024-06-16 10:24 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/GenreBottomAdapter.kt
> +            binding.genreBottom = genre
genre 타입 명시도 해주세요!

2024-06-16 12:38 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/GenrePreferredData.kt
> +    data class GenreTop(
서버통신이 다르다면 다른 클래스를 사용해도 될 지도 ......?

2024-06-17 09:17 UTC, s9hn requested changes
고생하셨씁니다! 몇 군데 수정이 필요해보여 RC로 걸어두겠씁니당
LGGGTTMM

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/model/GenrePreferredData.kt
> +sealed class GenrePreferredData {
preferred가 앞에 오는게 자연스러울 것 같습니다.
PrefferedGenreEntity

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    private val viewModel: MyPageViewModel by viewModels()
프래그먼트에서 액티비티 뷰모델을 쓴다면 어떤 네이밍을 부여하실 생각이신가요?

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +        binding.viewModel = viewModel
현재 라이브데이터에 생명주기를 지정해주는 코드가 없어보입니다.

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageViewModel.kt
> +    private val _myPageProfile = MutableLiveData<MyPageProfileData>().apply {
프로퍼티에 apply를 쓰시는 이유가 있을까요 ?

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyViewPagerAdapter.kt
> +    FragmentStateAdapter(fragmentManager, lifecycle) {
FragmentManager와 lifecycle를 넘겨줄 필요가 있나요?

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    private fun setupViewPagerAndTabs() {
해당 함수가 호출될 때마다 어댑터 인스턴스가 초기화되고 있습니다.

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/GenreBottomAdapter.kt
> +    context: Context,
어댑터에 컨텍스트를 넘겨줄 필요 없이, getView의 인자로 오는 parent로부터 context를 얻어올 수 있습니다.
binding을 하고 있다면, binding.root의 컨텍스트 또한 사용 가능합니다.

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/GenreBottomAdapter.kt
> +) : ArrayAdapter<GenrePreferredData.GenreBottom>(context, resource, items) {
ArrayAdapter로 선택한 이유가 궁금해요

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private val libraryViewModel: MyLibraryViewModel by viewModels()
여기는 이름 명시해주셨네? 일관성 통일 바랍니다

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        })
저도 이 방식이 좀더 가독성이 좋아보입니다.

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        libraryViewModel.attractivePoints.value?.let { attractivePoints ->
let을 어느 경우에 사용하는 것이 좋을까요?

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        chip.setTextAppearance(R.style.body2)
개행도 코드입니다! 깔끔히 정리바랍니다.
오히려 이런곳에 apply라던가 with이라던가 가독성 개선을 위해 스코프함수를 활용할 수 있겠네요

2024-06-17 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private fun adjustListViewHeight(listView: ListView) {
어쩔 때 리스트뷰의 크기를 확장시켜주나요?

2024-06-17 16:41 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myfeed/MyFeedFragment.kt
> +class MyFeedFragment : Fragment() {
뭘까여... 수정하겠습니당...

2024-06-17 16:43 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageViewModel.kt
> +    private val _myPageProfile = MutableLiveData<MyPageProfileData>().apply {
앗! 넵! 수정하겠습니다

2024-06-17 16:48 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private fun observeViewModel() {
함수 순서 변경했습니다!

2024-06-17 16:56 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        })
함수 수정했습니다!

2024-06-17 17:02 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        libraryViewModel.attractivePoints.value?.let { attractivePoints ->
미쳐반영하지 못한 부분인 것 같네용..! 이 부분도 라이브데이터를 사용하기 때문에 observe 패턴을 사용해주는게 좋을 것 같아용

2024-06-17 17:14 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private fun createChip(data: AttractivePointData): Chip {
함수 선언 순서를 변경했는데 확인부탁드려용!

2024-06-17 17:15 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        binding.listPreferredGenreBottom.visibility = if (isVisible) View.VISIBLE else View.GONE
더 간결해졌네용! 감사합니다:)

2024-06-17 17:24 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    }
아직 함수명 변수명이 젤 어려운 안드삐약이입니다,,, 알려주셔서 감사해용

2024-06-17 17:45 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
> +    }
선호작품부분에 매력포인트들이 '피폐 7'이렇게 표시되어야 하는데 '피폐'는 string으로 '7'는 int로 넘어와서 그걸 합쳐주는 과정에서 사용합니다!

2024-06-17 18:15 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryViewModel.kt
> +            GenrePreferredData.GenreBottom(R.drawable.ic_novel_detail_genre_test, "로판", 3),
그럼 glid이용해서 이미지 업로드하는 방식으로 바꿔볼게요!

2024-06-18 12:33 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myfeed/MyFeedFragment.kt
> +package com.teamwss.websoso.ui.myPage.myfeed
아핳 수정하겠습니당

2024-06-18 12:35 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    private val binding get() = _binding!!
_binding이 null이 아님을 이야기해주고 싶었던건데 null 안정성을 보장해주는게 좋을까요?

2024-06-18 12:48 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/GenreBottomAdapter.kt
> +            binding.genreBottom = genre
수정하겠습니다!

2024-06-18 12:54 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/model/GenrePreferredData.kt
> +sealed class GenrePreferredData {
아핳 그러네용 수정하겠습니다

2024-06-18 12:57 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    private val binding get() = _binding!!
`FragmentMyPageBinding` 자료형을 명시해줘서 null이 아님을 알려줄 수 있을 것 같습니다

2024-06-18 13:17 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +            if (isVisible) R.drawable.ic_upper_path else R.drawable.ic_lower_path
오홓... 한 번 수정해볼게요!

2024-06-18 13:24 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    private val viewModel: MyPageViewModel by viewModels()
아핳... 변수명 바꿨습니다...ㅎ

2024-06-18 13:24 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private val libraryViewModel: MyLibraryViewModel by viewModels()
넹...ㅎ

2024-06-19 08:55 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +        binding.viewModel = viewModel
추가하도록하겠슴당..!

2024-06-19 09:02 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageViewModel.kt
> +    private val _myPageProfile = MutableLiveData<MyPageProfileData>().apply {
객체 생성과 설정을 한 곳에서 할 수 있어서 사용했습니다.

2024-06-19 14:46 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private fun adjustListViewHeight(listView: ListView) {
리스트뷰가 스크롤뷰 안에 존재하는데 그럴 때 리스트뷰에 있는 모든 아이템들을 보여주기 위해 확장시켜줍니다

2024-06-19 14:46 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        chip.setTextAppearance(R.style.body2)
넵...ㅎ

2024-06-19 15:01 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/GenreBottomAdapter.kt
> +) : ArrayAdapter<GenrePreferredData.GenreBottom>(context, resource, items) {
일단 리스트의 아이템 구조가 대부분 문자열로 간단한 구조이고, 기본으로 제공하는 기능으로도 충분히 원하는 뷰를 구현할 수 있다고 판단해서 array adapter을 사용했습니다.

2024-06-19 15:07 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyViewPagerAdapter.kt
> +    FragmentStateAdapter(fragmentManager, lifecycle) {
음... 생각해보니 필요 없을 것 같아요 이미 어댑터에서 내 서재와 내 피드 프레그먼트를 고정적으로 사용하고 있으니 굳이 넘겨줄 필요 없는 것 같아용.. 수정하겠습니다!

2024-06-19 15:11 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/GenreBottomAdapter.kt
> +    context: Context,
아핳!!!! 수정하겠습니당 감사합니다:)

2024-06-19 17:24 UTC, yeonjeen commented on app/src/main/res/values/ids.xml
칩에 들어가는 텍스트 때문에 필요한건뎅 xml에서 id를 정의하는데 사용하는 건데 원래 네이밍을 저렇게 하는거라고(?) 알고있어용

2024-06-19 17:30 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        libraryViewModel.attractivePoints.value?.let { attractivePoints ->
nullable한 객체를 처리하고자 할 때 사용하는 것이 좋다고....ㅎ  대신 지금 뷰모델에서 livedata를 쓰고 있는데 observe하지 않고 단순히 value를 가져와서 사용하고 있어서 이 부분 수정했는데 나중에 확인 부탁드려용:)

2024-06-19 17:33 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/GenreBottomAdapter.kt
> +    context: Context,
넵 적용해보겠습니당

2024-06-19 17:43 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageViewModel.kt
> +    private val _myPageProfile = MutableLiveData<MyPageProfileData>().apply {
```kotlin
  private val _myPageProfile = MutableLiveData<MyPageProfileData>(
           MyPageProfileData(
            avatarImage = "https://velog.velcdn.com/images/yeonjeen/post/73663b4d-ead3-41fa-bab9-4fd1a1651f91/image.png",
            genrePreferences = listOf("Fantasy", "Romance", "Action"),
            intro = "안녕 나는 사실 연진이야",
            nickname = "연진"
        )
)
````
로 생성하면 됩니다

2024-06-19 17:47 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +        libraryViewModel.attractivePoints.value?.let { attractivePoints ->
let의 best practice에 대해서 공부하고 알려주세요

2024-06-19 17:47 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private fun adjustListViewHeight(listView: ListView) {
항상 확장되어있는 상태인가요?

2024-06-19 17:49 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/mylibrary/MyLibraryFragment.kt
> +    private fun adjustListViewHeight(listView: ListView) {
넹넹 그 장르 아이콘을 피그마 사이즈에 맞게 해서 내려봤는데 잘리더라고요? 그래서 확장시켜주는 함수를 썼어요

2024-06-24 06:17 UTC, junseo511 reviewed
리뷰가 늦어서 죄송합니둥!! 바쁨이슈 ㅠㅠ
제 코드도 리뷰해주시면 감사하겠습니다... ㅎ

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/model/MyLibraryStorageData.kt
> +    val quitNovel : Int,
`소설` 의 자료형이 Int인 이유가 있나요?

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    }
```suggestion
    override fun onDestroyView() {
        _binding = null
        super.onDestroyView()
    }
```

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    private fun setupViewPagerAndTabs() {
2222

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
어떤 뷰'들'을 초기화하고 있나요? 하나는 옵저빙하고 있고 하나는 셋온클릭리스너가 달려있는 것 같아요

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
오호 함수분리를 하셨군요 저도 해볼까봐요 👍

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
위에도 뷰모델을 옵저브하는 코드가 있는거같아요

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        for (i in 0 until listAdapter.count) {
forEach같은거 써보는건 어떠세요?

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
> +    }
String 리소스를 통해 장르 리스트를 넘겨줄 수 있는 방법은 없을까용 해리 코드에서도 리뷰했던 내용인데 추후 언어를 변경해야 한다면 어떻게 되는지??에 대한 생각 🧐

2024-06-24 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
> +    }
저는 어댑터를 추가하지 않고 액티비티에서 진행했는데 숫자 + 문자 + 숫자 순으로 나와야해서요!!
혹시 추가에 대해 논의가 진행된 어댑터일까요?!

2024-06-25 05:06 UTC, m6z1 approved these changes
굿굿임다 훨씬 코드 가독성이 올라갔네요 수정하느라 넘 고생하셨어요 👍 👍 
drawable 네이밍 컨벤션만 수정 부탁드려요!!

2024-06-25 05:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +    private val myPageBinding get() = _binding ?: error("error: binding is null")
바인딩 프래그먼트면 이 친구들 없애려고 사용하는 거라서 없애두 됩니다! 
밑에 onDestroy 메서드도 마찬가지입니다

2024-06-25 05:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myFeed/MyFeedFragment.kt
> +
두 줄! 얼른 CI 구축해볼게요 ^^...

2024-06-25 05:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myFeed/MyFeedFragment.kt
> +class MyFeedFragment : Fragment() {
얘도 BindingFragment 사용하면 코드가 최소 10줄은 줄어들 것이라 장담합니다

2024-06-25 05:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +class MyLibraryFragment : Fragment() {
얘도 마찬가지, `BindingFragment` 받아와서 사용하면 좋을 것 같아요 
다른 파일들도 전부`BindingFragment`, `BindingActivity` 로 수정 부탁드려요

2024-06-25 05:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryViewModel.kt
> +
눈에 띄어서 ... 코드리뷰 남겨요 추후에 꼭 CI를 ...... (먼 산)

2024-06-25 05:06 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
> +    }
xml 에서 사용하는 방법 혹시 못 찾으셨을까여

2024-06-25 09:30 UTC, librarywon requested changes
리뷰 반영부탁드립니다!!

2024-06-25 09:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/model/MyPageProfileData.kt
> +    val nickname: String
R: 콤마

2024-06-25 09:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myFeed/MyFeedFragment.kt
> +class MyFeedFragment : Fragment() {
A: 생각보다 많이 보일러플레이트 코트가 줄어드네요? Base를 부정적으로 봤었는데

2024-06-25 09:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    }
R: 불필요한 함수화 같네요

2024-06-25 09:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +    private fun initializeAttractivePoints() {
R: 회의 때 결정해서 observe 혹은 setupObserve 로 변경해야할 것 같네요

2024-06-25 09:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myLibrary/MyLibraryFragment.kt
> +        )
C : 뷰바인딩 로직이 좀 많은 것 같긴하군요 데바로 바꿀 수 있다면 변경해주세요

2024-06-25 09:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/model/AttractivePointData.kt
> +data class AttractivePointData(
R: 어떤친구는 entity고 어떤친구는 Data이네요? 저희 컨벤션상 모두 Entity로 통일해야하는거 아닌가요?

2024-06-25 09:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/util/BindingAdapter.kt
> +    }
R: 이 바인딩 어뎁터는 필요 없어 보입니다. 
데이터에 변경을 주는 것은 viewModel이 할 역할이라고 생각합니다.

2024-07-13 15:36 UTC, librarywon commented
작업 중단 새로운 브렌치로 작업 예정

2024-07-13 15:36 UTC, closed without merging