feat: 작품평가 툴팁 추가
Team-WSS/WSS-Android pull request #218
Opened 2024-08-21 07:07 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #217

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 작품평가 뷰 툴팁 추가

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/4f40ba57-88b1-4abf-9e20-f859d83a9878

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
이 툴팁에 제 하루가 갈렸어요 🥲

2024-08-22 03:15 UTC, m6z1 approved these changes
고생하셨어요 b 코멘트로 질문 남겨뒀는데 답변 부탁드립니다:)

2024-08-22 03:15 UTC, m6z1 commented on app/build.gradle.kts
> +    implementation("androidx.datastore:datastore-preferences:1.1.1")
a: 다른 로컬 디비도 있는데 데이터스토어를 선택하신 이유가 궁금해요

2024-08-22 03:15 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +@Module
r: 다른 코드와 통일성 및 가독성을 위해 순서를 바꿔주시면 좋을 것 같아요

```suggestion
@Module
@InstallIn(SingletonComponent::class)
```

2024-08-22 03:15 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +            ),
a: 이 코드는 왜 필요한가요?

2024-08-22 03:15 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +            scope = CoroutineScope(Dispatchers.IO + SupervisorJob()),
a: scope를 꼭 지정해주어야 하나요?

2024-08-22 03:15 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        binding.ctlNovelDetail.viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
a: 이 viewTreeObserver는 무슨 역할을 하나요?

2024-08-22 04:20 UTC, junseo511 commented on app/build.gradle.kts
> +    implementation("androidx.datastore:datastore-preferences:1.1.1")
Room과 SharedPreference가 제 비교대상이었습니다!! Room은 사용하기에 너무 무겁고, DataStore가 상대적으로 SharedPreference에 비해 보안, 비동기처리 등에서 강점을 가지고 있다고 알고 있어 적용했습니다!!

2024-08-22 04:20 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +@Module
아 못봤네요 감사합니당

2024-08-22 04:20 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +            scope = CoroutineScope(Dispatchers.IO + SupervisorJob()),
비동기적으로 실행되는데, 부모 작업에서 에러가 발생해도 하위 작업으로 진행된다고 알고 있습니다 🧐 대부분 안정성 때문에 지정해준 옵션들입니다!!

2024-08-22 04:20 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +            ),
손상된 경우 빈 객체를 반환합니다

2024-08-22 04:20 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        binding.ctlNovelDetail.viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
뷰가 생성되는걸 감지한다고 알고있습니다! wrap_content로 설정된 항목의 높이를 측정하기 위해 사용했습니다!

2024-08-23 14:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +            scope = CoroutineScope(Dispatchers.IO + SupervisorJob()),
c: supervisorScope를 쓰시면 될 것 같습니당 :)

2024-08-23 16:40 UTC, s9hn requested changes

2024-08-23 16:40 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/repository/UserPreferencesRepository.kt
> +    private val dataStore: DataStore<Preferences>,
r: 나중에 로컬저장소가 sql room 등 다른것으로 바뀌어도 현재 이름을 계속 사용할 수 있을까요?

2024-08-23 16:40 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +object DataStoreModule {
r: DataStore만을 위한 모듈인가요?

2024-08-23 16:40 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        override fun onNavigateToNovelRatingClick(readStatus: ReadStatus?) {
a: status가 null일 수 있나요?

2024-08-23 16:40 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                userPreferencesRepository.fetchUserPreferences(UserPreferencesRepository.KEY_NOVEL_DETAIL_FIRST_LAUNCHED)
c: 뷰모델이 키 값을 알아야하나요?

2024-08-24 05:36 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                userPreferencesRepository.fetchUserPreferences(UserPreferencesRepository.KEY_NOVEL_DETAIL_FIRST_LAUNCHED)
오호 우차피 userPreference니 모듈이 가지고 있어도 될 것 같아요...! 🤔

2024-08-24 05:38 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        override fun onNavigateToNovelRatingClick(readStatus: ReadStatus?) {
화면이 이동할 때 넘겨줄 수도 있고 안넘겨줄 수도 있다는 기획의 요구사항이 있었습니다...! 🤔 근데 생각해보니 어차피 작품상세에서 기존 정보를 받긴 해서 그걸 넘겨줘도 될까 싶기도 한데, 작품평가로 넘어간 이후 api를 통해 다시 갱신하는 과정이 있어서 null로 넘겨주는게 나을거같기도 하구 그러네여

2024-08-24 06:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        override fun onNavigateToNovelRatingClick(readStatus: ReadStatus?) {
적어도 UI 레이어에선 ReadStatus 라는 클래스로 관리하고 계시다면 null을 이동시키는 것보단 Nothing, None 등으로 명시적으로 활용해보시죠

2024-08-24 06:09 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                userPreferencesRepository.fetchUserPreferences(UserPreferencesRepository.KEY_NOVEL_DETAIL_FIRST_LAUNCHED)
우리가 인텐트를 넘겨줄 때 XXXActivity.XXXKey로 가져오지 않고 생성자만 넘겨주죠? 키 값은 키를 사용하는 객체 내부에 캡슐화되어있구요. 비슷하게 구조화해봅시다! 키 값은 키를 사용하는 친구만 알게끔 캡슐화하고 필요한 데이터만 받을 수 있도록 API를 노출해보시죠

2024-08-25 14:53 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                userPreferencesRepository.fetchUserPreferences(UserPreferencesRepository.KEY_NOVEL_DETAIL_FIRST_LAUNCHED)
죠슴미다 내일 해볼게유

2024-08-26 05:58 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +            scope = CoroutineScope(Dispatchers.IO + SupervisorJob()),
```kotlin
CoroutineScope(Dispatchers.IO).launch {
            supervisorScope { 
                runCatching {
                    userPreferencesRepository.fetchUserPreferences()
                }.onSuccess { isFirstLaunched ->
                    _novelDetailModel.value = novelDetailModel.value?.copy(isFirstLaunched = isFirstLaunched)
                }.onFailure {
                    _novelDetailModel.value = novelDetailModel.value?.copy(isFirstLaunched = true)
                }
            }
        }
```

아하 supervisorScope라는 친구도 있었군요...! 이친구를 뷰모델에서 위와 같이 사용하는게 나을까요?

2024-08-26 05:58 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/repository/UserPreferencesRepository.kt
> +    private val dataStore: DataStore<Preferences>,
이것도 변수형에 의존한 이름이 될 수도 있겠네요! storage는 어떠신지?

2024-08-26 05:58 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        override fun onNavigateToNovelRatingClick(readStatus: ReadStatus?) {
None을 평소에 즐겨쓰니 None으로 가보도록 하겠습니다 ㅋ.ㅋ

2024-08-26 05:58 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +object DataStoreModule {
현재는 DataStore만 주고 있지 않나욤 ?.?

2024-08-26 06:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +object DataStoreModule {
나중에 다른 저장소도 활용할 일이 생기면 그때도 이 이름으로 사용해야하나요?

2024-08-26 06:53 UTC, s9hn requested changes

2024-08-26 06:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> -            scope = CoroutineScope(Dispatchers.IO + SupervisorJob()),
a: 스코프는 왜 빠졌나요?

2024-08-26 06:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +        CoroutineScope(Dispatchers.IO).launch {
r: 뷰모델에선 뷰모델 스코프를 쓰는 것이 권장사항입니다!  차라리 사용되어지는 dataStore 객체 내부에서 스코프를 초기화해주는게 더 좋아보입니다

2024-08-26 06:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +            supervisorScope {
+ 뷰모델스코프는 이미 supervisorJob입니다!

2024-08-26 06:53 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
> +            else -> Unit
a: ReadStatus를 사용해도 else 처리가 뜨나요?

2024-08-26 07:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
> +            else -> Unit
`ReadStatus.NONE -> ` 을 추가하니까 이제 안뜨는군요

2024-08-26 07:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +            supervisorScope {
헉 이거 처음앎

2024-08-27 07:24 UTC, s9hn approved these changes
고생하셨씁니다!!!!

2024-08-27 07:44 UTC, merged