feat: 내 활동 ui 구현
Team-WSS/WSS-Android pull request #224
Opened 2024-08-26 21:03 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #196 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 내 활동 피드 리사이클러뷰
- 장르카테고리, 날짜 -> 형식에 맞게 전환
- 수정여부, 스포일러 여부 -> 가시성 처리

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/db71bb4b-e257-40ee-853e-4a2d36d991fd

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-08-27 00:26 UTC, m6z1 reviewed
고생하셨슴다!!

요 부분이 제 예전 뷰라 저두 기억이 나는디 ㅎ,,ㅎ 스크롤이 되지 않았을 때두 탭 레이아웃 중 선택되지 않은 곳에두 선이 있어야 하는 것 같은데 영상에선 잘 보이진 않더라구요!! 있는지 확인 한 번 부탁드립니당


<img width="666" alt="스크린샷 2024-08-27 오전 9 24 03" src="https://github.com/user-attachments/assets/02e65c60-5dfe-4ded-b77e-c9132d71ebbe">

수정하시구 노티주시면 어프루브 드릴게요 😄

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/MyActivitiesEntity.kt
> +    val feeds: List<MyActivityEntity>
r: 트레일링 콤마

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeMyActivityRepository.kt
> +class MyActivityRepository @Inject constructor() {
c: 사용자의 피드 전체 조회이니, FeedRepository로 옮겨도 되지 않으까여?

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityFragment.kt
> +        setUpObserve()
r: 
```suggestion
        setupObserver()
```

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +                    relevantCategories = translateGenres(entity.relevantCategories)
r: 이 부분은 매퍼 사용해서 뷰모델에서 제거해야 할 것 같아요!

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +            val activities = myActivityRepository.getMyActivities().take(5).map { entity ->
c: runCatching도 넣어주심 좋겠네요 👍

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +    }
c: 요 부분은 ActivityModel 로 옮겨서 사용해도 좋을 것 같아요 👍

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +            outputFormat.format(date!!)
c: !! 말고 다른 방법은 없나여!?

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/model/Genres.kt
> +        fun fromString(value: String): Genres? {
r: 
```suggestion
        fun from(value: String): Genres? {
```

과 개행 한 번 부탁드려요!

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/res/layout/fragment_my_activity.xml
> +                android:text="활동기록 더보기"
c: string 추출

2024-08-27 00:26 UTC, m6z1 commented on app/src/main/res/layout/item_my_activity.xml
> +        <import type="android.view.View" />
a: 요 부분은 어디에서 사용되고 있나용?

2024-08-27 05:16 UTC, s9hn requested changes

2024-08-27 05:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityFragment.kt
> +        binding.rvMyActivity.apply {
c: 굳이 apply 쓸 필요가 없어보입니다

2024-08-27 05:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +class MyActivityViewModel @Inject constructor(private val myActivityRepository: MyActivityRepository) :
r: 생성자는 한줄부터 개행!

2024-08-27 05:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/adapter/MyActivityViewHolder.kt
> +        binding.executePendingBindings()
a: 지금 이 함수에서 어떤 역할을 하나요?

2024-08-27 05:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/model/Genres.kt
> +            return Genres.values().find { it.name.equals(value, ignoreCase = true) }
c: entries 사용합시다!

2024-08-27 07:17 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeMyActivityRepository.kt
> +class MyActivityRepository @Inject constructor() {
음.. 하지만 FeedRepository는 피드 관련 전체 데이터(전체 피드, 개별 피드, 댓글 등)을 관리하고 있고, 또한 장르별로 조회를 하기도 하는데 MyActivityRepository같은 경우는 지금은 더미데이터를 처리하고 있기도하고, 앞으로도 특정 인물에 대한 피드를 조회하는거라 분리하는게 맞다고 생각했어용!

2024-08-27 07:18 UTC, yeonjeen commented on app/src/main/res/layout/item_my_activity.xml
> +        <import type="android.view.View" />
앗.. 여기는 삭제 해야하는 부분입니당! 감사해용

2024-08-27 07:19 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/model/Genres.kt
> +        fun fromString(value: String): Genres? {
넵!

2024-08-27 08:52 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +                    relevantCategories = translateGenres(entity.relevantCategories)
해당 부분 수정했습니다!

2024-08-27 16:32 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +            val activities = myActivityRepository.getMyActivities().take(5).map { entity ->
적용했습니다~

2024-08-27 16:38 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +    }
아핳 넵!

2024-08-27 17:47 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/adapter/MyActivityViewHolder.kt
> +        binding.executePendingBindings()
데이터 바인딩에서 데이터가 변경된 후 UI를 즉시 업데이트하도록 하는 메서드 입니다!

2024-08-27 17:51 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +            outputFormat.format(date!!)
?: 사용해볼게용!

2024-08-27 17:53 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/model/Genres.kt
> +            return Genres.values().find { it.name.equals(value, ignoreCase = true) }
수정하겠슴당

2024-08-27 22:29 UTC, m6z1 approved these changes

2024-08-28 05:46 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/adapter/MyActivityViewHolder.kt
> +        binding.executePendingBindings()
r: 해당 메서드는 UI스레드에서 강제로 UI를 즉각 업데이트 수행하도록합니다.
아이템 갯수가 많으면 많아질수록 수많은 bind 함수 내부에서 UI 스레드를 사용할것같아요!!
기능 구현에 문제가 없다면 제거해도 좋아보입니다!

2024-08-28 05:49 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeMyActivityRepository.kt
> +class MyActivityRepository @Inject constructor() {
아니면 UserRepository / UserNovelRepository 이런 식으로 쓰는데, UserFeedRepository는 어떤가욤?

2024-08-28 06:54 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/adapter/MyActivityViewHolder.kt
> +        binding.executePendingBindings()
알겠습니다!

2024-08-28 07:30 UTC, s9hn approved these changes
고생하셨씀다

2024-08-28 07:33 UTC, merged