feat: 내 활동 디테일 ui 구현
Team-WSS/WSS-Android pull request #226
Opened 2024-08-26 22:47 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #225 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 내 활동 디테일 리사이클러뷰
- 내 활동 <-> 내 활동 디테일 이동

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/805f63b9-1b06-475b-816d-06aa88c300b9

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
'내 활동'과 '내 활동 디테일'은 아이템을 불러오는 수의 차이 말고는 똑같은 뷰입니당..! 그래서 겹치는 코드가 많은데 어떻게 재사용하면 좋을까요?

2024-08-27 00:37 UTC, m6z1 reviewed
수고하셨어요 👍 
여기도 수정 후 노티주시면 어프루브하겠슴다

근데 컨플릭트 때문에라도 이전 PR의 내 활동 커밋이 이 브랜치에 반영되지 않게 하는 게 더 좋아 보이긴 해요!!

2024-08-27 00:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/adapter/MyActivityDetailAdapter.kt
> +    ListAdapter<ActivityModel, MyActivityDetailViewHolder>(diffCallback) {
a: 아직 클릭했을 때 피드 상세보기로 넘어가는 건 구현 안 하신 거죱 ??

2024-08-27 00:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityFragment.kt
> +            val intent = Intent(requireContext(), MyActivityDetailActivity::class.java)
c: 요 부분 정적 팩토리 메서드 패턴 적용해 주세요!

2024-08-27 00:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityViewModel.kt
> +class MyActivityViewModel @Inject constructor(private val myActivityRepository: MyActivityRepository) :
c: 생성자 개행하면 좋을 것 같아요!

2024-08-27 00:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/MyActivityDetailActivity.kt
> +        setUpObserve()
r: 
```suggestion
        setupObserver()
```

2024-08-27 00:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/MyActivityDetailActivity.kt
> +    private fun setupBackToMyActivityButton() {
c: 
```suggestion
    private fun onBackButtonClick() {
```
뭐 요런 식은 어떨지! 리스너에 대한 컨벤션에 맞춰서 ?

2024-08-27 05:21 UTC, s9hn requested changes

2024-08-27 05:21 UTC, s9hn commented on app/src/main/res/layout/item_my_activity.xml
> +                android:text='@{String.format(@string/my_activity_score_count, myActivity.novelRating != null ? myActivity.novelRating : 0.0f, myActivity.novelRatingCount != null ? myActivity.novelRa
r: 저희 xml에선 뷰로직 사용안하기로 했습니다! 클래스로 옮겨주세요!

2024-08-27 05:21 UTC, s9hn commented on app/src/main/res/layout/item_my_activity.xml
> +        <import type="android.view.View" />
c: 지금 View 를 사용하는 곳이 어딘가요?

2024-08-27 17:56 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/adapter/MyActivityDetailAdapter.kt
> +    ListAdapter<ActivityModel, MyActivityDetailViewHolder>(diffCallback) {
기능 구현에서 같이 할 예정입니다!

2024-08-27 17:57 UTC, yeonjeen commented on app/src/main/res/layout/item_my_activity.xml
> +        <import type="android.view.View" />
이거 삭제해야하는 부분입니다!!

2024-08-27 17:58 UTC, yeonjeen commented on app/src/main/res/layout/item_my_activity.xml
> +                android:text='@{String.format(@string/my_activity_score_count, myActivity.novelRating != null ? myActivity.novelRating : 0.0f, myActivity.novelRatingCount != null ? myActivity.novelRa
아핳 넵 수정하겠습니다!

2024-08-27 18:17 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myPage/myActivity/MyActivityFragment.kt
> +            val intent = Intent(requireContext(), MyActivityDetailActivity::class.java)
넵!! 적용하겠습니다!

2024-08-27 18:17 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/myActivityDetail/MyActivityDetailActivity.kt
> +    private fun setupBackToMyActivityButton() {
좋은 것 같아요! 수정하겠습니다!

2024-08-27 22:30 UTC, m6z1 approved these changes

2024-08-28 07:31 UTC, s9hn approved these changes
잘했씁다!

2024-08-28 08:59 UTC, merged