feat: 프로필 수정 API 연결
Team-WSS/WSS-Android pull request #230
Opened 2024-08-27 07:21 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #227

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 닉네임 검증 추가
- 프로필 수정 추가
- 바텀시트 대략적인 추가

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/user-attachments/assets/92b8177d-ec59-44c4-ae76-4e44ad587300

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
TODO: 프로필 이미지 수정 추가, 에러 핸들링 추가
아직 마이페이지쪽에서 완성된게 없어서 실시간 테스트는 어려울 것 같네요...! 이미지 관련도 답변좀 들어봐야할듯
너무 양이 많아져서 중간에 끊었다가 갑니다

2024-08-27 07:37 UTC, s9hn requested changes

2024-08-27 07:37 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/remote/response/UserNicknameValidityResponseDto.kt
> +    val isValid: Boolean
r: 트레일링콤마

2024-08-27 07:37 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
> +    suspend fun patchUserProfile(avatarId: Int?, nickname: String?, intro: String?, genrePreferences: List<String>) {
c: 패치요?

2024-08-27 07:37 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +                genrePreferences = arrayListOf("fantasy", "romance"),
c: 객체로 묶는게 이쁠 것 같아요. uimodel을 넘기시죠

2024-08-27 07:37 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +        val defaultState = uiState.nicknameEditResult != NicknameEditResult.VALID_NICKNAME && uiState.nicknameEditResult != NicknameEditResult.NONE
c: sealed 혹은 enum들은 가급적이면 다 임포트해주세요

2024-08-27 07:37 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiModel.kt
> +        fun String.checkNicknameValidity(): NicknameEditResult {
c: 이넘클래스의 역할에 대해 다시 생각해봐도 좋겠어요

2024-08-27 08:16 UTC, m6z1 reviewed
수고하셨습니다! 질문 남겨놓은 게 많아서 코멘트 확인 후에 어프루브 드리겠슴다 ( _ _ 👍

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
> +}
a: 요 부분은 저도 리뷰 받은 거긴 한데 request를 사용할 때 매퍼를 만들어야 하나? 라는 리뷰를 받았어서 엔티티 클래스 생성하지 않고 바로 requestDto로 넘겨줘도 될 듯 함다

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    }
a: activity 내에서 데이터 통신 데이터를 사용하지 않고, intent 객체에 데이터 값을 받아오는 이유가 무엇인가욥? 코드 봤을 때, 조회 api를 사용하면 뷰가 훨씬 가벼워질 것 같다는 생각이 드는데!

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    }
c: 버튼이 활성화되기 위한 로직을 뷰에서 사용해야 하나요? 뷰모델에서 `isEnabled` 의 상태를 가지는 건 어떨지?

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +        binding.tvProfileEditNicknameError.text = uiState.nicknameEditResult.message
c: 여기 binding 으로 한 번 묶으면 가독성이 훨씬 좋아질 것 같아요

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    private fun setupNicknameEditText() {
r: 리스너에 대한 코드니 메서드명이 달라야 할 것 같아요

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    private fun setupIntroductionEditText() {
r: 여기도 마찬가지

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +                    genrePreferences = currentProfile.genrePreferences.map { it.tag },
c: 이 로직 말고 다른 방법은 없는 건가욥??

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiModel.kt
> +                this.contains(Regex("^\\s|\\s$|[^\\w가-힣-_]|[ㄱ-ㅎㅏ-ㅣ]")) -> INVALID_NICKNAME_SPECIAL_CHARACTER
c: 검증 로직을 탈 때마다 정규식을 새롭게 생성하는 걸로 보이는데 성능 향상 고려하면 좋을 듯해유

2024-08-27 08:16 UTC, m6z1 commented on app/src/main/res/layout/dialog_profile_edit_character.xml
> +            android:text="프로필 선택"
c: 스트링 추출

2024-08-28 00:37 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
> +    suspend fun patchUserProfile(avatarId: Int?, nickname: String?, intro: String?, genrePreferences: List<String>) {
엥 save인데 뭐지

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
> +}
사실 저도 현재 크게 분리할 필요성을 느끼지 못한 부분이긴 함당

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/remote/response/UserNicknameValidityResponseDto.kt
> +    val isValid: Boolean
화긴

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +                genrePreferences = arrayListOf("fantasy", "romance"),
여기 관련 확장함수를 그냥 추가하는게 예쁠 것 같습니다 👍

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    }
확실히 뷰모델에서 가지는게 맞겠군요

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +        val defaultState = uiState.nicknameEditResult != NicknameEditResult.VALID_NICKNAME && uiState.nicknameEditResult != NicknameEditResult.NONE
오 훨씬 깔끔해지네요 소소팁 감사 👍

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    private fun setupNicknameEditText() {
on-what-action 이 맞을까여

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    }
이미 이전 뷰에서 무조건 가지고 있어야 할 정보를 위해 네트워크를 한번 더 찌르는게 성능이나 리소스 사용 면에서 좋지 못하다고 생각했습니다. 만약 가독성을 위해서라면 Serializable로 이번 수정에서 직렬화를 진행할 계획입니다 :)

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiModel.kt
> +        fun String.checkNicknameValidity(): NicknameEditResult {
값을 나열해주는 클래스에서 로직이 들어간다면 어색할 수 있겠네요 🤔 이친구는 다른 곳에 있어야 할 것 같습니다

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +                    genrePreferences = currentProfile.genrePreferences.map { it.tag },
비교하는 함수를 하나 분리하는 것 이외에 크게 달라질 것은 없을 것 같습니다...! 기존과 같은 경우 서버에서 null값을 요구해서요

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/model/ProfileEditUiModel.kt
> +                this.contains(Regex("^\\s|\\s$|[^\\w가-힣-_]|[ㄱ-ㅎㅏ-ㅣ]")) -> INVALID_NICKNAME_SPECIAL_CHARACTER
좋은 지적인듯요 Regex가 단순 문자열같은 느낌인줄

2024-08-28 01:39 UTC, junseo511 commented on app/src/main/res/layout/dialog_profile_edit_character.xml
> +            android:text="프로필 선택"
이거 일부러 냅뒀음요 새로 이슈파서 뜯어야할거같아서

2024-08-28 05:43 UTC, m6z1 approved these changes
굿이에영

2024-08-29 07:34 UTC, librarywon requested changes
고생하셨습니다! 리뷰확인해주세요!

2024-08-29 07:34 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/remote/response/UserNicknameValidityResponseDto.kt
> +
r: 공백

2024-08-29 07:34 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +                )
a: 서버 안찌르고 통으로 넘기나보네요 👍

2024-08-29 07:34 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +        ivProfileEditNicknameClear.isSelected = defaultState
c: 보기가 너무 어려운데 개행을 좀 해주시는 것은 어떤가요?

2024-08-29 07:34 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    private val hangulConsonantAndVowelRegex = Regex("[ㄱ-ㅎㅏ-ㅣ]")
c: viewModel에 닉네임 검증로직이 다 들어가 있으면 재사용이 불가능하기도 하고 viewModel에 이 로직이 있는게 맞을까 생각이 들기도합니다 그래서 저는 domain을 만들고 도메인 객체가 관련 로직을 처리하는 것을 만들었는데 참고해보실래요? 근데 저도 그거 뜯어고쳐야합니다.

2024-08-29 07:34 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    }
c: 양방향 데이터 바인딩으로 처리 가능해 보이는데 권장사항입니다!

2024-08-29 07:34 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    }
c: ??? 이걸 확장함수까지 만들어야하나요?

2024-08-29 07:34 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    }
r: 여기서만 사용하는 로직인데 String의 확장함수로 만들필요가 없을꺼 같습니다.

2024-08-29 08:25 UTC, s9hn approved these changes
고생하셨습니다.

2024-08-29 08:25 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/common/util/ExtentionFuction.kt
> +inline fun <reified T : Parcelable> Intent.getAdaptedParcelableExtra(key: String): T? {
a: inline과 reified에 대해 이해하고 계신가요?

2024-08-29 08:25 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +        val defaultState = uiState.nicknameEditResult != VALID_NICKNAME && uiState.nicknameEditResult != NONE
c: 모델로 빼도 되겠어요 :)

2024-08-29 08:25 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
>                      genrePreferences = currentProfile.genrePreferences.map { it.tag },
c: 이렇게 어렵게할 필요가 있나요? previousProfile.nickname이 현재 닉네임과 같으면 아래서버통신 로직이 시작되기전에 함수 return으로 끝내고, 그 이외의 경우엔 currentProfile.nickname만 보내주면 될 것 같습니다.

2024-08-29 08:25 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    fun updateCheckDuplicateNicknameBtnEnabled() {
c: Button

2024-08-29 15:41 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/remote/response/UserNicknameValidityResponseDto.kt
> +
아니 뭐지 닉값 지리네요

2024-08-29 15:42 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/myPage/MyPageFragment.kt
> +                )
불필요하게 이미 가지고 있는 정보를 위해 통신을 할 피료가 없다고 생각했습니당 🔥

2024-08-29 16:32 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    }
너무 지저분해지더라구요 그대로 검증 진행하니

2024-08-29 16:59 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    private val hangulConsonantAndVowelRegex = Regex("[ㄱ-ㅎㅏ-ㅣ]")
엄두가 잘 안나서 안하고 있었는데 저도 분리한번 해보겠습니다 확인해주시면 감사하겠슴다~~!!

2024-08-29 17:00 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditActivity.kt
> +    }
이건 잘 못해서 패스하겠습니다

2024-08-29 17:14 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
>                      genrePreferences = currentProfile.genrePreferences.map { it.tag },
기존과 다르게 '변경된 값'이 아니면 null을 보내야 한다는 서버의 요구사항이 있었슴다 ㅠ 그냥 유즈케이스로 빼는 것도 괜찮아보이네요

2024-08-30 03:10 UTC, librarywon approved these changes

2024-08-30 04:32 UTC, merged