feat: search view 구현
Team-WSS/WSS-Android pull request #24
Opened 2024-01-09 20:26 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #15 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
-  EditText 입력 상황에 따른 배경색 변경
 - 키보드 자동으로 올리기/내리기 구현
 - EditText 취소 버튼 구현
 - 검색 결과 리사이클러뷰 구현
 - 검색 결과 null 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/Team-WSS/WSS-Android/assets/144861180/36db7e0f-fc4c-4b8e-8710-9fcfac3fd70f

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
서버연결 후에 결과 화면은 처리 할 예정입니다.

2024-01-10 07:21 UTC, librarywon reviewed
수고했어요! 코드리뷰 확인 부탁드립니다!

2024-01-10 07:21 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/search/model/SearchResult.kt
> +    @DrawableRes val resultNovelImage: Int,
추후 image url로 변경할 소요가 있으니 다음에 작업할 때는 바로 url로 작업하는 방법이 좋을 것 같습니다.

2024-01-10 07:21 UTC, m6z1 requested changes
고생하셨슴다 리뷰 확인 부탁드려용

2024-01-10 07:21 UTC, m6z1 commented on app/src/main/res/layout/activity_search.xml
> +            app:layout_constraintEnd_toStartOf="@id/ivSearchCancel"/>
얘도 컬러값 지정해줘야 할 것 같습니다!

2024-01-10 07:21 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
> +    }
저는 보통 companion object를 클래스 내부 맨 하단에 두는 편인데 코틀린 코딩 컨벤션 한 번 읽어보시면 좋을 것 가타요
[코틀린 코딩 컨벤션](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-01-10 07:21 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchAdapter.kt
> +    }
setResultNovelList 메서드 같은 경우에는 RecyclerView Adatper의 필수 메서드의 맨 밑으로 내리는 게 어떨까용

2024-01-10 07:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +        val etSearch = binding.etSearch
이건 준서도 그렇게 하던데 가독성을 위해서 그런걸까요?

2024-01-10 07:23 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
깃 표시때문에 계속 띄어져있다고 생각했나봐요..;;; 수정하겠습니다!

2024-01-10 07:23 UTC, librarywon commented on app/src/main/res/drawable/bg_gray50_corner_12dp.xml
> +</shape>
어쩐지

2024-01-10 07:26 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +        val etSearch = binding.etSearch
그렇게 구현하는게 조금 더 코드의 가독성이 올라갈 것 같네용! 수정하겠습니다! 감사합니다!!

2024-01-10 07:33 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
> +    }
제가 알기로는 최상단 혹은 최하단에 두면 되는 것 같고, 
어디에 꼭 두어야 하는지는 컨벤션이 없는 것으로 알고 있습니다.

2024-01-10 07:36 UTC, yeonjeen commented on app/src/main/res/drawable/bg_gray50_corner_12dp.xml
> +</shape>
앗! 넵 수정하겠습니다!!

2024-01-10 07:40 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
> +    }
@librarywon 그렇다면 각자 코드에서는 통일해야 할 것 같은데 재원오빠 코드에서는 상단에도 있고 하단에도 있었어욥 확인해보심 좋을 듯 합니다~!

2024-01-10 07:45 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +        val etSearch = binding.etSearch
@librarywon 저같은 경우는 처음에 함수를 구현할 때 필요한 값들을 먼저 불러오고 코드를 생각하다보니 그렇게 구현하게 된 것 같습니다

2024-01-10 07:46 UTC, yeonjeen commented on app/src/main/res/layout/item_search_novel.xml
> +        android:layout_marginEnd="280dp"
넵! 수정했습니다! 감사합니당~

2024-01-10 07:47 UTC, yeonjeen commented on app/src/main/res/layout/item_search_novel.xml
> +        app:layout_constraintDimensionRatio="3:4"
아! 이건 수정하면서 안지웠네요;; 수정했습니다!

2024-01-10 07:51 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
> +    }
하단으로 통일하겠습니다~

2024-01-10 07:59 UTC, yeonjeen commented on app/src/main/res/drawable/bg_transparent_stroke_gray70_2dp_corner_12dp.xml
> +    <corners android:radius="12dp" />
수정했습니다!

2024-01-10 08:05 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +            }
궁금한 것이 있는데 사용자가 검색버튼을 누르고 이후에 다시 검색하기 위해서 edittext를 누르거나 cancel버튼을 눌렀을 때 다시 원래의 배경색으로 돌아오게 하기 위한 코드인데 그래도 여기서 처리하면 안되는 걸까요? 사용자가 다시 검색하기 위한 액션들이 결국 텍스트의 변화라고 생각했습니다.

2024-01-10 08:06 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/model/SearchResult.kt
> +    @DrawableRes val resultNovelImage: Int,
넵! 유념하겠습니다!

2024-01-10 08:09 UTC, yeonjeen commented on app/src/main/res/layout/activity_search.xml
> +        app:layout_constraintTop_toTopOf="@id/ivSearchBack" />
추가했습니다!

2024-01-10 08:11 UTC, yeonjeen commented on app/src/main/res/layout/activity_search.xml
> +            app:layout_constraintEnd_toStartOf="@id/ivSearchCancel"/>
넵 추가했습니다!

2024-01-10 08:11 UTC, yeonjeen commented on app/src/main/res/layout/item_search_novel.xml
> +        app:layout_constraintTop_toTopOf="@id/ivSearchNovel" />
추가했습니다~

2024-01-10 08:15 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +            }
아 그렇다면 이 기능을 유지하는 것이 좋을 것 같네요 좋습니다!

2024-01-10 08:22 UTC, yeonjeen commented on app/src/main/res/layout/activity_search.xml
> +        app:layout_constraintBottom_toBottomOf="parent">
디쟌쌤들께서 화면의 가운데라고 말씀해주셔서 margin값 지우고 top bottom 제약을 다시 주었습니다!

2024-01-10 08:23 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchAdapter.kt
> +    }
아하 넵! 그게 좋을 것 같습니당! 수정했습니다~

2024-01-10 08:33 UTC, m6z1 approved these changes

2024-01-10 15:01 UTC, s9hn approved these changes
LGTMMM

2024-01-10 15:01 UTC, s9hn commented on app/src/main/res/layout/activity_search.xml
> +        tools:listitem="@layout/item_search_novel"
린트체크 생활화합시다 !

2024-01-10 15:01 UTC, s9hn commented on app/src/main/res/layout/activity_search.xml
> +        tools:listitem="@layout/item_search_novel"
추가로 리사이클러뷰의 orientation 속성도 가급적이면 명시해줍시다 !

2024-01-10 15:26 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +        inputMethodManager.showSoftInput(binding.etSearch, 0)
키보드의 기본동작(올라오기)을 의미합니다.

2024-01-10 15:39 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +            override fun afterTextChanged(s: Editable?) {
text로 수정했습니다!

2024-01-10 15:55 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +    private fun deleteEditTextOnCancleBtn() {
한 함수에 너무 많은 기능을 담고 있다는 생각이 드네요. 배경색 변경, 취소버튼, 에디트텍스트 초기화를 나눠서 함수화 해보겠습니다.

2024-01-10 16:18 UTC, yeonjeen commented on app/src/main/res/layout/activity_search.xml
> +        tools:listitem="@layout/item_search_novel"
넵! 감사합니다!

2024-01-10 16:20 UTC, merged

2024-01-13 16:09 UTC, junseo511 reviewed
리뷰 늦어서 죄송합니당!!!! 완료했어요

2024-01-13 16:09 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
> +        with(binding) {
오 이번엔 with 잘 사용하셨군요 좋습니당

2024-01-13 16:09 UTC, junseo511 commented on app/src/main/res/layout/activity_search.xml
> +            android:background="@null"
transparent가 아닌 null로 사용하신 이유가 궁금합니다!!

2024-01-13 16:09 UTC, junseo511 commented on app/src/main/res/values/styles.xml
> +        <item name="cornerSize">10%</item> <!-- 원형을 위해 50%로 지정 -->
주석, 로그는 항상 제거해주는게 좋습니다!! by 세훈

2024-01-14 08:35 UTC, yeonjeen commented on app/src/main/AndroidManifest.xml
> +            android:windowSoftInputMode="stateAlwaysVisible"
이건 키보드를 자동으로 올라오게 하기 위해서 필요한 코드였습니다!

2024-01-14 08:35 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +    private fun showKeyboardOnEditTextFocus() {
에디트 텍스트를 눌러야'만' 올라오기 때문에 액티비티가 시작하자마자 자동으로 에디트텍스트에 포커스가 가고 키보드가 올라온 상태에서 액티비티가 시작되도록하기 위해서였습니다!

2024-01-14 08:36 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
> +            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {
아 여기까지 수정을 못햇네요!! 수정했습니다~ 감사합니다:)

2024-01-14 08:37 UTC, yeonjeen commented on app/src/main/res/layout/activity_search.xml
> +            android:background="@null"
2개에는 차이가 없다고 알고 있습니다!

2024-01-14 08:37 UTC, yeonjeen commented on app/src/main/res/values/styles.xml
> +        <item name="cornerSize">10%</item> <!-- 원형을 위해 50%로 지정 -->
오케 알겠습니다~