Feat/250
Team-WSS/WSS-Android pull request #255
Opened 2024-08-28 08:20 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #250

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 캐릭터 선택 다이알로그 추가

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

Uploading Screen_recording_20240828_171648.mp4…

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
확인차 피알 올려씀 아직 수정중,,,

2024-08-28 15:08 UTC, m6z1 approved these changes
굿이다요

2024-08-28 15:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/repository/AvatarRepository.kt
> +import com.teamwss.websoso.data.remote.api.UserApi
r: 불필요한 import문이 많은 것 같은데 정리 부탁드려요

2024-08-28 15:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +class AvatarChangeBottomSheetDialog : BaseBottomSheetDialog<DialogAvatarChangeBinding>(R.layout.dialog_avatar_change) {
c: @AndroidEntryPoint

2024-08-28 15:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +        binding.onSaveClick = ::onSaveClick
c: 얘네도 bindViewModel로 옮겨도 되지 않을까요?

2024-08-28 15:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +        val genrePreferences = profileEditUiState.value?.profile?.genrePreferences?.toMutableList() ?: mutableListOf()
a: toList()가 아니라 toMutableList()로 사용하신 이유가궁금해염

2024-08-28 15:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    fun fetchAvatars() {
r: 상태를 업데이트 하는 건 `updateXXX`

2024-08-29 05:14 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/repository/AvatarRepository.kt
> +import com.teamwss.websoso.data.remote.api.UserApi
엥 거의 쓰레기장이네요 😅

2024-08-29 05:15 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +class AvatarChangeBottomSheetDialog : BaseBottomSheetDialog<DialogAvatarChangeBinding>(R.layout.dialog_avatar_change) {
궁금한점 다이알로그로 activityviewmodels 쓰는데 붙여야하나요?? 기능 다 돌아가던데

2024-08-29 05:16 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +        val genrePreferences = profileEditUiState.value?.profile?.genrePreferences?.toMutableList() ?: mutableListOf()
add하고 remove 하기가 용이해서 mutableList로 했슴당

2024-08-29 07:57 UTC, librarywon requested changes
고생했습니다 리뷰 확인해주세요

2024-08-29 07:57 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +class AvatarChangeBottomSheetDialog : BaseBottomSheetDialog<DialogAvatarChangeBinding>(R.layout.dialog_avatar_change) {
다이얼로그에는 주입받고 뭐하는게 없는데 붙여야하나?

2024-08-29 07:57 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +            }
c: -> unit 해두시는건?

2024-08-29 07:57 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +            layoutManager = GridLayoutManager(context, profileEditViewModel.getFormattedSpanCount())
c: xml 코드만으로도 대응 가능해보이는데 어떻게 생각하시나요? 데바를 안쓰신다면 이렇게 하는게 맞구요

2024-08-29 07:59 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +class AvatarChangeBottomSheetDialog : BaseBottomSheetDialog<DialogAvatarChangeBinding>(R.layout.dialog_avatar_change) {
안 붙여도 돌아가면 그대로 고고

2024-08-29 08:44 UTC, s9hn requested changes
고생하셨습니다.

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    fun getSelectedAvatar(): AvatarModel {
r: 객체의 상태값을 public으로 열어두고 있어요. 굳이 커스텀 게터를 만들 필요는 없습니다.

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +            else -> {
c: else보단 좀 더 구체적인 상황을 제시해주세요

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +    private fun setupRecyclerView() {
r: uistate가 성공일때 매번 어댑터를 재할당해줘야할까요?

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +    private fun updateAvatarAnimation(lottieId: Int) {
a: 현재 avatarChangeUiState 객체 주소값이 바뀔때마다(에러든 로딩이든) 아바타가 업데이트되는데 의도하신 로직인가요?

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +                nicknameModel = profileEditUiState.value?.profile?.nicknameModel?.copy(
a: 위에 전체적으로 let을 활용하면 가독성이 많이 개선될 것 같아요

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +        val isCheckDuplicateNicknameBtnEnabled = nickname.isNotEmpty() && profileEditUiState.value?.nicknameEditResult == NONE
r: btn -> button

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +        val resourceId = R.raw::class.java.getField(resourceName).getInt(null)
c: 리플렉션은 런타임 성능을 감소시킵니다 :(

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +        Avatar.entries.forEach { avatar ->
c: 이정도 로직은 Avatar친구에게 위임해도 괜찮아보입니다

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeViewHolder.kt
> +        }
r: init에서 수행하도록 구현해보시죠

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeAdapter.kt
> +            holder.bind(currentAvatar)
c: 로직상 최초 한번만 불러주는 것 같은데, bind라는 함수이름이 적절할까요?

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeAdapter.kt
> +            holder.itemView.tag = currentAvatar.avatarId
r: 외부 객체가 상태값을 직접 변경하는 것이 좋은가요? 객체 간 메시지로 소통하고 상태 업데이트의 책임을 해당 객체에게 위임해주세요

2024-08-29 08:44 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeViewHolder.kt
> +        }
+ 단 한번만 호출되는 함수라면 상관없을 것 같습니다

2024-08-29 18:47 UTC, librarywon approved these changes

2024-08-29 18:48 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +            layoutManager = GridLayoutManager(context, profileEditViewModel.getFormattedSpanCount())
서버에서 오는 캐릭터 수에 따라 화면대응을 하기 위해 추가했습니다...!

2024-08-29 18:49 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/ProfileEditViewModel.kt
> +    fun getSelectedAvatar(): AvatarModel {
엥 그러게요 이거 왜 함수 분리해놨죠

2024-08-29 18:53 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +    private fun setupRecyclerView() {
저 리턴 넣어놨어용 ㅇㅂㅇ

2024-08-29 18:57 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/AvatarChangeBottomSheetDialog.kt
> +    private fun updateAvatarAnimation(lottieId: Int) {
같은 캐릭터를 누르더라도 다른 애니메이션이 재생되도록 하고 싶었습니다!!

2024-08-29 19:10 UTC, s9hn approved these changes
val approve by lazy { Approve.from(세훈) }

'approve'

2024-08-29 20:30 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeViewHolder.kt
> +        }
아니 처음에 뭔뜻인가 햇네 ㅋㅋㅋㅋ

2024-08-29 20:30 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeAdapter.kt
> +            holder.bind(currentAvatar)
setupItem으로 하겠습니다

2024-08-29 20:30 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/profileEdit/adapter/AvatarChangeAdapter.kt
> +            holder.itemView.tag = currentAvatar.avatarId
이것도 내부에서 할 수 있는건줄 몰랐음 ㅇㅂㅇ

2024-08-29 21:18 UTC, merged