feat: 스낵바 및 다이알로그 추가
Team-WSS/WSS-Android pull request #261
Opened 2024-08-29 05:09 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #168

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 작품평가 각종 검증 로직 보완했습니다
- 스낵바 및 다이알로그 추가했습니다
- 스낵바 이외에도 사용하는 경우가 많아 커스텀 토스트 추가했습니다

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/user-attachments/assets/4ff40dd9-0c49-47cf-a3fa-ff1c743f17ef

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
냠냠굿

2024-08-29 07:58 UTC, m6z1 approved these changes
굿 잘하셨겠죠b

2024-08-29 08:25 UTC, librarywon requested changes
고생하셨습니다 리뷰 확인해주세요!

2024-08-29 08:25 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/common/ui/custom/WebsosoCustomToast.kt
> +class WebsosoCustomToast(
a: ❤️

2024-08-29 08:25 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingViewModel.kt
> +                    isCharmPointExceed = charmPoints.size > 3,
r:  3 이거 상수로 빼두죠?

2024-08-29 08:25 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelRating/model/NovelRatingUiModel.kt
> +            isSearchKeywordExceed = newSelectedKeywords.size > 20 && isSelected,
r:  얘 두

2024-08-29 08:55 UTC, s9hn requested changes

2024-08-29 08:55 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelAlertDialogFragment.kt
> +        setCancelButtonText()
a: 이정도는 setupView 정도로 모아놔도 좋겠어요

2024-08-29 08:55 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelAlertDialogFragment.kt
> +            cancelButtonText: String,
c: 확장함수 만들어 놓으셨으니 모델로 넘기시죠

2024-08-29 08:55 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelAlertDialogFragment.kt
> +            onAcceptClick: () -> Unit,
r: 프래그먼트 알규먼트롤 람다를 넘길 수 없어서 전역 람다를 만드신 것 같네요.
함수형 인터페이스 타입을 넘기고 해당 프래그먼트를 호출하는 액티비티에서 인터페이스를 구현해주세요
FeedFragment에 비슷한 코드가 있을겁니다.

2024-08-29 08:55 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
> +                    novelRatingViewModel.updateCharmPoints(uiState.novelRatingModel.charmPoints.last())
c: 함수 하나로 분리하면 여러곳에서 재사용할 수 있겠어요

2024-08-29 08:55 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
> +    private fun setupBackPressCallback() {
a: 사용한 배경이 무엇인가요?

2024-08-30 04:44 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
> +    private fun setupBackPressCallback() {
뒤로가기를 눌렀을 때 나가지지 않고 경고창이 뜨도록 만들어야 해서 넣었습니다

2024-08-30 06:23 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelAlertDialogFragment.kt
> +            onAcceptClick: () -> Unit,
어차피 모델 들어가는거 같이 직렬화해서 넘기는게 더 깔끔할듯요?

2024-08-30 07:32 UTC, librarywon approved these changes
고생티비

2024-08-30 07:54 UTC, s9hn approved these changes

2024-08-30 07:54 UTC, merged