feat: 작품상세 뷰 피드 기능 구현
Team-WSS/WSS-Android pull request #266
Opened 2024-08-29 08:18 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #163

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 작품상세 뷰 피드 기능 구현
- 이미지 불러오는 방식 개선
- 스티키헤더 로딩 리사이클러뷰 대응

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
Uploading Screen_recording_20240829_171644.mp4…

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
거의 대부분의 부분을 산군 뷰 가져왔습니다
이미지 불러오는 방식이나 다른 엔티티랑 DTO 사용한 것 빼고는 크게 다를 것 없을겁니다

2024-08-29 08:41 UTC, m6z1 approved these changes
굿입니다~

2024-08-29 08:41 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
> +    }
c: 이 뷰에도 refresh 가 있나요 ?

2024-08-29 08:41 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
> +    private fun observeUiState() {
r: `setupObserver` 산군 코드 복붙하셨구만

2024-08-29 08:41 UTC, m6z1 commented on app/src/main/res/layout/fragment_novel_feed.xml
> +                android:layout_height="1200dp"
c: 1200dp 지정해주는 게 의도된 건가염 ??

2024-08-29 09:17 UTC, s9hn requested changes

2024-08-29 09:17 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
> +
r: 피드 상세보기 뷰 갔다가 돌아왔을 때 피드 새로고침되는 기능도 있어야해요 지금 제 열린 피알에는 있는디

2024-08-30 06:43 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
> +    }
그건 기획하고 이야기해봐야할듯?

2024-08-30 06:45 UTC, junseo511 commented on app/src/main/res/layout/fragment_novel_feed.xml
> +                android:layout_height="1200dp"
어차피 뷰에서 재조정돼서 임의로 적은거긴 합니다 0dp로 바꿔야게씀

2024-08-30 06:48 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelFeed/NovelFeedFragment.kt
> +
해죠요 🤣

2024-08-30 07:54 UTC, s9hn approved these changes

2024-08-30 08:05 UTC, merged