feat: NovelDetail 뷰 및 MemoWrite 뷰 구현
Team-WSS/WSS-Android pull request #27
Opened 2024-01-13 15:59 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #12 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 작품 메모 및 정보 뷰 구현
- 메모 작성 및 작품 메모 ~ 작성 뷰 까지의 모든 다이얼로그 뷰 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/Team-WSS/WSS-Android/assets/114990782/57d03133-5224-489d-a42b-ccb3c48e51d8

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
- 분기 처리는 서버 붙이면서 진행할 예정입니다.
- 이미지 radius 둥글게 진행하는 바인딩 어댑터도 서버 연결하면서 수정하겠습니다.
  ㄴ 이 PR에 `shape.xml` 파일 제거하겠습니다. (다음 PR에 제거한다는 뜻)
- 중간에 한 번 끊고 진행했어야 하는데 욕심이 계속 생겨서 커밋이 너무 많아졌네요 죄송합니다.
- 서버 하나 붙이고 바로바로 PR 날리도록 하겠습니다.
- 낼 봐요 >0<

2024-01-14 06:54 UTC, yeonjeen approved these changes
수고하셨어용~:) 짱짱 개발자 손명지

2024-01-14 06:54 UTC, yeonjeen commented on app/src/main/res/layout/activity_memo_write.xml
> +
텍스트나 툴 둘 중에 하나는 삭제하시면 될 것 같아요~

2024-01-14 06:54 UTC, yeonjeen commented on app/src/main/res/layout/activity_memo_write.xml
> +        tools:text="이보라" />
여기두용!

2024-01-14 06:54 UTC, yeonjeen commented on app/src/main/res/layout/activity_memo_write.xml
> +
여기두용!

2024-01-14 06:54 UTC, yeonjeen commented on app/src/main/res/layout/activity_novel_detail.xml
> +            app:layout_constraintEnd_toEndOf="parent"
여기 이미지뷰는 서버에서 보내주는 이미지인가용?

2024-01-14 06:54 UTC, yeonjeen commented on app/src/main/res/layout/dialog_memo_delete.xml
> +        android:layout_height="40dp"
제약은 거는게 아니라 이렇게 직접 값을 넣으신 이유가 있을까용?

2024-01-14 06:54 UTC, yeonjeen commented on app/src/main/res/layout/fragment_novel_memo.xml
> +            android:text="새로운 메모를 작성해보세요"
스트링으로 들어가면 좋을 것 같습니다~

2024-01-14 06:54 UTC, yeonjeen commented on app/src/main/res/layout/item_custom_popup_drop_down.xml
> +    tools:text="작품을 서재에서 삭제"
이 텍스트는 필요 없는 텍스트인가용??

2024-01-14 07:08 UTC, junseo511 approved these changes
굉장히 많은 xml을 그리셨군요 고생 많으셨습니당

2024-01-14 07:08 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/DialogNovelDelete.kt
> +            clickNovelDelete()
이친구는 어디서 사용하신건가요?!

2024-01-14 07:08 UTC, junseo511 commented on app/src/main/res/drawable/img.jpg
이제 fix PR이 머지되면 어댑터를 쓰셔도 될듯합니당 🤭

2024-01-14 07:08 UTC, junseo511 commented on app/src/main/res/layout/activity_memo_write.xml
> +    <com.google.android.material.imageview.ShapeableImageView
추후 기본 이미지뷰로 변경하셔도 됩니당 참고만 해두세요~~!!!!

2024-01-14 07:08 UTC, junseo511 commented on app/src/main/res/layout/activity_memo_write.xml
> +        tools:text="dddddddffffff" />
혹시 코딩하다가 화가 나셨나요

2024-01-14 07:08 UTC, junseo511 commented on app/src/main/res/layout/activity_memo_write.xml
> +        tools:text="dddddddffffff" />
아니면 롤이 하고싶으신건가

2024-01-14 07:08 UTC, junseo511 commented on app/src/main/res/layout/activity_memo_write.xml
> +            tools:text="가을이 지나가는 하늘에는 가을로 가득차 있습니다. 나는 아무 걱정도 없이 가을 속의 별들을 다 헬 듯합니다. 가슴 속에 하나 둘 새겨지는 별을 이제 다 못 헤는 것은 쉬이 아침이 오는 까닭이요, 내일 밤이 남은 까닭이요, 아직 나의 청춘이 다하지 않은 까닭입니다. 별 하나에 추억과 별하나의 사랑과 별 하나에 쓸쓸
다들 별헤는밤 너무 좋아하시네 ㅋㅋㅋㅋㅋㅋ

2024-01-14 07:08 UTC, junseo511 commented on app/src/main/res/layout/activity_novel_detail.xml
> +        <!-- 추가될 예정 -->
굿굿

2024-01-14 07:08 UTC, junseo511 commented on app/src/main/res/layout/activity_novel_detail.xml
> +                    app:layout_scrollFlags="scroll|exitUntilCollapsed">
이친구 자연스럽게 성공하셨나요? 하셨다면 공유좀 긁적

2024-01-14 07:09 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/memoWrite/DialogMemoDelete.kt
> +        dialog?.window?.requestFeature(Window.FEATURE_NO_TITLE)
이 코드는 뷰가 생성되기 전에 있어야 하는 코드라 그냥 쳤는데 오히려 좋아 ?

2024-01-14 07:13 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        const val POPUP_WIDTH = 196
PopupWindow 메서드의 width 값 타입 자체가 int 값이라서 그렇습니다!

2024-01-14 07:16 UTC, m6z1 commented on app/src/main/res/layout/activity_novel_detail.xml
> +            app:layout_constraintEnd_toEndOf="parent"
넵 그렇습니다 이미지들은 서버 붙일 때 바로 연결시키려구용

2024-01-14 07:17 UTC, m6z1 commented on app/src/main/res/layout/dialog_memo_delete.xml
> +        android:layout_height="40dp"
넵 다이얼로그 width 랑 height값은 모든 다이얼로그의 값이 같아서 고정 값으로 넣었습니다

2024-01-14 07:19 UTC, m6z1 commented on app/src/main/res/layout/item_custom_popup_drop_down.xml
> +    tools:text="작품을 서재에서 삭제"
액티비티 자체에서 텍스트값을 지정해주고 있기도 하고, 재사용 되는 텍스트라 따로 텍스트값을 기입하지 않았습니다!

2024-01-14 07:24 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/remote/response/NovelMemoInfoResponse.kt
> +    val userNovelRating: Double,
굿굿 감사합니다

2024-01-14 07:28 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
> +        dialog.show((supportFragmentManager), "CancelEditMemoDialog")
굿  !

2024-01-14 07:29 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        isUserInteraction = true
여기서는 사용되고 있는 부분이고, private으로 선언되어 있습니다

2024-01-14 07:33 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +    }
따로 쓰면 될 듯!!!!

2024-01-14 07:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/memoWrite/DialogMemoCancel.kt
> +        clickKeepWriteBtn()
함수 네이밍 컨벤션이 있는 줄 몰랐는데 짚어주셔서 감사해요 >.,< 네이밍 바로 수정 드갑니다요

2024-01-14 07:59 UTC, m6z1 commented on app/src/main/res/layout/activity_memo_write.xml
> +        tools:text="dddddddffffff" />
ㅋㅋㅋㅋㅋㅋㅋ 롤이 하고 싶었을 수도 🤔

2024-01-14 08:00 UTC, m6z1 commented on app/src/main/res/layout/activity_novel_detail.xml
> +                    app:layout_scrollFlags="scroll|exitUntilCollapsed">
세훈오빠의 도움을 빌려서 맛꿀마로 성공했지예 ㅋ.ㅋ

2024-01-14 08:31 UTC, librarywon requested changes
정말 수고하였습니다! 리뷰 반영해주세요!

2024-01-14 08:31 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        }
이 `addOnOffsetChangedListener`는 어떤 역할을 하는 친구인가요?

2024-01-14 08:31 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        }
`MemoWriteActivity`의 인텐트를 `NovelDetailActivity`가 만들어야할까요? 제가 공부했어요에도 적고 안드 꿀팁에도 적은 내용을 확인하시면 좋을 것 같습니다.

2024-01-14 08:31 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +    }
감사합니다 잘 쓰겠습니다

2024-01-14 08:31 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelMemoViewHolder.kt
> +    }
서버 NovelMemoResponse에 현재 코드가 의존적인데 model을 생성하고 mapper를 적용하는건 어떻게 생각하시는지

2024-01-14 08:31 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelMemoFragment.kt
> +        startActivity(intent)
이것도 동일합니다!

2024-01-14 08:31 UTC, librarywon commented on app/src/main/res/layout/activity_memo_write.xml
> +        android:focusable="true"
이 두 속성은 어떤 역할을 하나요?

2024-01-14 08:43 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/DialogNovelDelete.kt
> +            clickNovelDelete()
얘는 지금 람다로 넘겨서 액티비티에서 로직을 구현했을 거예욥

2024-01-14 09:04 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +            this
NovelDetailViewPagerAdapter는 뷰 페이저 내에서 프래그먼트들을 표시하고 관리합니다.  또한, FragmentActivity의 context를 사용해서, 프래그먼트의 생명주기를 해당 액티비티와 동기화하여 안정적으로 관리할 수 있어 context를 생성자로 받고 있습니다

2024-01-14 09:12 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        }
얘는 스크롤의 변화를 감지하는 메서드입니다.

2024-01-14 09:20 UTC, m6z1 commented on app/src/main/res/layout/activity_memo_write.xml
> +        android:focusable="true"
`android:clickable="true"`은 해당 뷰를 클릭할 수 있도록 해주고,
`android:focusable="true"`는 사용자가 화면에서 탭을 통해 뷰 사이를 이동하게 할 수 있고 말그대로 포커스를 받을 수 있는 역할입니다

2024-01-14 09:20 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelMemoViewHolder.kt
> +    }
반영해보겠습니다

2024-01-14 19:18 UTC, librarywon approved these changes
세훈 코드리뷰 끝나면 노티 주시고 머지하시면 좋을 것 같습니다.

2024-01-14 19:34 UTC, s9hn approved these changes
에휴 잘한다잘해 어휴

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/memoWrite/DialogMemoCancel.kt
> +    private fun onClickExitBtn() {
> 5. 줄여 쓰지 않는다(축약 금지)

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
> +        val dialog = DialogMemoCancel(clickExit = {
```
 private val dialogMemoCancel: DialogMemoCancel by lazy {
        DialogMemoCancel(::finish)
    }

...

dialogMemoCancel.show()
```

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
> +        dialog.show((supportFragmentManager), "CancelEditMemoDialog")
소괄호는 빼도 될듯요?

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
> +        fun createIntent(context: Context): Intent {
이것도 팀원들끼리 한번 맞추면 좋을듯

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +            this
오.. 이거 정보의 출처가 어디인가요 ?

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        val tabTitleList = listOf(getText(R.string.novel_detail_memo), getText(R.string.novel_detail_info))
no List !

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        binding.vpNovelDetail.adapter = NovelDetailViewPagerAdapter(this)
데에에ㅔㅔㅔㅔㅔㅔ엠;;

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        binding.vpNovelDetail.registerOnPageChangeCallback(object :
함수분리 삽가능

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +            fragment.view?.post { fragment.view?.requestLayout() }
오호 이게 그때 우리 얘기한 그 코드인가?

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        isUserInteraction = true
어디서 사용하는 프로퍼티인가요 .. ? 분기문이 존재하진 않는 것 같은데

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailViewPagerAdapter.kt
> +    FragmentStateAdapter(fragmentActivity) {
왜 FragmentStateAdapter 쓰셨나욧

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelMemoFragment.kt
> +    private lateinit var rvNovelMemoAdapter: NovelDetailMemoAdapter
rv..?

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelMemoFragment.kt
> +    private fun initRecyclerView() {
함수이름과 조금..

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelMemoFragment.kt
> +        rvNovelMemoAdapter = NovelDetailMemoAdapter()
차라리 by lazy..

2024-01-14 19:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelInfoFragment.kt
> +        view?.requestLayout()
뷰에서 reloadFragmentView 이거해줘도 requestLayout()해줘야 하나요?

2024-01-14 19:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
> +        val dialog = DialogMemoCancel(clickExit = {
대에에엠

2024-01-14 20:00 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        binding.vpNovelDetail.adapter = NovelDetailViewPagerAdapter(this)
뭐가 '?... 잘못된 것임 ? ..

2024-01-14 20:01 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +            fragment.view?.post { fragment.view?.requestLayout() }
마즘

2024-01-14 20:04 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        binding.vpNovelDetail.adapter = NovelDetailViewPagerAdapter(this)
해결완료 ㅎㅎ

2024-01-14 20:19 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        isUserInteraction = true
ㅎ ; 분기문을 삭제했나봐요 제거하겠습니다. 감사해염 다들

2024-01-14 20:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/adapter/NovelDetailViewPagerAdapter.kt
> +    FragmentStateAdapter(fragmentActivity) {
viewPager 에서 각 페이지를 fragment로 구성하고 있어서fragmentstateadapter를 사용했습니닷

2024-01-14 20:50 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelMemoFragment.kt
> +    private lateinit var rvNovelMemoAdapter: NovelDetailMemoAdapter
수정햇ㅅ브니다

2024-01-14 20:52 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelMemoFragment.kt
> +    private fun initRecyclerView() {
함수 삭제햇어요 =,,=

2024-01-14 21:08 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/fragment/NovelInfoFragment.kt
> +        view?.requestLayout()
코리 달리고 확인해봤는데 이 부분이 어떻게 동작하는 지 확실하게 공부해봐야 할 것 같아요. onResume에서 requestLayout()을 호출하지 않았을 경우에 novelMemoFragment에서 뷰의 height novelInfoFragment의 height값 만큼 길어져서 툴바 뒤로 컨텐츠가 뒤로 숨는 ^^.. 요상한 경우가 생기네요. 반대로 onResume()에서 requestLayout()을 호출했을 땐 문제가 없는데 뭐가 다른 걸지 , , , 일단은 뷰 단의 reloadFragmentView는 삭제하고 onResume()에만 남기겠습니다. 공부하고 꼭 공유해드릴게요~.~

2024-01-15 06:22 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +            this
대답한 거 출처 - 지피티는 좀 그렇긴한데, 해당 방식은 공식문서에 있는 방법이네요. 이렇게말해줬으면 더 공신력 있었을 듯?
잘배워갑니다

2024-01-15 14:11 UTC, merged