feat: 다른 유저 활동 ui 구현
Team-WSS/WSS-Android pull request #276
Opened 2024-08-29 19:33 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #275 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 다른 유저 활동 리사이클러뷰 구현
- 유저 활동 디테일 액티비티로 이동
- 이동한 곳에 따른 활동 디테일 타이틀 분기처리

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/ad9e1551-7ebe-40d5-ba4e-81dd5dc9333b

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-08-30 04:36 UTC, m6z1 approved these changes
LGTM!!

2024-08-30 04:36 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        val source = intent.getStringExtra("source")
c: 요런 키값은 상수로 관리하면 좋을 것 같아용

2024-08-30 04:36 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private fun setUpObserve() {
r: setupObserver()

2024-08-30 04:36 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        fun createIntentForMyActivityDetail(context: Context): Intent {
r: 
```suggestion
        fun getIntent(context: Context): Intent {
```

2024-08-30 04:36 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +        return ActivityDetailViewHolder(binding)
r: 뷰홀더에 팩토리메서드 만들어둔 걸 사용하면 되지 않을까욥 ?

2024-08-30 04:36 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
> +        setUpObserve()
r: setupObserver()

2024-08-30 04:36 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
> +    private fun navigateToMyActivityDetail() {
c: 클릭리스너를 클릭했을 때 넘어가는 거니까,,, onXXXButtonClick()이 맞지 않을까요? (중요하지 않음)

2024-08-30 04:36 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityAdapter.kt
> +    }
r: 얘네도 팩토리 메서드 만들어둔 거 사용하면 좋을 것 같아요

2024-08-30 05:47 UTC, librarywon requested changes
고생하셨습니다 리뷰확인해주세요!

2024-08-30 05:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            "otherUserActivity" -> getString(R.string.other_user_page_activity)
c: 이런 상수는 보내주는 쪽에서 가지고 있고 참조하는 형태로 쓰면 좋겠네요

2024-08-30 05:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            else -> ""
c: else는 최대한 지양하도록 해볼까요?

2024-08-30 05:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +                activities.toUi().take(5)
c: 이 숫자 5는 뭐죠?

2024-08-30 05:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
> +    private fun navigateToMyActivityDetail() {
맞긴습니다 setOnClickListener 안에 내용이 이동함수 이름입니다

2024-08-30 05:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityAdapter.kt
> +        holder.bind(activity)
r: 한줄로 적어주면 좋을 것 같아요

2024-08-30 05:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityViewHolder.kt
> +        binding.myActivity = myActivity
c: 뷰홀더 Bind에 뷰모델을 직접 넘기는 형태는 좋지 않다고 생각합니다. 다른 사람들 코드 참고해보시면 리뷰를 받고 대부분 고친형태여서요

2024-09-05 14:58 UTC, s9hn approved these changes

2024-09-16 19:07 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +        return ActivityDetailViewHolder(binding)
오.. 제 파일에는 이렇게 되어있는데 푸쉬가 안된 부분이 있었나봐용...!

2024-09-16 19:12 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityAdapter.kt
> +    }
수정했습니다!1

2024-09-16 19:38 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            else -> ""
수정했씁니다!1

2024-09-16 19:38 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            "otherUserActivity" -> getString(R.string.other_user_page_activity)
넵! 수정하겠습니당!

2024-09-16 19:38 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +                activities.toUi().take(5)
마이 혹은 다른유저 페이지에 있는 '활동'은 피드를 최신 5개만 보여주기로해서요!

2024-09-16 19:53 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityViewHolder.kt
> +        binding.myActivity = myActivity
확인해보고 수정하겠습니다!

2024-09-16 20:16 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityViewHolder.kt
> +        binding.myActivity = myActivity
제가 home 부분 뷰홀더를 확인을 해봤는데 ui에 있는 model이 아니라 data에 있는 Entity를 넘기고 계시던데 혹시 그 부분 수정을 말씀하시는 걸까요?

2024-09-17 13:40 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +                activities.toUi().take(5)
이건 그러면 상수화하면 좋을 것 같아요

2024-09-17 13:42 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityViewHolder.kt
> +        binding.myActivity = myActivity
이게 왜 이런 코드리뷰가 갔는지 모르겠는데 뷰모델을 넘기는줄 알았던거 같네요 😭

2024-09-17 13:43 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            "otherUserActivity" -> getString(R.string.other_user_page_activity)
이거 리뷰 반영이 되었을까요?

2024-09-17 13:45 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
>          holder.bind(activity)
r: 한줄로 바꿔볼까요
```suggestion
        holder.bind(getItem(position))
```

2024-09-17 14:27 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
>          holder.bind(activity)
반영했습니다!

2024-09-17 14:29 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +                activities.toUi().take(5)
네넵

2024-09-17 14:57 UTC, librarywon approved these changes
정말 수고하셨습니다 마지막으로 하나만 더 반영해주세요!

2024-09-17 14:57 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            "" -> title = ""
c: "" 처리는 불필요한 것 같네요 `source`, `title` 자료형 명시도 부탁드립니다.

2024-09-17 15:09 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            "" -> title = ""
한가지 질문이 있는데욤! title 같은 경우는 빈문자열로 초기화되고 있는데 이 경우에도 자료형을 명시적으로 작성하는 것이 좋은지 궁금합니당!

2024-09-17 15:22 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            "" -> title = ""
저는 명시해주는 것이 읽는 사람을 배려하는 것이라고 생각해서 작성해주는 것이 좋다고 생각합니다.

2024-09-17 15:23 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            "" -> title = ""
아하 넵! 감사합니당:)

2024-09-17 15:34 UTC, merged