feat: my pgae view 구현
Team-WSS/WSS-Android pull request #29
Opened 2024-01-13 16:25 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #14 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 마이페이지 xml
- 닉네임변경 xml
- 계정정보 xml
- 아바타 바텀시트
- 닉네임 변경 조건 기능 구현
- 마이페이지 리사이클러뷰 

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/Team-WSS/WSS-Android/assets/144861180/ddc85afa-bbe5-4c2c-8ccd-f2eeb0941dcc

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
닉네임 변경 부분 코리 기다리면서 슬금슬금 뷰모델 만들어보겠습니다. 그리고 대표캐릭터와 바텀시트에 있는 캐릭터들은 모션이 들어가는 캐릭어라 제가 들고있을 예정입니다. 그리고 이슈에서 말씀드렸다시피 캐릭터 선택 부분은 확정뷰가 아니라서 일단은 가로 리사이클러뷰로 만들었습니다.

2024-01-14 00:55 UTC, m6z1 approved these changes
고생 많으셨어요!! >0<

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    internal var onItemClickListener: ((Avatar) -> Unit)? = null
`internal var` 은 어떨 때 사용하는 것인가요 ?

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    }
람다 사용 좋네요 ....

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    }
함수 순서를 변경하면 어떨까요 ? onItemClickListener 도 마찬가지로 !

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +        viewModel = ViewModelProvider(this).get(MyPageViewModel::class.java)
ViewModelProvider는 어떤 것인가용 ?

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +    @SuppressLint("StringFormatMatches")
이 애노테이션은 어떤 것이가요 ?

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +    }
코드가 위에서 아래로 읽히도록 함수 순서를 변경하면 좋을 것 같습니다!

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
> +            crossfade(true)
이건 어떤 메서드인가용 ?

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
> +        _userName.value = "김명진"
ㅋㅋㅋㅋㅋㅋㅋ

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +        etChangeName.addTextChangedListener(
```suggestion
        binding.etChangeName.addTextChangedListener(
```
로 사용하면 어떨까요 ?

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +                10
10 은 어떤 숫자인가용 ?

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +                10
10은 어떤 숫자인가용 ?

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +        editText.background.setTint(ContextCompat.getColor(this, backgroundColor))
굿 ...

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +        editText.text = Editable.Factory.getInstance().newEditable(defaultName)
이 코드는 intent에서 받아온 값을 edittext에 넣어놓는 코드인가요 ?? 신기방기하네요

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/res/drawable/bg_gray100_radius_999dp.xml
> +    <corners android:radius="999dp"/>
999dp는 어디에 사용되나요 ??

2024-01-14 00:55 UTC, m6z1 commented on app/src/main/res/layout/activity_check_user_info.xml
> +        tool:text="김명진"/>
많이 언급되는 울 TL

2024-01-14 07:19 UTC, junseo511 approved these changes
고생하셨습니다~~~!!!!!

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
> +    }
혹시 companion object로 따로 선언하신 이유가 있으신가요?

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    fun setOnItemClickListener(listener: (Avatar) -> Unit) {
이친구도 PRND 컨벤션이 있다네용 오늘자 띵지 PR에 달린 코드리뷰를 참고해주세용

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +        viewModel = ViewModelProvider(this).get(MyPageViewModel::class.java)
이친구를 쓰신 목적이 있으신가요?

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +    }
추후 바인딩어댑터를 쓰셔도 좋을듯합니다!!

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            intent.putExtra("userName", userNameWithoutSuffix)
위에서 불러온 유저네임을 사용하지 않고 새로 선언하신 이유가 있으신가요?

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            }
따로 try catch를 사용하신 이유는 무엇인가요?

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +                Log.e("error", "이동실패", e)
불필요한 로그는 지워주세용!!

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
> +        }
함수 분리하셔도 괜찮을듯합니다

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +    ): TextWatcher {
뭐가 들어간게 굉장히 많군요 신기하네요 ㄷㄷ

2024-01-14 07:19 UTC, junseo511 commented on app/src/main/res/layout/activity_check_user_info.xml
> +        tool:text="김명진"/>
이쯤되면 티엘바라기...

2024-01-14 07:39 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    internal var onItemClickListener: ((Avatar) -> Unit)? = null
해당 변수들이 같은 모듈내 외부 클래스에서 사용되는 경우 이렇게 선언을 한다고 하더라고요! 저는 두 변수가 어댑터뿐만 아니라 프레그먼트 내에서도 사용이 될 예정이라 이렇게 선언을 했습니다! 혹시 다른 방법이나 잘못된 부분이 있다면 말씀 부탁드려용:)

2024-01-14 07:45 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +        viewModel = ViewModelProvider(this).get(MyPageViewModel::class.java)
ViewModelProvider는 뷰모델을 생성하는 클래스입니다!

2024-01-14 08:02 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    internal var onItemClickListener: ((Avatar) -> Unit)? = null
이야 ~~~ 폼 미쳤다이

2024-01-14 08:08 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
> +            crossfade(true)
음 일단은 crossfade가 주로 이미지 교체 시 애니메이션을 부드럽게 보이게 해주는 메서드라고해서 사용해보았습니다! 마이페이지에 있는 이미지뷰들이 기본적으로 '전환'을 할 예정이라 이 메서드가 적절할 것이라고 판단했어요!! 혹시 다른 의견있으시면 부탁드립니다~

2024-01-14 08:12 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +                10
닉네임 변경 시 최대 글자 수 입니다! maxLength입니다~

2024-01-14 08:13 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +        editText.text = Editable.Factory.getInstance().newEditable(defaultName)
맞아요! 닉네임 변경 시 edittext에 기존 닉네임이 입력된 상태로 시작을 해야해서 이런 코드가 나오게 되었습니당:)

2024-01-14 08:15 UTC, yeonjeen commented on app/src/main/res/drawable/bg_gray100_radius_999dp.xml
> +    <corners android:radius="999dp"/>
아바타 바텀시트에서 장르이미지와 태그 배경이 되는 타원 라운드에 적용되기 위해 999dp가 탄생했습니다 ㅎㅎㅎ

2024-01-14 08:16 UTC, yeonjeen commented on app/src/main/res/layout/activity_check_user_info.xml
> +        tool:text="김명진"/>
사랑한다 김명진

2024-01-14 09:23 UTC, KwakEuiJin reviewed
코끼리조원 연진누나의 요청으로 코드 리뷰를 남깁니다 ㅎㅎ
리뷰를 달면서 느꼇지만 안드로이드 개발자로서 정말 많이 발전한 부분이 보이네요!! 
앱잼 성공적으로 잘 마무리 하시길 바라겠습니당 화이팅

2024-01-14 09:23 UTC, KwakEuiJin commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
> +    }
아마 View는 Nullable하지 않을 것 같네요!

2024-01-14 09:23 UTC, KwakEuiJin commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
> +    }
굳 Instance를 함수로 반환받는 것은 좋은 구조! 다만 avatar 를 받았다면 argument로 던진다던가 추가적인 액션이 없는 것 같네요

2024-01-14 09:23 UTC, KwakEuiJin commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    internal var avatarItems: List<Avatar> = emptyList()
ListAdapter를 통해 조금 더 간결한 구조를 가져가보아도 괜찮을 것 같습니당

2024-01-14 09:23 UTC, KwakEuiJin commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    }
오 이건 어떤 방법인가요? 처음 보는 ViewHolder 생성 방법이네요

2024-01-14 09:23 UTC, KwakEuiJin commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +        }
제 꿀팁공유에서 RecyclerView ItemOnclickListener 을 효율적으로 선언하는 부분을 확인해보아도 좋을 것 같습니다.

2024-01-14 09:23 UTC, KwakEuiJin commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +        viewModel = ViewModelProvider(this).get(MyPageViewModel::class.java)
@yeonjeen by viewModels 를 쓰지 않으신 이유가 있나요?

2024-01-14 09:23 UTC, KwakEuiJin commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            val displayText = getString(R.string.my_page_user_name, userName)
viewLifecycleOwner 를 쓰신 부분 너무 인상깊네요 좋습니다!

2024-01-14 09:23 UTC, KwakEuiJin commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            val defaultName = binding.tvMyPageUserName.text.toString()
orEmpty라는 함수도 있으니 참고~!!

2024-01-14 09:26 UTC, librarywon requested changes
리뷰 확인 부탁드립니다.

2024-01-14 09:26 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    internal var onItemClickListener: ((Avatar) -> Unit)? = null
동일 모듈에서만 사용을 의도 하셨다면 문제가 없어보이는데 internal 을 사용하는 adapter를 개인적으로 본 적이 없어서 남겨봅니다

2024-01-14 09:26 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +        viewModel = ViewModelProvider(this).get(MyPageViewModel::class.java)
by viewModels() 를 사용하지 않은 이유가 뭔가요?

2024-01-14 09:26 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            val intent = Intent(binding.root.context, ChangeNameActivity::class.java)
저번에도 말했었던 `ChangeNameActivity`의 Intent를 현재 프레그먼트가 만들어야할까요?

2024-01-14 09:26 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +    }
양방향 데이터 바인딩에 대해서 확인해보시면 불필요한 코드가 확실히 줄어들 것 같습니다.

2024-01-14 09:26 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/checkUserInfo/CheckUserInfoActivity.kt
> +    }
함수 이름이 여러 단어가 혼재 된 것 같습니다. 더 명확한 이름이 필요해보이네요!

2024-01-14 12:50 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +    }
해당사항 알아보고 수정하겠습니다.

2024-01-14 12:50 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/checkUserInfo/CheckUserInfoActivity.kt
> +    }
함수 이름이 조금 더 해당 구현 내용에 대해서 명시할 수 있도록 수정해보겠습니다!

2024-01-14 14:35 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    }
아 이건 제가 이런저런 시도를 하다가 수정하지 않은 부분인데 이건 권장하지 않는 방법이라고 알고 있습니다. 뷰홀더를 만들때마다 새로운 어댑터를 생성하는 문제가 있습니다. 이 부분은 수정하도록 하겠습니다!

2024-01-14 14:45 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    internal var avatarItems: List<Avatar> = emptyList()
넵! 수정해보겠습니다~

2024-01-14 15:50 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            val intent = Intent(binding.root.context, ChangeNameActivity::class.java)
음 '공부했어요'에 올리신 게시물을 참고해서 이해했습니다! 그런데 '공부했어요'에서는 companion object 안에 구현을 하셨던데 뷰모델 안에서도 가능한가요?

2024-01-14 16:23 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +        }
참고해서 수정해보겠습니다~

2024-01-14 18:42 UTC, s9hn approved these changes
LGTM

2024-01-14 18:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
> +    }
avatar는 사용하지 않는 것 같은데 왜 필요한가용 .. ?

2024-01-14 18:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +        viewModel = ViewModelProvider(this).get(MyPageViewModel::class.java)
추후 여러 생성자가 추가되어도 by viewModel를 활용해 깔끔히 사용 가능합니당

2024-01-14 18:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +    private fun launchChangeNameOnClick() {
네이밍이 하나의 성격만 가졌으면 좋겠습니다
무언가를 클릭하는 함수입니다 or 클릭 시 일어나는 일입니다.

2024-01-14 18:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            val intent = Intent(binding.root.context, ChangeNameActivity::class.java)
Context는 무엇인가요?
context 공부해서 공부했어요 올려보시죠

1. binding.root.context
2. getContext()
3. requireContext()
4. applicationContext

2024-01-14 18:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
> +class MyPageViewHolder(private val binding: ItemAvatarBinding, adapter: MyPageAdapter) :
음..? 뷰홀더가 어째서 어댑터를 가지고 있을까용..?

2024-01-14 18:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
> +    val avatarData: MutableLiveData<List<Avatar>> get() = _avatarData
avatars가 어떨지요

2024-01-14 18:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +                10
상수화

2024-01-14 18:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +        editText.background.setTint(ContextCompat.getColor(this, backgroundColor))
배경색을 바꿔주는 함수같은데 함수이름이 의도를 정확히 나타내는 것 같지는 않아보여용
추가로 컨텍스트는 this를 사용할 순 없나요?

2024-01-14 20:49 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
> +    }
아 필요가 없는 부분이네요;; 해당사항 수정했습니다!

2024-01-14 20:56 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    var onItemClickListener: ((Avatar) -> Unit)? = null
요기 nullable 해염

2024-01-14 21:00 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
> +    private lateinit var binding: DialogAvatarBinding
생명주기와 맞아야 한다고 알고 있습니다.

2024-01-14 21:04 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    fun setAvatarList(avatarList: List<Avatar>) {
넵 수정하겠습니다

2024-01-14 21:08 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    fun onAvatarItemClickListener(listener: (Avatar) -> Unit) {
넵! 알겠습니다!

2024-01-14 21:18 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +        viewModel = ViewModelProvider(this).get(MyPageViewModel::class.java)
return �binding.root는 해당 프레그먼트의 ui를 타나내는 루트뷰를 반환합니다. 반환되기 전에 수행중인 로직들이 많아지면 사용자에게는 응답하지 않은 것처럼 보일 수 있습니다.

2024-01-15 07:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
> +    private lateinit var binding: DialogAvatarBinding
@m6z1

2024-01-15 08:21 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            val displayText = getString(R.string.my_page_user_name, userName)
LiveData나 ViewModel과 같은 데이터 관찰이 필요한 경우, viewLifecycleOwner를 사용하여 뷰의 생명주기에 맞게 데이터를 관찰하고 적절한 시점에 해제할 수 있다고 하여 사용하였습니다. 마이페이지 프레그먼트는 뷰모델을 사용하고 있어서  viewLifecycleOwner사용이 적절하다고 판단했습니다.

2024-01-15 08:28 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +            val displayText = getString(R.string.my_page_user_name, userName)
넵 수정하겠습니다1

2024-01-15 08:29 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +                startActivity(intent)
구현과정에서 인텐트가 안되서 썼었는데 따로 수정을 하지 않았습니다! 예외처리가 여기서는 필요 없는 것 같다는 의견이 많아서 이 부분은 수정했습니다.

2024-01-15 08:36 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +    private fun launchChangeNameOnClick() {
수정했습니다~

2024-01-15 08:59 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
> +class MyPageViewHolder(private val binding: ItemAvatarBinding, adapter: MyPageAdapter) :
아이템 클릭리스너 구현하면서 필요해서 가지고있는 건데 혹시 문제가 되나요?

2024-01-15 09:01 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
> +    val avatarData: MutableLiveData<List<Avatar>> get() = _avatarData
넵 수정했습니다

2024-01-15 09:07 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
> +        viewModel = ViewModelProvider(this).get(MyPageViewModel::class.java)
넵 수정했습니다

2024-01-15 09:07 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +                10
상수화했습니다

2024-01-15 09:08 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
> +    var onItemClickListener: ((Avatar) -> Unit)? = null
아 수정하겠습니다!

2024-01-15 09:11 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
> +        editText.background.setTint(ContextCompat.getColor(this, backgroundColor))
setEditTextFocusColor 로 수정했습니다

2024-01-15 14:55 UTC, librarywon approved these changes

2024-01-15 14:56 UTC, merged