feat: 작품상세 1차 QA 대응
Team-WSS/WSS-Android pull request #301
Opened 2024-09-09 16:20 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #294

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 자세한 수정사항은 이슈에 있습니다

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/user-attachments/assets/ca7294e1-5819-4940-8af5-3d039ab32c63

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
- 아마 가장 로직수정이 많은 QA 피알일겁니다 코드 길이 양해 부탁드립니다 :)
- 영상에는 새로고침되는게 잘 안담겨버렸는데 잘 작동하는거 확인했습니다!!

2024-09-10 00:17 UTC, m6z1 approved these changes
LGTM

2024-09-10 00:17 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailCoverDialogFragment.kt
> +            WindowManager.LayoutParams.MATCH_PARENT
r: 트레일링 콤마

2024-09-10 00:17 UTC, m6z1 commented on app/src/main/res/values/strings.xml
> +    <string name="novel_detail_report_url">http://pf.kakao.com/_kHxlWG</string>
c: url을 string에서 관리하는 이유가 궁금해요, string 리소스의 관심사에는 url이 포함되지 않는다고 생각합니다.

2024-09-10 12:46 UTC, librarywon commented on app/src/main/res/values/strings.xml
> +    <string name="novel_detail_report_url">http://pf.kakao.com/_kHxlWG</string>
그러게요? locate 대응을 할 것도 아니고

2024-09-11 09:32 UTC, librarywon requested changes
고생하셨습니다 리뷰확인해주세요

2024-09-11 09:32 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +    private lateinit var novelRatingLauncher: ActivityResultLauncher<Intent>
c: 지연 초기화를 하는 이유가 무엇인가요?

2024-09-11 09:32 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +            delay(UPDATE_TASK_DELAY)
c: 뷰모델에서 딜레이를 주지 않고 엑티비티에서 `Dispatchers.IO`를 열어서 딜레이를 주는 이유가 궁금하네요

2024-09-11 09:32 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
> +            putExtra("ratingResult", true)
c: "ratingResult" 도 const val 로 선언가능하긴 하겠네요

2024-09-11 13:59 UTC, junseo511 commented on app/src/main/res/values/strings.xml
> +    <string name="novel_detail_report_url">http://pf.kakao.com/_kHxlWG</string>
여러 뷰에서 같은 링크 사용하길래 다른 곳에 빼두려고 둔게 스트링이었습니다 다른 대안 있으면 통일하면 감사
@m6z1 @librarywon

2024-09-11 16:48 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +    private lateinit var novelRatingLauncher: ActivityResultLauncher<Intent>
아래쪽에 놓는게 깔끔해보여서 내렸습니다 원하신다면 위로 올려둘게용

2024-09-11 16:48 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +            delay(UPDATE_TASK_DELAY)
아 맞네 왜 이생각을 못했을까요

2024-09-11 16:48 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelRating/NovelRatingActivity.kt
> +            putExtra("ratingResult", true)
이친구가 문득 있어야할까라는 생각도 드네요

2024-09-11 16:48 UTC, junseo511 commented on app/src/main/res/values/strings.xml
> +    <string name="novel_detail_report_url">http://pf.kakao.com/_kHxlWG</string>
추후 딥링크 머지되면 반영하겠습니다

2024-09-11 17:56 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +    private lateinit var novelRatingLauncher: ActivityResultLauncher<Intent>
저는 지연초기화 이유가 없다고 생각해서 올려서 val 로 선언해주세요

2024-09-11 18:00 UTC, librarywon approved these changes
LGTM

2024-09-11 18:00 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
a: 👍

2024-09-11 18:05 UTC, merged