feat: 상세탐색 1차 QA 대응
Team-WSS/WSS-Android pull request #304
Opened 2024-09-11 08:38 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #291 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- [x] (상세탐색) - 키워드 검색결과 없을 때 카카오톡 채널로 이동
- [x] (상세탐색) - 키워드 칩 크기 수정하기(잘림 현상)
- [x] (상세탐색) - 선택한 키워드가 1개라도 있을 시에 위에서 아래로 세게 당기면 생기는 찌부 현상 해결하기
- [x] (상세탐색) - 키워드 탭에서 정보 탭으로 이동했다가 돌아오면 키워드 전체화면으로 돌아오기
- [x] (상세탐색) - 상세탐색 검색바 눌렀을 때, 기존 화면에서 바텀시트 뜨게 하고 재검색 시 바텀시트 내리기
- [x] (상세탐색) - 상세탐색 뒤로가기 눌렀을 때, 다이얼로그 종료된 exploreFragment 보이게 하기
- [x] (상세탐색) - 상세탐색 loading 인스턴스 추가하기
- [x] (상세탐색) - '~한 필터가 적용됐어요' ux 라이팅 변경된 사항 적용하기

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/f11caab2-8246-439e-8655-411ac6088718

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-09-11 11:23 UTC, librarywon requested changes
고생하셨습니다 리뷰 확인해주세요

2024-09-11 11:23 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(KAKAO_INQUIRE_URL))
c: 이 KAKO_URL 어느 한곳에서 관리하면 참 좋을텐데~~~

2024-09-11 11:23 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultInfoFragment.kt
> +            }
c:
```suggestion
      val selectedChip = selectedStatus?.let { 
          SeriesStatus.fromIsCompleted(it).title 
      }
```

2024-09-11 11:23 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(KAKAO_INQUIRE_URL))
뭉치가 만들어준 오브젝트 파일에 넣어두던가~~~~~~

2024-09-11 11:23 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultViewModel.kt
> +                appliedFilters.add(KEYWORDS_LABEL)
a: 👍 👍

2024-09-11 11:23 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/detailExploreResult/DetailExploreResultViewModel.kt
> +    fun updateIsBottomSheetOpen(isOpen: Boolean) {
a:
```suggestion
    fun updateIsBottomSheetOpen(isBottomSheetOpen: Boolean) {
```

2024-09-11 11:23 UTC, librarywon commented on app/src/main/res/values/strings.xml
> +    <string name="detail_explore_result_filter_description">\u00A0적용</string>
c: \u00A0 이거 뭔가용

2024-09-11 11:24 UTC, m6z1 commented on app/src/main/res/values/strings.xml
> +    <string name="detail_explore_result_filter_description">\u00A0적용</string>
띄어쓰기욥~

2024-09-11 14:24 UTC, junseo511 approved these changes
땡지티엠 칩 잘쓸게용

2024-09-11 14:24 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreViewModel.kt
> +import android.util.Log
r: 얍

2024-09-11 14:24 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            setWebsosoChipCloseIconEndPadding(12f.toFloatPxFromDp())
a: 애정합니다 선생님

2024-09-11 14:24 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(KAKAO_INQUIRE_URL))
이거 어칸담 🤔

2024-09-11 14:44 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/detailExplore/keyword/DetailExploreKeywordFragment.kt
> +            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(KAKAO_INQUIRE_URL))
반영완! [커밋](https://github.com/Team-WSS/WSS-Android/pull/304/commits/cf4fe1b83f0d3afd2fdd6f915593838d6d38c8c0)

2024-09-11 14:44 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreViewModel.kt
> +import android.util.Log
와 ~

2024-09-12 01:13 UTC, librarywon approved these changes

2024-09-12 01:26 UTC, merged