feat: 홈 1차 QA 대응
Team-WSS/WSS-Android pull request #312
Opened 2024-09-12 08:06 UTC by librarywon

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #290 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- [x] 오늘의 인기작 리사이클러뷰로 변경
- [x] ~~관심글  리사이클러뷰로 변경
- [x] ~~관심글 별점과 제목 위치 변경 
- [x] onResume()에 서버 불러오는 로직 넣기
- [x] 오늘의 인기작 사용자 프로필 라운드값 적용
- [x] 관심작품이 있는데 관심작품의 글이 없는 경우 케이스 UI 대응

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/user-attachments/assets/69780799-126b-4315-bbd0-004c7e5f7312

- 관심작품은 있지만 관련 피드가 없는 경우
<img width="354" alt="스크린샷 2024-09-12 오후 4 49 38" src="https://github.com/user-attachments/assets/618bb9e9-1f75-4a63-a11d-73a5a4ac9548">

- 관심작품 있는데 관련 피드 있는 경우
<img width="366" alt="스크린샷 2024-09-12 오후 4 50 47" src="https://github.com/user-attachments/assets/14770a92-7976-4dcd-a569-2fb3642707ce">

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-09-12 08:35 UTC, m6z1 requested changes
코멘트 확인부탁드려요 👍 빠른 작업 굿이네요

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/UserInterestFeedsEntity.kt
> +            return values().find { it.message == message }
c: 
```suggestion
            return entries.find { it.message == message }
```

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/model/UserInterestFeedsEntity.kt
> +enum class UserInterestFeedMessage(val message: String) {
a: 이 메시지 처리를 data 단에서 해주어야 하나요 ?? 받아온 메시지에 따라서 ui 상태가 달라지는 거니 ui 레이어에서 진행되는 게 아닌지! 데이터 레이어에서 enum class 를 만드신 이유가 궁금해요

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +
c: onResume 은 onCreate의 메서드가 끝난 뒤로 옮기면 좋을 것 같아요 (동반 객체 위)

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                clHomeNoAssociatedFeed.visibility =View.GONE
r: 여기 포맷팅 안 되어 있는 것 같아요

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                        UserInterestFeedMessage.NO_ASSOCIATED_FEEDS -> true
c: 여기 UserInterestFeedMessage import 하면 좋을 것 같아요 👍

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                    userInterestFeeds = userInterestFeeds.userInterestFeeds
r: 트레일링 콤마

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                    error = true
r: 여기도 트레일링 콤마

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/res/layout/fragment_home.xml
> +                        android:text="아직 관심 등록한 작품과 관련된 글이 없어요"
r: 스트링 추출

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/res/layout/item_popular_novel.xml
> +            cornerRadius="@{8.7f}"
a: 이 부분 소수점 디쌤이 잘못 설정해두신 게 아닐까여 한 번 여쭤보면 어떨지!

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/res/layout/item_user_interest_feed.xml
> +            android:id="@+id/li_user_interest_rating"
r: `@+id/ll`

2024-09-12 08:35 UTC, m6z1 commented on app/src/main/res/layout/item_user_interest_feed.xml
> +            android:breakStrategy="balanced"
a: 오 이건 무슨 속성인가요?

2024-09-12 19:58 UTC, s9hn approved these changes
빠른 머지를 위해 어프는 눌러놓겠습니다.

2024-09-12 19:58 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +        homeViewModel.updateHomeData()
c: 
(우테코 안드 교육 과정에 Compose를 넣어야한다 토론중)
레x아: 아니 아직도 온리쥼에 서버통신 코드 넣는 사람도 있다니까요??

   -9월 7일자 실제 대화 내용 일부 발췌 -

2024-09-12 19:58 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                        clHomeNoAssociatedFeed.visibility =View.GONE
r: 여기도 !

2024-09-12 19:58 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                        clHomeNoAssociatedFeed.visibility =View.VISIBLE
r: 복붙의 ..

2024-09-12 19:58 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                when(homeViewModel.uiState.value?.isInterestNovel){
r: 포맷팅이 왜 다 안되어있쬬

2024-09-12 19:58 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +
r: 개행 2줄

2024-09-13 01:29 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/model/UserInterestFeedsEntity.kt
> +enum class UserInterestFeedMessage(val message: String) {
이 함수는 그저 상태만 정의하고 있습니다. ui상태가 달라지는 로직은 ui 레이어에 있구요

2024-09-13 01:35 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                        UserInterestFeedMessage.NO_ASSOCIATED_FEEDS -> true
UserInterestFeedMessage는 이미 임포트가 되어있습니다

2024-09-13 01:37 UTC, librarywon commented on app/src/main/res/layout/item_popular_novel.xml
> +            cornerRadius="@{8.7f}"
일단 9로 변경해볼게요

2024-09-13 01:39 UTC, librarywon commented on app/src/main/res/layout/item_user_interest_feed.xml
> +            android:breakStrategy="balanced"
그 단어별 줄바꿈입니다 우리 앱잼 때 부토...썻는데

2024-09-13 01:40 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                when(homeViewModel.uiState.value?.isInterestNovel){
정확히 복붙 ㅋㅋㅋ

2024-09-13 01:43 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +        homeViewModel.updateHomeData()
흐음 이건 2차 QA 이후 개선하겠습니다 #317 이슈 발급 완료

2024-09-13 01:46 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                        UserInterestFeedMessage.NO_ASSOCIATED_FEEDS -> true
옵션 + 엔터 누르면 import 멤버스 어쩌구 ~ 로 임포트 해서 
```suggestion
                        NO_ASSOCIATED_FEEDS -> true
```
이렇게 쓸 수 있습니다

2024-09-13 01:46 UTC, m6z1 approved these changes

2024-09-13 01:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                        UserInterestFeedMessage.NO_ASSOCIATED_FEEDS -> true
아! 아래 enum class ㄷㄷ

2024-09-13 01:48 UTC, merged