feat: 데이타스토어 정비 및 기능 추가
Team-WSS/WSS-Android pull request #337
Opened 2024-09-19 14:59 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #321

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 기존 데이터스토어를 이전했습니다
- 데이터스토어 확장함수를 추가했습니다
- 토큰을 저장할 수 있는 데이터스토어 함수를 추가했습니다

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
레퍼런스는 드로이드나이츠하고 나우인안드로이드, 오프로드에서 제가 직접 수정한 코드입니다

2024-09-19 16:28 UTC, s9hn requested changes

2024-09-19 16:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +    @Named("userPreferencesDataStore") private val dataStore: DataStore<Preferences>,
a: 우리 dataStore가 여러개인가요??

2024-09-19 16:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +    object PreferencesKey {
c: 여기 위치한 이유가 무엇인가요?

2024-09-19 16:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +        return dataStore.data.first()[PreferencesKey.ACCESS_TOKEN_KEY] ?: ""
c: orEmpty() 어떠심?

2024-09-19 16:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +    private fun Context.createDataStore(preferencesName: String): DataStore<Preferences> {
c: DataStoreModule에 위치하는건 별로인 것 같아요

2024-09-19 16:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +    @Named("userPreferencesDataStore")
c: Named가 필요한 이유가 무엇인가용

2024-09-19 16:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +class UserPreferencesDataSource @Inject constructor(
c: 왜 dataSource인가요?

2024-09-20 00:24 UTC, m6z1 reviewed
코드 확인했습니다. 그런데 resovled 하려는 이슈와 피알 내용이 다른 것 같아서 다시 수정하셔야 할 것 같아요!

2024-09-20 06:37 UTC, librarywon commented
이슈와 피알 내용이 다른 것은 제가 토큰 관리 쪽을 요청드려서 그런거 같습니다!

2024-09-21 07:13 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +    @Named("userPreferencesDataStore") private val dataStore: DataStore<Preferences>,
원래 두개를 만들었는데 하나를 지웠습니다!!

2024-09-21 07:14 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +    object PreferencesKey {
드나에서 이렇게 쓰더라구요 데이터소스가 직접 키값을 가지고 있는 것도 괜찮다고 생각했습니다!

2024-09-21 07:15 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +        return dataStore.data.first()[PreferencesKey.ACCESS_TOKEN_KEY] ?: ""
코틀린스럽고 좋은듯요

2024-09-21 07:16 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +    @Named("userPreferencesDataStore")
데이터스토어 종류가 추가되면 충돌이 발생하더라구요? 그래서 추가했던 것 같습니다 🤔

혹시 하나의 데이터스토어를 모두가 공유해야하나요...?

2024-09-21 07:18 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +class UserPreferencesDataSource @Inject constructor(
이 부분 역시 드나에서 이렇게 사용하더군요! 데이터스토어가 아닌 다른 로컬 저장소로 교체되더라도 네이밍이 바뀌지 않아도 될 것 같아서 괜찮다고 생각해서 채택했습니다 :)

2024-09-21 08:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +    @Named("userPreferencesDataStore") private val dataStore: DataStore<Preferences>,
그럼 Named 어노테이션은 필요 없을 것 같아요!

2024-09-21 08:08 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +    object PreferencesKey {
그럼 동반 객체로 가져가도 좋을 것 같아요~

2024-09-21 08:09 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/DataStoreModule.kt
> +    @Named("userPreferencesDataStore")
하나의 데이터스토어밖에 사용하고 있지 않으니 불필요한 어노테이션 같아요

2024-09-21 08:11 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/datasource/UserPreferencesDataSource.kt
> +class UserPreferencesDataSource @Inject constructor(
드나나 구글 공식 레포가 정답인것은 아닙니다! 그리고 적어주신 이유는 레포지토리 이름으로도 가능한 내용입니다
특히 클래스명은 팀 컨벤션이니까 적용전에 상의해보는 것도 좋겠습니다 :)

2024-09-21 16:05 UTC, s9hn requested changes

2024-09-21 16:05 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/repository/UserRepository.kt
> +    private val dataStore: DataStore<Preferences>,
r: 않이. 이전에도 비슷한 리뷰 남긴것 같은데.... 공식문서에서도 구현체를 밝히는 네이밍은 권장하지 않아요 :(

2024-09-21 16:59 UTC, s9hn approved these changes

2024-09-23 05:41 UTC, librarywon approved these changes
고생하셨습니다

2024-09-23 05:42 UTC, merged