Feat/317
Team-WSS/WSS-Android pull request #343
Opened 2024-09-21 09:56 UTC by librarywon

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #317 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
 
<img width="572" alt="스크린샷 2024-09-21 오후 6 49 04" src="https://github.com/user-attachments/assets/b39e956b-7524-437f-9848-8ccaeccd9f87">
의 자극을 받고 로직을 개선하였습니다

startActivityLauncher를 통해서 `Activity.RESULT_OK`응답이 온다면 서버통신을 시키는 로직으로 개선하였으며

홈에서 이동가능한 뷰에서 백버튼을 누르거나 백 버튼 아이콘을 눌렀을 때 Home에서 왔을 경우에만 `Activity.RESULT_OK`를 하고 돌아가는 로직을 구성하였습니다.

홈에서 갈 수 있는 뷰가
1. NovelDetail
2. FeedDetail
3. NormalExplore
4. ProfileEdit
인데 프로필 편집 같은 경우에는 준서가 먼저 로직을 처리해야해서 준서가 알아서 잘 붙이겠죠?

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/6a2cb143-07b5-4d83-911e-6a34fe53895f

https://github.com/user-attachments/assets/4bd303fc-a4e8-419b-adec-228cdeb769e6

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-09-21 14:54 UTC, m6z1 approved these changes
굿굿 onResume 서버 통신을 없애셨네요 b

2024-09-21 14:54 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +    private val fromViewName by lazy { intent.getStringExtra(FROM_VIEW_NAME) }
c: previousViewName 모 요런 건 어떤가요 ?

2024-09-21 14:54 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                SOURCE_HOME
r: 트레일링 콤마

2024-09-21 14:54 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                SOURCE_HOME
r: 여기두

2024-09-21 14:54 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                        SOURCE_HOME
r: d여기두

2024-09-21 14:55 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +    private val fromViewName by lazy { intent.getStringExtra(FROM_VIEW_NAME) }
previous는 개인적으로는 별로인 것 같아요!

2024-09-21 16:57 UTC, s9hn approved these changes
재원TM~

2024-09-21 16:57 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +    private val fromViewName by lazy { intent.getStringExtra(FROM_VIEW_NAME) }
a: 이전 스택 뷰 라는 의미가 내포되면 좋을 것 같아요

2024-09-21 16:57 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +        }
a: 이 코드랑 아래 backbutton 클릭이랑 하는일이 어떻게 다른가요?

2024-09-21 16:57 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +            }
a: 저희 이거 상수값 이넘클래스로 정의하고 다같이 맞춰볼까요?

2024-09-22 04:46 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +    private val fromViewName by lazy { intent.getStringExtra(FROM_VIEW_NAME) }
이전 스택뷰 괜찮네요 그 방향으로 수정하겠습니다

2024-09-22 04:47 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +        }
이건 소프트 키보드 뒤로가기 혹은 스와이프로 뒤로가기를 할 때 처리하는 로직입니다

2024-09-22 04:48 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +            }
그럼 빠르게 맞춰봐야겠네요! 지금 1주일남아서 산군님이 틀을 잡아두신게 있어서 그거에 맞춰볼까요?

2024-09-23 17:41 UTC, s9hn requested changes

2024-09-23 17:41 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +                setResult(Home.RESULT_OK)
r: FeedDetail 뷰는 FeedDetail에 대한 결과값을 set 해주는게 더욱 어울려보입니다! 여기서 Home을 세팅해주는 건 어색해보여요.

2024-09-24 02:40 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
> +                setResult(Home.RESULT_OK)
네 확인하였습니다 다른뷰도 같은 방식으로 개선이 필요해보이네요

2024-09-25 08:16 UTC, s9hn approved these changes
고생하셨씁니다

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/feedDetail/FeedDetailActivity.kt
>          finish()
c: 

``` kotlin
 onBackPressedDispatcher.addCallback(this) {
            handleBackPressed()
        }

```
전부가 들어가야할 것 같아요

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +            }
a: 한줄짜린 괄호없애고 한줄로 쓰시는 것이..

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
>                          getString(R.string.home_nickname_interest_feed, nickname)
a: R.string import해버리면 한줄로 쓰는게 가능할지도 ?

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                        requireContext()
a: 트레일링콤마

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +            _uiState.value = _uiState.value?.copy(loading = true)
a: 사용은 읽기전용으로

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                    popularFeeds = popularFeeds.popularFeeds.chunked(3),
a: ui 로직은 모델내부에서 해도 좋아보여요

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                    error = true
a: 트레일링

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +    fun updateFeedData() {
a: Data란 표현은 굳이 안넣어도 될것같아요

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
>      fun updateHomeData() {
a: Data 빼도 될 것 같아요

2024-09-25 08:16 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +            else -> true
a: NO_INTEREST_NOVELS -> false
else -> true 
만해도 결과가 같을 것 같아요.

2024-09-25 08:29 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
>                          getString(R.string.home_nickname_interest_feed, nickname)
맛있네요

2024-09-25 08:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +            _uiState.value = _uiState.value?.copy(loading = true)
확인입니다.

2024-09-25 08:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                    popularFeeds = popularFeeds.popularFeeds.chunked(3),
아 이건 공수가 조금 들어서 추후 수정하겠습니다

2024-09-25 08:30 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +    fun updateFeedData() {
좋습니다

2024-09-25 08:31 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +            else -> true
` NO_ASSOCIATED_FEEDS -> true` 라는 것을 명시해서 보는 사람이 더 쉽게 코드를 알 수도록 작성하고 싶어서 이건 유지하고 싶습니다!

2024-09-25 08:35 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +            else -> true
보는 사람들에게 유의미한 명시인지 모르겠어요 :(

2024-09-26 06:31 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +            else -> true
else로 확인하는 것보다 `NO_ASSOCIATED_FEEDS`라는 것을 직관적으로 보여주는게 좋지 않을까요?

2024-09-26 07:46 UTC, merged