feat: 보관함 api 연결
Team-WSS/WSS-Android pull request #347
Opened 2024-09-24 01:16 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #246 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 정렬 팝업메뉴 구현
- 읽기상태/정렬에 따른 api 연결
- 소설 아이템 클릭 > novelDetail 이동
## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/1e7b68f4-003b-4462-8eb4-d23aef28374d

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-09-24 01:48 UTC, m6z1 approved these changes
고생하셨어요 b 👍

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +                override fun onTabReselected(tab: TabLayout.Tab?) {}
c: 사용하지 않는 부분이라면 요런식으로 빼도 좋을 것 같아요
```suggestion
                override fun onTabUnselected(tab: TabLayout.Tab?) = Unit
                override fun onTabReselected(tab: TabLayout.Tab?) = Unit
```

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +    private val userRepository: UserRepository
r: 요기 트레일링 콤마

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                val storageResponse = response
r: stroageResponse 변수를 따로 만드는 이유가 있나요? 바로 response로 사용하면 될 것 같은데!

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                val canLoadMore =
c: 요런 네이밍은 어떨지?
```suggestion
                val isLoadMore =
```

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                    storageResponse.isLoadable && storageResponse.userNovels.isNotEmpty()
c: 비어있을 경우에 대한 분기처리는 따로 해주지 않아도 되나요? canLoadMore 이란 변수에서만 사용되는 것 같아서 여쭤봅니다!

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +            }.onFailure { throwable ->
r: 사용하지 않는 파라미터는 제거해줘도 될 것 같아유

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageItemAdapter.kt
> +    private val novelClickListener: (Long) -> Unit,
r: 어떤 거에 대한 Long 타입인지 적어주면 좋을 것 같아요!

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageItemAdapter.kt
> +        }
c: adapter가 아닌 viewHolder에서 clickListener에 대한 값을 adapter로 넘겨줘도 될 것 같아욥

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerAdapter.kt
> +    private var novels: List<StorageEntity.StorageNovelEntity>,
r: 
```suggestion
    private val novels: List<StorageEntity.StorageNovelEntity>,
```

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/model/SortType.kt
> +enum class SortType(val apiValue: String, val displayName: String) {
c: 뷰에서 데이터를 몰라야 하는 건 아니지만, apiValue 보다는 다른 네이밍을 가지면 좋을 것 같아요! 가령 다른 분들의 코드처럼 이런 식으로?
```suggestion
enum class SortType(val titleEn: String, val titleKr: String) {
```

2024-09-24 01:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/storage/model/StorageUiState.kt
> +    val isLoadable:Boolean = true,
r: 포맷팅이 안 되어있어요

2024-09-24 06:09 UTC, librarywon requested changes
너무 고생하셨습니다 정말 까다로운 뷰인데 대단하신군요... 리뷰 확인해주시면 감사드리겠습니다.

2024-09-24 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +
r: 이 개행은 없어도 괜찮을 거 같아요

2024-09-24 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/storage/model/StorageUiState.kt
> +    val isLoadable:Boolean = true,
이게 보여?

2024-09-24 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/storage/model/StorageTabs.kt
> +    QUITTING(3, "하차", "QUITTING");
c: 하차니까 `QUIT`이 아닌가 싶습니다 영어센세한테 감히 여쭤봅니다.

2024-09-24 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +
r: 이것두?

2024-09-24 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                    userId = 2L,
a: 이거 추후에 제가 MainViewModel에 userId를 담아둘테니 MyPage에서 MainViewModel을 activityViewModel로 받아서 StorageViewModel로 id를 Intent로 넘겨주시면 될거에요

2024-09-24 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                    size = 20,
c: 받아오는 사이즈도 상수화 해볼까요?

2024-09-24 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerAdapter.kt
> +    private val novelClickListener: (Long) -> Unit,
r: 이렇게 변수명을 명시해볼까요?
```suggestion
    private val novelClickListener: (novelId : Long) -> Unit,
```

2024-09-24 06:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerViewHolder.kt
> +    private val novelClickListener: (Long) -> Unit,
r: 여기도 동일합니다.

2024-09-24 06:54 UTC, junseo511 reviewed
진짜진짜 잘해지심 👏👏 파이팅입니다

2024-09-24 06:54 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
a: 아 이거 분리하셨네요? ㄱㅊ은듯?

2024-09-24 06:54 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +        _uiState.value = _uiState.value?.copy(readStatus = readStatus)
```suggestion
        _uiState.value = uiState.value?.copy(readStatus = readStatus)
```

2024-09-24 06:54 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                val canLoadMore =
c: 요건 어떠신지?
```suggestion
                val isLoadable =
```

2024-09-24 06:54 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/storage/model/StorageTabs.kt
> +    QUITTING(3, "하차", "QUITTING");
a: 형용사 느낌이니까 QUIT이 맞지 않을까유?!라고 카톡방에서 말씀드린 것 살짝 적어드리고 갑니다 👍 파이팅이예요~~

2024-09-24 06:54 UTC, junseo511 commented on app/src/main/res/layout/activity_storage.xml
> +                android:text='@{String.valueOf(storageViewModel.uiState.userNovelCount)+ " 개"}'
c: 이거 uiState자체에서 처리해서 건너올 수 있을 것 같아요

2024-09-24 06:58 UTC, librarywon commented on app/src/main/res/layout/activity_storage.xml
> +                android:text='@{String.valueOf(storageViewModel.uiState.userNovelCount)+ " 개"}'
`%d개`도 String리소스에 넣을 수 있어요

2024-09-24 07:15 UTC, s9hn requested changes
너무 오랜만의 샐리 PR이라 재밌게 코드 리뷰했습니다.
가끔 PR 올라올 때마다 띄엄띄엄 성장한 게 보여서 흐뭇하네요.
객체를 분리하려는 시도도 보여서 재밌었고, 객지사를 읽는 중이라기에 좀 더 OOP스러운 리뷰 위주로 남겼습니다.
온전히 받아들이기보단, 반박하며 성장하세요! 
추가로 샐리는 다른 팀원들의 PR을 보는 경험이 필요해보여요!
이전 PR에 많이 리뷰되었던 부분들이나 컨벤션들이 아직 미숙한 모습이 보입니다.
타인의 코드를 읽고 해석하는 행위가 어렵긴하지만 
성장하는 가장 빠른 지름길은 어려운 길로 가는 것입니다 ㅎ
고생하셨습니다! 질문 편하게 하십시오

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
> +fun StorageResponseDto.toData(): StorageEntity {
c: 보관함을 의미하는 Storage는 맞지만, 뷰 네임 외적으로도 storage는 개발적인 네이밍으로 쓰이기에도 다분한 네이밍이죠! 따라서 좀 더 구체적인 ui네이밍을 표기해주면 좋을 것 같아요! MyStorage, MypageStorage같은것이요!

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
> +fun StorageResponseDto.StorageNovelDto.toData(): StorageEntity.StorageNovelEntity {
a: StorageEntity와 같은 import 가능한 것들은 import 처리해주면, 반환타입 등에 대해 좀 더 직관적으로 확인할 수 있을 것 같아요!

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/model/StorageEntity.kt
> +            get() = novelRating != 0f
c: visibility는 data 레이어의 책임인가요?

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/remote/response/StorageResponseDto.kt
> +    ){
r: ...... 안되겠네요 3차 QA 지나고 첫 이슈로 그냥 제가 CI 린트 붙이겠습니다

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +class SortClickHandler(
r: ClickHandler라는 네이밍에 맞게 정말 'Click'과 관련된 일들만 수행하고 있나요?

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +    private val viewModel: StorageViewModel,
a: 일반적으로 객체의 생성자로 인스턴스를 넘기는 행위는, 해당 객체에 추가적인 기능, 상태, 옵션 등을 덧붙이는 데코레이트 패턴 등이 아니면 굳이 잘 넘기진 않는 것 같아요. 객체간 생성자에 인스턴스를 넘기는 행위보단, 람다를 넘기는 구현 방식이 좀 더 안전해보여요!

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +    override fun onSortButtonClick(view: View) {
c: 클릭리스너 인터페이스를 '상속' 받았고, 반드시 해야만 하는 의무적인 일로 'onSortButtonClick'을 구현해야만 해요.
여기까지 보았을 땐 SortClickHandler로서 충분히 의미있는 일이지만, 정말 클릭에 관한 일만 하고 있다고 장담할 수 있나요?
제가 보기엔 너무 많은 일들을 하고 있어요

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +        val binding: MenuStoragePopupBinding = DataBindingUtil.inflate(
c: DataBindingUtil 방식으로 바인딩을 초기화한 이유가 있을까요? 관습적으로 사용했다면 이번 기회에 다시 한번 점검해보는 것도 좋겠어요

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +        binding.storageViewModel = viewModel
a: 아마 이 뷰모델을 넘겨주려고 뷰모델 인스턴스를 받았을 거라 짐작해요. SortClickHandler를 조합으로 들고 있는 Activity의 상태값을 '참조'하도록 수정해보세요

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +            novels = emptyList(),
a: novels는 StorageViewPagerAdapter를 인스턴스화 시키는 데 꼭 필수적인 '키'일까요? 아님 StorageViewPagerAdapter가 꼭 가져야할 '상태'일까요? 샐리 의견이 궁금합니다 :)

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +        binding.vpStorage.adapter?.let {
a:  binding.vpStorage.adapter가 nullable한가요? 그렇지않다면 let을 강제하기보단, apply 혹은 run을 사용해도 좋겠어요

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +                    }
a: let을 사용해 당장은 nullable한 객체를 사용함에 있어 편리함을 취할 순 있지만, 장기적으로 보았을 땐 어떨까요? 정말 말도 안되는 일로 tab이 null이 된다면 어떤일이 벌어지나요?

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +            (binding.vpStorage.adapter as? StorageViewPagerAdapter)?.updateNovels(uiState.storageNovels)
r: nullable한 캐스팅은 자칫하면 throw의 주 원인이 됩니다. 지금 로직에선 굳이 어댑터를 캐스팅할 필요가 없어보입니다. 
다른 팀원들의 뷰 코드에서 확인해볼 수 있듯이 대부분이 어댑터코드를 by 초기화하고 있는 이유가 이런 이유에서죠
리사이클러뷰 어댑터와 다를바가 없어요! 어댑터에게 업데이트하란 '메시지'를 보내도록 구현해주세요

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +    private fun updateViewPagerAdapter(uiState: StorageUiState) {
c: 뷰페이저를 업데이트하는게 아닌 '뷰'를 업데이트 하는 네이밍이 좀 더 적절해보입니다!

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageSortTypeClickListener.kt
> +    fun onSortButtonClick(view: View)
c: 인터페이스까지 추출한 이유는 무엇인가요?

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +        if (_uiState.value?.loading == true || (!forceLoad && _uiState.value?.isLoadable == false)) {
c: 상태값을 수정하는 게 아니라면, 기본적으로 읽기전용 프로퍼티를 사용하도록 구현해주세요

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +        if (_uiState.value?.loading == true || (!forceLoad && _uiState.value?.isLoadable == false)) {
c: 해당부분은 여러 분기를 하나의 if분기로 표현하려다보니 가독성이 조금 떨어진 것 같아요! when 을 사용해 분기를 하나씩 나눠보아도 좋아보입니다.

2024-09-24 07:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerAdapter.kt
>      private val navigateToExplore: () -> Unit,
c: 어댑터가 굳이 알 필요가 없는 구체적인 함수네이밍이라고 생각해요. 추가로 클릭 리스너에 관한 네이밍으로 저희 컨벤션이 onXXXClick입니다

2024-09-24 07:15 UTC, s9hn commented on app/src/main/res/layout/activity_storage.xml
> +                android:text='@{String.valueOf(storageViewModel.uiState.userNovelCount)+ " 개"}'
r: 다른분들의 코드를 참고해서 해당 문자열을 string 리소스로 관리해주세요 !

2024-09-24 14:49 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +                override fun onTabReselected(tab: TabLayout.Tab?) {}
감사함둥 수정하겠습니다!

2024-09-24 15:06 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                val storageResponse = response
아핳 그러네염!! 수정하겠슴당

2024-09-24 15:09 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                val canLoadMore =
isLoadable로 수정할게욤~ 감사해융

2024-09-24 15:23 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageItemAdapter.kt
> +    private val novelClickListener: (Long) -> Unit,
넵!

2024-09-24 15:25 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/model/SortType.kt
> +enum class SortType(val apiValue: String, val displayName: String) {
수정하겠습니다앙~

2024-09-24 15:55 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageItemAdapter.kt
> +        }
반영했습니다~

2024-09-25 07:05 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                    storageResponse.isLoadable && storageResponse.userNovels.isNotEmpty()
추후 새로운 이슈로 해결하겠습니다!

2024-09-25 07:06 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/model/StorageTabs.kt
> +    QUITTING(3, "하차", "QUITTING");
수정했습니당!

2024-09-25 07:06 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerAdapter.kt
> +    private val novelClickListener: (Long) -> Unit,
수정했습니당!

2024-09-25 07:11 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                    size = 20,
반영하겠습니당!

2024-09-25 07:11 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +                    userId = 2L,
넵! 알겠슴당

2024-09-25 07:21 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +        _uiState.value = _uiState.value?.copy(readStatus = readStatus)
적용하겠슴당

2024-09-25 07:38 UTC, yeonjeen commented on app/src/main/res/layout/activity_storage.xml
> +                android:text='@{String.valueOf(storageViewModel.uiState.userNovelCount)+ " 개"}'
모두 반영했슴당~

2024-09-25 07:42 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
> +fun StorageResponseDto.toData(): StorageEntity {
구체적인 네이밍을 표기해주는 게 더 좋을 것 같아욤! 근데 해당 보관함이 나의 페이지에서 접근을 하게 된다면 'My'라는 표현을 쓰는게 적절하지만 다른 사람의 페이지에서 보관함에 접근 할 때는 'My'라는 표현을 사용하는게 어색하다고 느껴집니다! 그래서 'UserStorage', 'NovelStorage'는 어떨까요?

2024-09-25 07:43 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
> +fun StorageResponseDto.StorageNovelDto.toData(): StorageEntity.StorageNovelEntity {
넵 수정하겠습니다!

2024-09-25 07:49 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/model/StorageEntity.kt
> +            get() = novelRating != 0f
앗... 아니죠..ㅎ 수정하겠습니다

2024-09-25 07:52 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/remote/response/StorageResponseDto.kt
> +    ){
...지송합니다

2024-09-25 09:04 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +class SortClickHandler(
음.. 아니요 ㅎㅎ 현재 해당 클래스에서 팝업메뉴가 보여지는 일들도 같이 수행이 되고 있습니다... 'SortMenuHandler' 등으로 클래스 명 변경하는게 좋을 것 같네욤

2024-09-25 11:13 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +    private val viewModel: StorageViewModel,
아핳 감사합니당! 수정해보겠습니다!

2024-09-25 13:17 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +    override fun onSortButtonClick(view: View) {
클릭리스너 객체를 상속 받았기 때문에 해당 부분에서는 버튼의 클릭이벤트만 처리하는게 단일 책임 원칙에 적합할 것 같아요! 지금 클래스에서는 클릭이벤트 뿐만 아니라 팝업의 생성부터 바인딩하는 일까지 처리가 되고 있네욤..! 해당 부분은 수정하겠습니당! 감사해용

2024-09-25 13:45 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +        val binding: MenuStoragePopupBinding = DataBindingUtil.inflate(
앗. 제가 버튼 바인딩을 뷰바인딩으로 하고 있었지요..ㅎㅎㅎ 수정하겠습니다! 감사해용

2024-09-25 14:31 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/SortClickHandler.kt
> +        binding.storageViewModel = viewModel
이 부분 수정했습니당!

2024-09-25 14:42 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
> +fun StorageResponseDto.toData(): StorageEntity {
My는 그냥 예시였습니다! 뭐든 좋아요~

2024-09-25 14:47 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +            novels = emptyList(),
음.. 저는 '상태'라고 생각합니다! 제가 얼마전에 ㅎㅎ 읽은 객사오에 따르면 '상태'는 객체가 요청에 대해서 어떤 행동을 할지 선택할 수 있게 가지고 있는 것이라고 했습니다! 즉 '상태'는 선택의 영역이라고 볼 수 있습니다! 그렇다고 했을 때 novels가 '키'라면 novels가 존재하지 않는 상황(= 비어있는 리스트)의 경우 제대로 실행되지지 않겠다는 생각을 했습니다! 근데 코드 상에서 기본값으로 emptyList() 전달하고 있고 해당경우는 novels가 존재하지 않는 상황을 의미합니다. 그 상황에서 탐색으로 이동하는 null 화면을 제공하고 있기 때문에 novels를 선택의 영역인 '상태'라고 생각합니당:)

2024-09-25 14:51 UTC, yeonjeen commented on app/src/main/res/layout/activity_storage.xml
> +                android:text='@{String.valueOf(storageViewModel.uiState.userNovelCount)+ " 개"}'
넵 수정했습니다!

2024-09-25 15:03 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/data/mapper/UserMapper.kt
> +fun StorageResponseDto.toData(): StorageEntity {
예압 수정하겠습니당!

2024-09-25 15:14 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +        binding.vpStorage.adapter?.let {
apply로 수정하겠습니다앙

2024-09-25 15:21 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +                    }
만약 정말 그런 경우가 일어난다면 let 블럭 안에서 실행되지는 것들이 아무것도 동작하지 않을 것입니다.. 하지만 그런 경우는 매운 드문 경우이고 만약에 그런 경우가 발생한다면 그건 예외적으로 처리해야 하는 경우가 아닐까 하고 생각합니다...ㅎ 그래서 명시적으로 null이 아님을 보장하는 것이 더 좋을 것 같네용 수정하겠습니다!!

2024-09-25 15:25 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +                    }
만약 정말 그런 경우가 일어난다면 let 블럭 안에서 실행되지는 것들이 아무것도 동작하지 않을 것입니다..  그래서 null이 아님을 보장하거나 null을 체크하는 방향(이게 더 좋겠죠?)으로 수정하겠습니당

2024-09-25 15:52 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +            (binding.vpStorage.adapter as? StorageViewPagerAdapter)?.updateNovels(uiState.storageNovels)
넵 수정하겠습니당!

2024-09-25 15:55 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageActivity.kt
> +    private fun updateViewPagerAdapter(uiState: StorageUiState) {
그러네욤..! 수정하겠슴당

2024-09-25 16:01 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageSortTypeClickListener.kt
> +    fun onSortButtonClick(view: View)
actually... 다른 분들의 코드를 보다가 클릭이벤트 처리를 분리해서 사용하시길래 저도 함... 분리하는게 좋지 않을까? 라는 생각에 추출한건데 정렬 관련 버튼의 확장성이.. 있을 가능성이 낮아서 다소 불필요한 리소스 일 수 있겠다는 생각이 드네용.. 수정하는게 좋을 것 같습니다!

2024-09-25 16:16 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageViewModel.kt
> +        if (_uiState.value?.loading == true || (!forceLoad && _uiState.value?.isLoadable == false)) {
넵! 수정하겠습니다!

2024-09-25 16:22 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/storage/adapter/StorageViewPagerAdapter.kt
>      private val navigateToExplore: () -> Unit,
아핳.. 수정하겠습니다..!

2024-09-26 05:19 UTC, librarywon approved these changes
고생하셨습니다 나머지 코멘트확인해주시고 반영해주시면 머지하셔도 좋을 것 같습니다

2024-09-26 05:19 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +                    "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MiLCJpYXQiOjE3MjcyNzgxMTAsImV4cCI6MTcyODQ4NzcxMCwidXNlcklkIjoyfQ.pQl5jmjKkBftDcyegn7-MkZjN-H8OzmKkG0p5ZHwHaw"
a: 👍

2024-09-26 05:19 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageViewModel.kt
> +        }
c: when절을 이렇게 사용하신 의도를 잘 모르겠는데 설명해주실 수 있을까요?

2024-09-26 05:19 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemAdapter.kt
> +        }
r: 뷰홀더안에 클릭리스너를 달아두신거 같은데 이중으로 적용하신거 맞나요?

2024-09-26 05:19 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemViewHolder.kt
> +        }
c: bind될 때마다 setOnClickListener를 해주어야할까요? - 산군의 코드리뷰 매크로 27번

2024-09-26 05:19 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerViewHolder.kt
> +        }
r: 이것두

2024-09-26 05:20 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/storage/StorageSortTypeClickListener.kt
> +    fun onSortButtonClick(view: View)
보통은 뷰홀더에 다수의 클릭이벤트를 넘길때 사용합니다! 생성자로 너무 많은 람다를 보내기는 그러니까요!

2024-09-26 05:33 UTC, s9hn approved these changes
시간이 없으니 Approve는 해놓겠씁니다! r리뷰는 꼭 반영해주세요

2024-09-26 05:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
> +        isRatingVisible = novelRating != 0.0f,
r: 메퍼의 책임은 mapping입니다! 관련 로직은 Model 내부에 위치하는게 좋아보여요

2024-09-26 05:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/SortMenuHandler.kt
> +        val sortPopupHandler = SortPopupHandler()
r: showSortMenu 함수가 호출될 때마다 핸들러 객체를 새롭게 생성해요. 의도된 동작인가요? 그렇지 않다면 지연초기화 혹은 initialized를 활용해 하나의 인스턴스만 활용해도 좋을 것 같아요

2024-09-26 05:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/SortMenuHandler.kt
> +class SortMenuHandler(
a: 팝업과 메뉴를 구분한 이유를 잘 모르겠어요

2024-09-26 05:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
> +    private lateinit var userStorageAdapter: UserStorageViewPagerAdapter
r: adapter가 뷰 내에서 가변인가요? 어댑터는 한번의 초기화만 필요한 친구입니다

2024-09-26 05:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
> +        binding.onSortTypeClick = View.OnClickListener {
r:  onSortTypeButtonClick() 하나만 넘겨줘도 됩니다

2024-09-26 05:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerViewHolder.kt
> +            val adapter = UserStorageItemAdapter(novels, novelClickListener)
r: 가급적이면 함수에서 객체생성을 지양하는게 좋을 것 같아요. 지연초기화를 활용해 전역에서 관리하고, 고정인 혹은 정적인 뷰 초기화로직들은 init에서 한번만 진행해주세요

2024-09-26 05:33 UTC, s9hn commented on app/src/main/res/layout/activity_storage.xml
> +            type="android.view.View.OnClickListener" />
a: 함수 데이터바인딩은 다른분들 xml 코드에 있습니다 Function0 타입이요!

2024-09-26 06:08 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
> +        binding.onSortTypeClick = View.OnClickListener {
역시

2024-09-27 03:47 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageViewModel.kt
> +        }
정렬되는게 안되서 다른 조건들을 추가로 넣어보다가 미처 수정하지 못한 것 같습니당. 조건이 하나라서 if문으로도 충분할 것 같네용 수정하겠습니다!:)

2024-09-27 03:51 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemAdapter.kt
> +        }
아아앗... 수정하겠씁니다!

2024-09-27 04:11 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageItemViewHolder.kt
> +        }
음...뷰홀더 재활용시 매번 재설정을 해줘야 하니까 그런 면에서 비효율적일 수 있을 것 같아요..! 수정하겠습니당!

2024-09-27 04:13 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerViewHolder.kt
> +        }
넵!

2024-09-27 04:28 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/mapper/NovelMapper.kt
> +        isRatingVisible = novelRating != 0.0f,
넵 수정하겠습니당!

2024-09-27 04:32 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/SortMenuHandler.kt
> +        val sortPopupHandler = SortPopupHandler()
앗 그러네욤! 수정하겠습니다:)

2024-09-27 04:39 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/SortMenuHandler.kt
> +class SortMenuHandler(
메뉴는 팝업 메뉴를 표시하는 시점과 동작을 관리하는 역할을 하고 있고 팝업은 팝업 자체의 UI를 생성하고 보여주는 역할을 하고 있어서 분리한건데 불필요한 부분일까요ㅕ?

2024-09-27 05:20 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
> +    private lateinit var userStorageAdapter: UserStorageViewPagerAdapter
넵 수정하겠습니다

2024-09-27 05:31 UTC, yeonjeen commented on app/src/main/res/layout/activity_storage.xml
> +            type="android.view.View.OnClickListener" />
수정했습니당

2024-09-27 05:32 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageActivity.kt
> +        binding.onSortTypeClick = View.OnClickListener {
넵!

2024-09-27 05:37 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/adapter/UserStorageViewPagerViewHolder.kt
> +            val adapter = UserStorageItemAdapter(novels, novelClickListener)
넵! 수정하겠습니다!

2024-09-27 05:42 UTC, merged