feat: 활동 디테일 api 연결
Team-WSS/WSS-Android pull request #406
Opened 2024-10-04 10:53 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #395 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 활동 디테일 api 연결
- 내 활동/ 다른유저 활동 분기처리

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
[Screen_recording_20240928_133633.webm](https://github.com/user-attachments/assets/8343d228-f51d-4185-996e-3e83a6d666cb)

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
멍청이슈로...ㅎ 다른유저뷰모델에서 유저정보 불러오는 함수에 유저아이디 전달을 안했지 뭐예요..ㅎㅎㅎㅎㅎ 그래서 로드가 안된거였어욤...ㅎㅎ

2024-10-04 15:01 UTC, librarywon requested changes
문제가 잘 해결되서 다행입니다 리뷰 확인해주세요! 고생하셨습니다!

2024-10-04 15:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
>          val source: String? = intent.getStringExtra(MyActivityFragment.EXTRA_SOURCE)
r: 여기서 source를 두 번 받아오고 있는데 앞에서 받아온걸 넘겨받던가 하면 좋을 것 같습니다.

2024-10-04 15:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private fun setUpObserve(source: String?) {
a: 여기서는 잘 쓰고 있군요

2024-10-04 15:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            SOURCE_MY_ACTIVITY -> title = getString(R.string.my_activity_detail_title)
a: R.string 까지 임포트 하는 것도 좋을 것 같습니다.

2024-10-04 15:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        const val SOURCE_OTHER_USER_ACTIVITY = "otherUserActivity"
c: 저두 명지한테 받은 코리인데 EXTRA 보단 `USER_ID_KEY` 이런식으로 다른 분들이 하셔서 저는 통일하였습니다. 근데 이거까지 개취

2024-10-04 15:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +    private val size: Int = 10
r: 이건 상수화해야 하는 값 같습니다.

2024-10-04 15:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +    private val _lastFeedId = MutableLiveData<Long>().apply { value = 0L }
```suggestion
    private val _lastFeedId =  MutableLiveData<Long>(0L)
```
r: 이렇게 가능한걸로 알고 있습니다.

2024-10-04 15:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/mapper/UserMapper.kt
> +        avatarImage = this.avatarImage
r: 트콤

2024-10-04 15:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/mapper/UserMapper.kt
> +        avatarImage = this.avatarImage
r: 트콤

2024-10-07 08:30 UTC, s9hn requested changes

2024-10-07 08:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private var userId: Long = -1L
r: 뷰모델에서 관리해도 될 것 같아요 뷰모델의 '상태'들이니까요

2024-10-07 08:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private var userId: Long = -1L
뷰모델에서 stateSavedInstance를 활용해도 되고, intent에서 불러오는 값이며 본 activity의 상태값이라고 확신한다면 lateinit var보단 by lazy를 통한 선언이 더 안전해보여요

2024-10-07 08:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
>          binding.tvActivityDetailTitle.text = title
```suggestion
        binding.tvActivityDetailTitle.text = when (source) {
        SOURCE_MY_ACTIVITY -> getString(R.string.my_activity_detail_title)
        SOURCE_OTHER_USER_ACTIVITY -> getString(R.string.other_user_page_activity)
        }
```

c: 훨씬 간단해보여요

2024-10-07 08:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private fun setUpObserve(source: String?) {
c: 전역으로 관리하는데 굳이 매개변수로 넘겨줄 필요가 있나요?

2024-10-07 08:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +    private val _lastFeedId = MutableLiveData<Long>().apply { value = 0L }
r: 예전에도 리뷰 달았지만 livedata 초기화에 apply를 쓰지않아요

2024-10-07 08:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +        notifyDataSetChanged()
r: ListAdapter를 쓰는데 notifyDataSetChanged를 쓰는 이유가 있나요?

2024-10-07 08:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailViewHolder.kt
> +    fun bind(activity: ActivityModel, userProfile: UserProfileModel) {
c: 두 모델을 ActivityDetailModel 과 같은 이름으로 하나로 합쳐서 주는것은 어떨까요?

2024-10-07 08:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityViewModel.kt
> +        }
c: id를 가져오는 것도 userRepository, 내활동을 부르는것도 userRepository라면, userRepository안에서만 id를 알게해도 되지 않을까요?

2024-10-07 09:01 UTC, junseo511 reviewed
리뷰 남기고 갑니당~ 총총

2024-10-07 09:01 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        setUpObserve(source)
c: 위에서 선언해 주었는데 따로 주입해주는 이유가 있나요?

2024-10-07 09:01 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        userId = intent.getLongExtra(EXTRA_USER_ID, -1L)
c: -1L 정도는 상수화해도 괜찮아보여요

2024-10-07 09:01 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private fun setUpObserve(source: String?) {
222

2024-10-07 09:01 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        const val SOURCE_OTHER_USER_ACTIVITY = "otherUserActivity"
근데 프로젝트 통일성 유지정도는 괜찮을듯요

2024-10-08 00:40 UTC, m6z1 approved these changes
다른 분들이 리뷰 잘 남겨주신 것 같아요 !! 고생하셨슴다

2024-10-08 00:40 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        setUpObserve(source)
r: setupObserver()

2024-10-08 00:40 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/OtherUserActivityFragment.kt
>          setupObserve()
r: 
```suggestion
        setupObserver()
```

2024-10-08 00:42 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
>          val source: String? = intent.getStringExtra(MyActivityFragment.EXTRA_SOURCE)
넵 수정했습니다!

2024-10-08 00:43 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private fun setUpObserve(source: String?) {
타이틀 부분은 예전에 구현했던 부분이라서 반영이 안되었나보욤..ㅎ

2024-10-08 00:47 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +            SOURCE_MY_ACTIVITY -> title = getString(R.string.my_activity_detail_title)
우옷.. 그런 방법이?! 감사함둥

2024-10-08 00:57 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        const val SOURCE_OTHER_USER_ACTIVITY = "otherUserActivity"
이왕이면 통일하는게 좋으니까~ 수정하겠슴당

2024-10-08 01:08 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +    private val size: Int = 10
넵 수정하겠습니다

2024-10-08 01:09 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +    private val _lastFeedId = MutableLiveData<Long>().apply { value = 0L }
아앗.. 수정하겠습니다!

2024-10-08 01:14 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        userId = intent.getLongExtra(EXTRA_USER_ID, -1L)
넵! 수정하겠슴당

2024-10-08 02:10 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private var userId: Long = -1L
넵! 반영하겠습니다!

2024-10-08 02:10 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
>          binding.tvActivityDetailTitle.text = title
오.. 그러네염! 감사합니다!

2024-10-08 02:17 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    private fun setUpObserve(source: String?) {
앗.. 그래서 해당 부분 제거하고 수정했습니다..!

2024-10-08 08:24 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +        notifyDataSetChanged()
아앗.. 그러네염.. DiffUtil이 있는데,,, 수정하겠습니다!!1

2024-10-08 08:27 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        setUpObserve(source)
코드리뷰 반영하면서 해당부분 수정했습니다~

2024-10-08 08:36 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailViewHolder.kt
> +    fun bind(activity: ActivityModel, userProfile: UserProfileModel) {
아.. 그러면 굳이 2개 다 선언하지 않아도 되겠네욤...오오,,, 감사합니다!

2024-10-08 14:46 UTC, s9hn approved these changes
고생하셨씀다

2024-10-09 13:53 UTC, librarywon approved these changes
너무 고생하셨습니다 마지막 하나만 확인해주세요

2024-10-09 13:53 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +    private val size: Int = ACTIVITY_SIZE
```suggestion
    private val activityLoadSize: Int = ACTIVITY_LOAD_SIZE
```
c: 변수명이 애매한거 같은데  이렇게 수정해주는건 어떤지, 사이즈라고 그냥하면 뭔지 모르니까

2024-10-10 08:34 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailViewModel.kt
> +    private val size: Int = ACTIVITY_SIZE
넵 수정하겠습니다!!

2024-10-14 13:12 UTC, merged