refactor: 닫힌피알(#378 이슈) 코드리뷰 반영
Team-WSS/WSS-Android pull request #410
Opened 2024-10-15 19:52 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #409 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- #378 코드리뷰 반영

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-10-16 03:23 UTC, s9hn requested changes

2024-10-16 03:23 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +        submitList(currentList)
c: 외부에서 해주시면 됩니다!

2024-10-16 03:23 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
> +    BaseFragment<FragmentMyActivityBinding>(R.layout.fragment_my_activity),ActivityItemClickListener {
r: 왜 프래그먼트가 다른 인터페이스를 상속받고 있죠...??? 익명객체로 구현해주세요!!

2024-10-16 03:23 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
> +        val userId = arguments?.getLong(USER_ID_KEY) ?: 0L
c: 매번 get해올 필요없이 처음에 받아오면 캐싱해두고 계속 사용하면 더 좋을 것 같아요

2024-10-16 06:14 UTC, librarywon approved these changes
고생하셨습니다!! 깔끔하네요

2024-10-16 06:14 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
> +        val userId = arguments?.getLong(USER_ID_KEY) ?: 0L
이미 레포지토리에 들어있을겁니다.

2024-10-22 09:36 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
> +        val userId = arguments?.getLong(USER_ID_KEY) ?: 0L
레포지터리에 들어있는 유저 아이디는 '나'의 유저아이디 아닌가욤?

2024-10-24 07:13 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +        submitList(currentList)
반영하겠습니다!!

2024-10-24 07:13 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
> +    BaseFragment<FragmentMyActivityBinding>(R.layout.fragment_my_activity),ActivityItemClickListener {
최근 올라온 피알에서 반영했습니다!!

2024-10-24 14:36 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +                        activityDetailAdapter.userProfile = myProfile.toUserProfileModel()
r: 추후에 객지사에서도 얘기하겠지만, 다른 객체의 상태를 직접수정하는 일은 없어야합니다! 
객체의 상태를 업데이트 해달라는 '메시지'를 보내는 것, 그것을 위해 만들어진게 submitList입니다.

2024-10-24 14:36 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myActivity/MyActivityFragment.kt
> +                myActivityAdapter.notifyDataSetChanged()
r: submitList로 통일바랍니다!

2024-10-24 14:36 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserActivity/adapter/OtherUserActivityAdapter.kt
> +            val activityModels = UserActivityModel(getItem(position), userProfile)
c: 외부에서 생성해서 넘겨주란 뜻이었습니다!

2024-10-30 05:40 UTC, s9hn approved these changes
굿!

2024-10-30 05:40 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        if (activities != null && userProfile != null) {
a: 무조건 둘다 널이 아닌가요?

2024-10-30 14:42 UTC, merged