feat: 다른유저활동, 활동디테일 기능 구현
Team-WSS/WSS-Android pull request #411
Opened 2024-10-15 20:19 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #236 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 다른유저활동: 좋아요반영, 피드디테일 이동, 노벨디테일 이동
- 활동디테일: 좋아요반영, 피드디테일 이동, 노벨디테일 이동

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
[Screen_recording_20241016_051847.webm](https://github.com/user-attachments/assets/88046c2e-018a-4499-8565-0b4827d128ee)

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
시간되실 때 리뷰 천천히 해주세용:) 항상 감사함둥(꾸벅)

2024-10-16 03:28 UTC, s9hn requested changes

2024-10-16 03:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    ActivityItemClickListener {
r: 액티비티가 클릭리스너를 구현할 필요가 있나요?

2024-10-16 03:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +            val activityModels = UserActivityModel(getItem(position), userProfile)
r:onBindViewHolder는 스크롤할때마다(새로운아이템이 노출될때마다) 매번 호출됩니다.
dataClass의 객체 생성 비용은 굉장히 큰편인데, 지금은 엄청나게 많은 인스턴스들을 생성하고 있어요. 외부에서 모델링을 진행하고 넘겨주세요

2024-10-16 03:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +        submitList(currentList)
r: 마찬가지로 외부에서 submitList 하는 구조로 바꿔주세요

2024-10-16 06:11 UTC, librarywon requested changes
수고하셨습니다 리뷰 확인해주세요!

2024-10-16 06:11 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +    ActivityItemClickListener {
명지 세훈 코드를 참고하세요

2024-10-16 06:11 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        val likeCountTextView: TextView = view.findViewById(R.id.tv_my_activity_thumb_up_count)
r: `findViewById`???? 이거 꼭 써야하나요?

2024-10-16 08:26 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        val likeCountTextView: TextView = view.findViewById(R.id.tv_my_activity_thumb_up_count)
뷰홀더에 있는 뷰ID를 참조해야해서 씁니다!

2024-10-24 07:12 UTC, librarywon approved these changes
리뷰 반영하느라 고생하셨습니다!

2024-10-24 07:15 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +        submitList(currentList)
이전 피알에서 반영했습니다!

2024-10-24 14:41 UTC, s9hn reviewed
첫번째 피알이랑 리뷰내용이 전부 비슷한데
1. submitList를 통해 뷰(Activity, Fragment)에서 어댑터로 데이터를 넘겨줄 것
2. 어댑터의 상태를 외부에서 직접 설정하는 것이 아닌 submitList로 넘겨줄 것
3. submitList로 넘겨줄 때, 필요한 모델객체를 생성 후 넘겨줄 것

2024-10-24 14:41 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/ActivityDetailActivity.kt
> +        activityDetailViewModel.updateActivityLike(view.isSelected, feedId, updatedLikeCount)
r: 제 코드에 있는데 디바운스 적용해줘야함미당

2024-10-24 14:41 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/activityDetail/adapter/ActivityDetailAdapter.kt
> +            val activityModels = UserActivityModel(getItem(position), userProfile)
이거 반영이 되어있나요?

2024-10-30 18:03 UTC, s9hn approved these changes

2024-10-30 18:04 UTC, merged