feat: 마이페이지 3차 QA 대응
Team-WSS/WSS-Android pull request #418
Opened 2024-11-02 16:36 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #401 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 작품취향 키워드 클릭 막아두기
- 보관함 정렬 선택 버튼 텍스트까지 범위 넓히기
- 읽기상태 변경시 보관함 카운트 반영
- 소개글 50자 정렬
- 작품취향 소재 빠진 키워드 추가

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/1c2f5bd4-ee5b-462f-992b-e92167c80f38

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
보관함/내서재 onResume에 넣어 놓은 건 계속 고민을 해보겠습니다..! 다른 분들 코드 참고해서 ActivityResultLauncher<Intent> 이용해서 해봤는데 잘 안되서 임시방편(?)으로 onResume에 넣어서 피알 올립니다,,,,

2024-11-03 10:40 UTC, librarywon requested changes
onResume만 잘 수정해봅시다! 고생하셨어요!

2024-11-03 10:40 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
> +    }
r: 이거 저나 산군 붙잡고 같이 해보면 될 것 같아요

2024-11-03 14:22 UTC, m6z1 approved these changes
잔디냠냠

2024-11-03 14:22 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
> +    fun loadMyLibrary(){
c: updateMyLibrary ? 는 어때욥

2024-11-14 06:46 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
> +    fun loadMyLibrary(){
좋아용!

2024-11-14 07:40 UTC, librarywon approved these changes
고생 많으셨습니다! 최적화를 성공적으로 이루어 내셨군요!

2024-11-14 07:40 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/userStorage/UserStorageViewModel.kt
> +
r: 빈줄 삭제 플리즈

2024-11-14 07:40 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
> +            myLibraryViewModel.updateMyLibrary() // 변경사항 반영을 위해 데이터 갱신
r: 주석도 삭제해주세요

2024-11-14 07:58 UTC, merged