feat: 소셜로그인 및 토큰 관리 로직 구현
Team-WSS/WSS-Android pull request #421
Opened 2024-11-12 18:25 UTC by librarywon

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #39 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯

### 먼저 PR단위가 커지게 된 것에 대해 사과의 말씀 드립니다 _(솔직히 소셜로그인은 인정아닌가?)_

### 본격적인 코드리뷰 이전 2가지 권장 사항
1. 반드시 **로컬 프로퍼티를 최신화하고 직접 프로젝트를 실행** 해본다.
2. 이전에 제공해드린 **토큰 관리 로직 그림**을 참고하며 코드를 확인한다.

### 비회원 유저 로직  구현
1. 회원가입 없이 둘러보기 선택
2. `MainActivity`로 `Intent`를 통해서 `isLogin`을 `false`으로 넘겨준다 (디폴트는 true)
3. `MainActivity` 전체를 덮고 있는 `v_main_guest` 뷰를 Visible 시켜 어떤 화면을 터치해도 로그인 유도 모달이 나오도록 처리

### 회원 로직 구현
0. 카카오 sdk를 통해 `OAuth AccessToken`을 받는다. 서버 로그인/회원가입 api에 `OAuth AccessToken`을 주어 `JWT AccessToken과 refreshToken`을 받는다.

1. 카카오 로그인시 가입된 유저라면? -> `JWT AccessToken과 refreshToken`를 로컬에 저장하고 자동로그인 변수 또한 true로 변경해준다.

2. 카카오 로그인시 가입되지 않은 유저라면 -> `JWT AccessToken과 refreshToken`를 `OnboardingActivity`를 `Intent`로 넘겨 최종 회원가입에 성공한다면 로컬에 토큰을 저장한다.

### Autenticator
1. Autenticator가 `response.code == 401`를 감지한다
2. `AccessToken`이 만료되었거나 혹은 유효하지 않은 토큰이라는 뜻이기 때문에 `refreshToken`을 통해 재발급을 시도한다.
3. 재발급이 성공적으로 이루어졌다면 ? -> 새로 발급 받은 AccessToken을 사용한다
4. 재발급이 실패했다면 ? -> 무언가 잘못된 상황이기 때문에 `LoginActivity`로 쫒아내고 토큰을 모두 날려버린다.

### @Secured 와 @Unsecured의 차이
- 헤더 토큰의 유무입니다.  `AuthApi` 에는 헤더 `Authorization`가 없이 작동하는 api들이 있기 때문에  `@Unsecured`입니다. (당연히 처음 카카오톡 소셜로그인으로 가입하면 헤더 토큰이 없겠죠?)
- `AuthApi`에 들어있지만 헤더 토큰이 필요한 친구들은 `@Header`를 통해서 헤더 토큰을 넣어주고 있습니다.

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
### 게스트 로그인
https://github.com/user-attachments/assets/ee4b24a2-7e0a-40d2-a165-16f1fda33362

### 유저 로그인
https://github.com/user-attachments/assets/d7683ef9-697d-4bbd-9717-591c891f1338

### 유저 로그아웃
https://github.com/user-attachments/assets/4451077a-a917-482d-b4d2-5c2b33991a14

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-11-13 06:43 UTC, junseo511 approved these changes
삼성티엠

2024-11-13 06:43 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/main/MainViewModel.kt
> +        this._isLogin.value = isLogin
c: 이 this 없어도 되는거 아닌가요?

2024-11-13 06:43 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/splash/SplashViewModel.kt
> +import android.util.Log
c: 이거 쓰고계신가용?

2024-11-13 06:43 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/withdraw/second/WithdrawSecondViewModel.kt
> +                }?:""
r: 포맷팅

2024-11-13 06:43 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +        .build()
```suggestion
@Provides
@Singleton
@Secured
fun provideSecuredOkHttpClient(
    @Log logInterceptor: Interceptor,
    @Auth authInterceptor: Interceptor,
    websosoAuthenticator: WebsosoAuthenticator
): OkHttpClient = createOkHttpClientBuilder(logInterceptor)
    .addInterceptor(authInterceptor)
    .authenticator(websosoAuthenticator)
    .build()

@Provides
@Singleton
@Unsecured
fun provideUnsecuredOkHttpClient(
    @Log logInterceptor: Interceptor
): OkHttpClient = createOkHttpClientBuilder(logInterceptor).build()

private fun createOkHttpClientBuilder(logInterceptor: Interceptor): OkHttpClient.Builder {
    return OkHttpClient.Builder()
        .addInterceptor(logInterceptor)
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(15, TimeUnit.SECONDS)
}
```

2024-11-13 06:54 UTC, s9hn requested changes
개인적으로 데이터스토어는 UDF를 구축하기에 아주 좋은 저장소입니다. 그래서 suspend 함수들만 지원한다고 생각해유
suspend함수는 리턴값으로 이용하기 적절치 않으니, 구독-발행 패턴이 좀 더 적절해보입니다. 
단순히 키값을 사용하는 용도로는 쉐어드프리퍼런스도 나쁘지 않다고 생각함다.
뷰에서 로직은 최대한 덜어내고 카카오sdk 사용은 뷰모델에서 콜백으로 소통해도 좋을 것 같아요

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/authenticator/WebsosoAuthenticator.kt
> +                    authRepository.reissueToken()
r: api통신이 5초가 걸린다면 .. ?

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/qualifier/Auth.kt
> +@Retention(AnnotationRetention.BINARY)
a: 왜 바이너리로 설정했나요

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/repository/AuthRepository.kt
> +        runCatching {
c: 런캐칭도 한곳에서 하면 좋을듯!

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
>      private lateinit var runnable: Runnable
c: 나중에 리팩터링하면 좋겠네요

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
> +                    kakaoAuthService.login()
c: 뷰모델의 콜백을 로그인에게 주는것은 어떠한지요?
그럼 콜백을 통해 뷰모델 프로퍼티를 업데이트하고, 그것을 관찰하는 옵저버가 아래 로직을 실행하는 ,,

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginViewModel.kt
> +import android.util.Log
r: 로그 컷

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
> +        val isLogin = intent.getBooleanExtra(IS_LOGIN_KEY, true)
c: 뷰모델에서 관리하고, 옵저버가 isLogin, isLogin.not() 일때로 분기 로직 구현하면 훨 꺨꼼~할듯

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/MainViewModel.kt
> +
r: 아하 여기 있었군요. 파라미터로 넘겨주지말고 인텐트자체를 savedStateHandler로 받아보시죵

2024-11-13 06:54 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/splash/SplashActivity.kt
> +            joinAll(autoLoginJob, delayJob)
r: 뷰모델 함수가 어차피 새로운 코루틴을 만들고 있어서 여기서 굳이 코루틴을 만들 필요가 없을 것 같아용

2024-11-13 07:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/authenticator/WebsosoAuthenticator.kt
> +                    authRepository.reissueToken()
이거 생각 못했는데 개쩌는듯

2024-11-13 07:08 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +        .build()
감사합니다 이건 쪼끔만 고민해볼게요!

2024-11-13 07:36 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
> +                    kakaoAuthService.login()
아 일단은 현상을 유지하고 더 좋은 로직이 생각나면 변경하겠습니다!

2024-11-13 10:09 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/authenticator/WebsosoAuthenticator.kt
> +                    authRepository.reissueToken()
이거 knownIssue로 남겨두겠습니다.

2024-11-13 10:53 UTC, m6z1 approved these changes
카카오 로그인 구현을 처음봐서 질문이 많네요 😅
플로우로 미리 보여주셔서 이해가 쉬웠어요 고생하셨습니다 👍

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/authenticator/WebsosoAuthenticator.kt
> +    @ApplicationContext private val context: Context,
c: 이 Authenticator에서 context를 사용하지 않고 구현할 수 있는 다른 방법은 없나요 ? android 의존성을 데이터가 가지고 있으니 어색한 것 같아요

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +    @Log
a: 요 Log 어노테이션은 어떤 역할인지 궁금해요!

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +        websosoAuthenticator: WebsosoAuthenticator
r: 트레일링 콤마

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +        @Log logInterceptor: Interceptor
r: 여기두 트콤

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/OAuthModule.kt
> +    }
a: 바인드 메서드를 인스턴스 클래스로 묶으신 이유가 무엇인지 궁금합니다

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/SecureStorageModule.kt
> +    private fun deleteExistingPref(fileName: String, context: Context) {
c: Pref 줄이지말고 Preferences로 쓰는 거 어떤가요 ?

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/SecureStorageModule.kt
> +            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
r: 여기도 트콤

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/remote/api/AuthApi.kt
> +    )
c: 이 친구들은 인증 레포지토리가 아니라 사용자 레포지토리에 들어가야 하는 게 아닌지 궁금합니다. 엔드포인트 자체도 `users` 로 시작하는데 authRepository에 넣으신 이유가 궁금해요!

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/remote/api/KakaoAuthService.kt
> +    override suspend fun login(): OAuthToken = suspendCancellableCoroutine {
a: 스타일일 수 있겠지만 한 줄에 끝나지 않는 함수는 { } 중괄호를 사용하시는 건 어떤가요?

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/accountInfo/LogoutDialogFragment.kt
> +                startActivity(LoginActivity.getIntent(requireContext()))
a: 요거 뷰 스택 안 날려도 되나요 ?

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
> +                                    state.refreshToken
r: 트콤!

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginActivity.kt
> +                }.onFailure { error ->
r: 안 쓰이는 건 제거! (error)

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginViewModel.kt
> +    val loginUiState: LiveData<LoginUiState> = _loginUiState
c:
```suggestion
    val loginUiState: LiveData<LoginUiState> get() = _loginUiState
```

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/login/model/LoginUiState.kt
> +    data object Loading: LoginUiState()
r: 포맷팅

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
> +                    mainViewModel.mainUiState.value?.nickname
r: 트레일링 콤마

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/home/HomeViewModel.kt
> +                    popularFeeds = popularFeeds.popularFeeds.chunked(3)
r: 트콤

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingActivity.kt
> +
c: 함수 분리 어때욥?

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
> +    fun setTokens(accessToken: String, refreshToken: String) {
c: 우리 뷰모델에서 사용하는 건 `updateXXX` 로 쓰기로 했어욥

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/splash/SplashActivity.kt
> +    private fun setObserver() {
r:
```suggestion
    private fun setupObserver() {
```

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/splash/SplashViewModel.kt
> +    val isAutoLoginSuccess: LiveData<Boolean> = _isAutoLoginSuccess
c: 
```suggestion
    val isAutoLoginSuccess: LiveData<Boolean> get() = _isAutoLoginSuccess
```

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/splash/SplashViewModel.kt
> +    fun autoLogin() {
c: 얘도 자동로그인 확인해서 값을 업데이트 하는 거니까 updateXXX로 사용하면 좋을 것 같아요

2024-11-13 10:53 UTC, m6z1 commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/v_main_guest"
r: 뷰는 `view_xxx_ `가 컨벤션!

2024-11-13 10:57 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/authenticator/WebsosoAuthenticator.kt
> +    @ApplicationContext private val context: Context,
401이 발생 -> 토큰 재발급 -> 재발급 실패시 로그인으로 돌아가는 기능 때문에 필요한건데 콜백을 만들어서 대응하려고 시도해봤는데 어렵더라구요 어떤 방법이 있을까요? 포포리 같은 경우도 그냥 의존성을 받고 있긴한데

2024-11-13 10:58 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/OAuthModule.kt
> +    }
OAuthService의 구현체인 KakaoAuthService 바인드하기 위해서는 저렇게 작성하는 것말고 다르게 작성하는 방법이 있나요?

2024-11-13 10:58 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/SecureStorageModule.kt
> +    private fun deleteExistingPref(fileName: String, context: Context) {
좋습니다.

2024-11-13 11:01 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/remote/api/AuthApi.kt
> +    )
`getNicknameValidity`, `postUserProfile` 둘다 가입 전에 사용되는 로직이라 아직 헤더 있는 인터셉터를 사용하지 않습니다.
그리고 가입과 관련된 친구들을 모아두고 싶어서 auth에 두고 관리하였습니다.

2024-11-13 11:02 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginViewModel.kt
> +    val loginUiState: LiveData<LoginUiState> = _loginUiState
혹시 근데 이거 왜 쓰는지 정확한 이유가 뭐였죠?

2024-11-13 11:03 UTC, librarywon commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/v_main_guest"
확인입니다.

2024-11-13 11:05 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +    @Log
제가 인터셉터를 구분짓기 위해 지은 이름입니다 인증용이 아니고 로그용!

2024-11-13 11:08 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/qualifier/Auth.kt
> +@Retention(AnnotationRetention.BINARY)
솔직히 모르겠습니다

2024-11-13 11:12 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/accountInfo/LogoutDialogFragment.kt
> +                startActivity(LoginActivity.getIntent(requireContext()))
LoginActivity `getIntent` 팩토리 메서드를 보시면 스택을 다 날리고 있습니다.

```
  fun getIntent(context: Context): Intent {
            return Intent(context, LoginActivity::class.java).apply {
                flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
            }
        }
```

2024-11-13 11:16 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingActivity.kt
> +
intent를 받아서 넘겨야해서 `onCreate`에 두는 것이 좋을 것 같습니다!

2024-11-13 11:19 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/splash/SplashViewModel.kt
> +    fun autoLogin() {
자동로그인을 실행하는 함수라고 생각하여 지금 네이밍을 지었고

updateXXX를 사용하려면 `updateIsAutoLoginSuccess`라는 이름을 가질 수 있겠는데 호감이 가는 이름은 아닌 것 같군요

2024-11-13 11:33 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/authenticator/WebsosoAuthenticator.kt
> +    @ApplicationContext private val context: Context,
어렵네요 ... ^..^ 그냥 현행유지 하시죠

2024-11-13 11:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/di/OAuthModule.kt
> +    }
진짜 몰라서 여쭤봤습니다 확인이요

2024-11-13 11:40 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/remote/api/AuthApi.kt
> +    )
`getNicknameValidity` 같은 경우에는 프로필 수정 화면에서도 사용되지 않나요 ? 가입과는 상관없는 친구라 생각하는데 어떻게 생각하시는지 궁금해요

2024-11-13 11:50 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/login/LoginViewModel.kt
> +    val loginUiState: LiveData<LoginUiState> = _loginUiState
암묵적인 컨벤션?처럼 모두 get()을 사용하고 있기도 하고 직접 참조하는 거랑 get() 해서 참조하는 거랑 다륵다고 하네여 ? 
[관련블로그](https://velog.io/@haanbink/Kotlin-Backing-Properties)

2024-11-13 14:15 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/remote/api/AuthApi.kt
> +    )
UserApi 에 옮기게 되면 토큰을 사용하는 인터셉터를 이용해야하는데 그러면 토큰이 없어서 401처리를 따로 해줘야합니다 좀 머리가 복잡해져서요 크게 문제가 안된다면 그냥 두고 싶어요

2024-11-13 15:35 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +    @Log
logging이란 이름도 괜찮을것같아요

2024-11-13 15:37 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/remote/api/KakaoAuthService.kt
> +    override suspend fun login(): OAuthToken = suspendCancellableCoroutine {
저는 반환타입이 있고 리턴전에 로직이 필요하지 않을때 = 써주는편

2024-11-13 15:38 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingActivity.kt
> +
두 intent를 by lazy로 빼도 괜찮을 것 같아요 아니면 이것도 savedStateHandler써도됨

2024-11-14 04:06 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/NetworkModule.kt
> +    @Log
`Log.d`랑 겹쳐서 logging으로 수정하는 것도 좋아보이네요

2024-11-14 05:58 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/qualifier/Auth.kt
> +@Retention(AnnotationRetention.BINARY)
알아보니 BINARY로 설정하면 컴파일된 바이트코드에 어노테이션 정보가 남지만 런타임에는 사용할 수 없다고합니다. 
런타임에 어노테이션  정보를 필요로 하지 않을 때 사용합니다

2024-11-14 11:30 UTC, s9hn approved these changes
고생하셨씀다~!

2024-11-14 11:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/di/SecureStorageModule.kt
> +            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
a: EncryptedSharedPreferences는 안드로이드에서 deprecated된것으로 알고 있어요. 잔버그가 많은친구라.
관련해서 직접 암호화모듈을 만드는것도 좋아보여요 :) 노운이슈로 남겨두시고 담당자는 추후에 논의해보죠

2024-11-14 11:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/login/model/LoginUiState.kt
> +
r: 토큰이 UiState에 담길일이 있을까요? UI상태값은 아닌것 같아요

2024-11-14 11:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
> +        set(value) { savedStateHandle[REFRESH_TOKEN_KEY] = value }
c: 커스텀 세터앞에도 가시성제어자가 붙나요

2024-11-14 11:30 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/splash/SplashViewModel.kt
> +    fun autoLogin() {
a: 굳이 Success인것까지 밝힐 필요는 없어요! 타입이 Boolean하니까요

2024-11-14 11:33 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/data/di/SecureStorageModule.kt
> +            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
#427  deprecated된건 모르던 사실이군요 이슈를 파서 담당자가 대응할 수 있도록 조치하겠습니다.

2024-11-14 11:34 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/login/model/LoginUiState.kt
> +
인정합니다!

2024-11-14 11:53 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
> +        set(value) { savedStateHandle[REFRESH_TOKEN_KEY] = value }
네 알아보니 붙일 수 있습니다! private을 붙이도록 하겠습니다.

2024-11-14 12:11 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/onboarding/OnboardingViewModel.kt
> +        set(value) { savedStateHandle[REFRESH_TOKEN_KEY] = value }
객체만이 본인의 상태를 업데이트 할 수 있도록 수정하였습니다.

2024-11-14 12:33 UTC, merged