feat: 내 서재/ 다른유저 서재에 따른 보관함 조회 분기처리 구현
Team-WSS/WSS-Android pull request #422
Opened 2024-11-12 20:02 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #419 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 내 서재/ 다른유저 서재 경로에 따른 보관함 조회 분기처리 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/40073ac7-2971-40a6-bebd-80b7a386fe7b

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-11-13 03:16 UTC, librarywon requested changes
고생하셨습니다! 리뷰 확인해주세요!

2024-11-13 03:16 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
> +    var userId: Long = -1
c: 외부에서 참조를 해서 가시성이 변경된걸까요?

2024-11-13 03:16 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/otherUserPage/otherUserLibrary/OtherUserLibraryFragment.kt
> +        }
r: 스로틀을 넣어서 한 번만 클릭되도록 만들어주세요

2024-11-13 11:15 UTC, m6z1 approved these changes
샐리 빠이팅🔥

2024-11-13 11:15 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryFragment.kt
> +            startActivity(
c: 요기두 쓰로틀 ?

2024-11-14 08:41 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
> +    var userId: Long = -1
네넵 레포지터리에서 가져오고 있어서 그렇게 했는데 문제가 될까요?

2024-11-14 09:05 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/main/myPage/myLibrary/MyLibraryViewModel.kt
> +    var userId: Long = -1
뷰모델에 있는 변수를 레포지터리에서 가져다 쓴다구요?

2024-11-14 09:09 UTC, librarywon approved these changes
수고하셨습니다!

2024-11-14 09:28 UTC, merged