feat: 최소버전 강제 업데이트 구현
Team-WSS/WSS-Android pull request #491
Opened 2024-12-17 18:21 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #478

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 최소버전 강제 업데이트 팝업 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/user-attachments/assets/ee49f019-95a9-4ab0-ae73-0acecdab8f02

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
위에 시현영상은 최소버전이 10.0.0이라고 가정하고 테스트해서 나온 모습입니당..!

2024-12-18 03:14 UTC, m6z1 approved these changes
빠른 작업 감사함니다 👍  체고
전체적으로 함수 전에 개행 안 된 부분 개행 시켜주시면 감사함니다 ( _ _

2024-12-18 03:14 UTC, m6z1 commented on app/src/main/java/com/into/websoso/data/remote/api/VersionApi.kt
> +        @Query("os") os: String = "android",
c: 이 android 란 값을 repository 에서 전달해주면 좋을 것 같아용!!

2024-12-18 03:14 UTC, m6z1 commented on app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
> +        dialog.show(parentFragmentManager, "MinimumVersionDialog")
c: tag 값 상수화 해주기 ?.?

2024-12-18 03:14 UTC, m6z1 commented on app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
> +        val currentParts = currentVersion.split(".").map { it.toIntOrNull() ?: 0 }
c: 현재의 파트 ?.? 라는 변수명이 살짝 어색한 것 같아용
`currentVersionParts` 혹은 `currentVersionNumbers` 요런 식으로 버전에 대한 값임을 명시해주면 좋을 것 같습니당

2024-12-18 03:14 UTC, m6z1 commented on app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
> +        val minParts = minVersion.split(".").map { it.toIntOrNull() ?: 0 }
c: 여기두 마찬가지!

2024-12-18 03:14 UTC, m6z1 commented on app/src/main/res/values/strings.xml
> +    <string name="minimum_version_popup_menu_url">https://play.google.com/store/apps/details?id=com.into.websoso</string>
r: 요 url은 deeplinks.xml 파일로 옮기면 좋을 것 같슴당!!

2024-12-18 06:01 UTC, librarywon requested changes
고생하셨습니다 반영해주셨음 하는 부분을 남겨두었으니 언제든 질문주세요!

2024-12-18 06:01 UTC, librarywon commented on app/src/main/java/com/into/websoso/data/repository/VersionRepository.kt
> +        return versionApi.getMinimumVersion(os = "android").toData()
r: 여기서 이미 기본 값으로 넣어주고 있는데 위 DTO 기본값으로 넣으셨군요 기본값을 제거하시면 좋을 것 같습니다.

2024-12-18 06:01 UTC, librarywon commented on app/src/main/java/com/into/websoso/data/model/MinimumVersionEntity.kt
> +    val updateDate: String,
r: 클라이언트에서 `updateDate`를 받을 필요가 있나요? 필요하지 않다면 불필요한 데이터까지 모델에 받아오는건 좋지 않다고 생각합니다. 필요한 데이터만 Entitiy에 추가해서 맵핑해서 사용합시다

2024-12-18 06:01 UTC, librarywon commented on app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
> +        }
r: 일단 Observe를 하지 않는데  `setupObserver()` 안에 이 로직이 들어있는 것이 이상합니다 그리고 `updateMinimumVersion`함수호출을 Fragment에서 안해도 될 것 같습니다 어차피 한 번만 검사한다면 ViewModel에서 init으로 한번만 해주고 `isRequiredUpdate`같은 변수를 옵저빙하면 될 것 같아요.
근데 그렇게되면 불필요하게 `HomeVIewModel`이 재생성 될 때마다 버전 체크를 진행할 우려가 있습니다. 그렇게다면 앱을 켰을 때 딱 한 번 들어가는 뷰에서 검사하면 좋겠죠?

2024-12-18 06:01 UTC, librarywon commented on app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
> +        val currentParts = currentVersion.split(".").map { it.toIntOrNull() ?: 0 }
c: 이런 불필요한 작업을 피하기 위해서 `VERSION_NAME`말고 `VERSION_CODE`를 쓰는 방법이 있습니다.

2024-12-18 06:01 UTC, librarywon commented on app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
> +        val currentParts = currentVersion.split(".").map { it.toIntOrNull() ?: 0 }
예를 들어 10001 (1.0.1) > 10000(1.0.0) 이기 때문에 대소 비교만하면 됩니다.

2024-12-18 06:06 UTC, librarywon commented on app/src/main/java/com/into/websoso/data/repository/VersionRepository.kt
> +        return versionApi.getMinimumVersion(os = "android").toData()
추가로 상수화도 해주세요

2024-12-18 06:56 UTC, junseo511 reviewed
작은 의견을 남겨보았습니다!!

2024-12-18 06:56 UTC, junseo511 commented on app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
> +                    versionRepository.fetchMinimumVersion().minimumVersion,
c: 저는 애초에 UI에서 버전 네임을 알아야 하는 이유에 대한 의문입니다...! 버전을 출력해주는 기능이 있는게 아니라면요!!

2024-12-18 06:56 UTC, junseo511 commented on app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
> +        val currentParts = currentVersion.split(".").map { it.toIntOrNull() ?: 0 }
c: 그래서 이 로직이 UI가 아닌 다른 레이어에 있어야 할 것 같다는 생각...? 어떻게 생각하시는지요 ?.?

2024-12-18 07:52 UTC, librarywon commented on app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
> +                    versionRepository.fetchMinimumVersion().minimumVersion,
매우동의합니다

2024-12-20 08:55 UTC, librarywon commented on app/src/main/java/com/into/websoso/ui/main/home/HomeViewModel.kt
> +        val currentParts = currentVersion.split(".").map { it.toIntOrNull() ?: 0 }
data에 있어야한다고 생각합니다.

2024-12-25 03:03 UTC, yeonjeen commented on app/src/main/java/com/into/websoso/ui/main/home/HomeFragment.kt
> +        }
스플래쉬에서 진행하겠습니다!

2024-12-25 13:48 UTC, librarywon approved these changes
크리스마스까지 너무 고생 많으셨습니다 또 구현도 너무 감사해요

메리 크리스마스 샐리🎄

2024-12-26 01:15 UTC, merged