feat: 일반 탐색 뷰 구현 및 더미데이터 연결
Team-WSS/WSS-Android pull request #64
Opened 2024-06-25 08:31 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #23 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 일반 탐색 뷰 구현했습니다.
- 레포지토리 패턴 이용해서 더미데이터 연결했습니다.
- 2달도 전에 작업하고 있던 부분이라 놓친 부분이 많을 수 있고, PR 권장 줄 컨벤션 맞추지 못한 점 매우 죄송함다 ㅠ.ㅠ
- 처음에 `ListAdapter`를 사용하고 있었는데, `RecyclerViewAdapter`로 수정했습니다.
> 그 이유 검색 버튼을 눌렀을 때 viewModel 에서 레포지토리로 dummyData를 가져옴 -> `activity` 단에서 uiState를 observe 하는 것까지 확인 -> `submitList`로 uiState에서 옵저빙한 값을 넣어주는 것까지 확인했으나, 뷰에 리사이클러뷰가 보이지 않음 ㅜ.ㅠ DiffCallback 부분에 디버깅 해보니까 이 부분이 문제인 것 같은데 좀 더 공부하고, 안드소소에게 알아내서 **다른 이슈파서 마이그레이션 할 예정**

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/Team-WSS/WSS-Android/assets/114990782/d7c5b721-3b0f-434e-a6d3-5f11246ea1dd

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
- 헷 따끔하게 혼내주십셔

2024-06-25 08:51 UTC, s9hn requested changes
MTGL

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +        onClickNovelSearchButton()
r: 컨벤션 상 onXXXClick() 이지않았나용?

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +        setupObserveUiState()
r: verb+verb+noun

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +            val intent = NormalExploreActivity.from(requireContext())
r: 이것도 한번 얘기나눠야겠군요

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +            binding.etNormalExploreSearchContent.text.clear()
c: 해당 editText는 양방향 데이터바인딩을 적용하지 않나요?

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.etNormalExploreSearchContent.requestFocus()
what is it(=requestFocus())?

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.rvNormalExploreResult.setHasFixedSize(true)
what is it?

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
> +    fun fetchNormalExploreResult() {
update 어떤가요?

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
> +) : RecyclerView.Adapter<NormalExploreViewHolder>() {
액티비티에서 submitList해주는 코드 바로 이전까지 로그 찍어보셨나요?

2024-06-25 08:51 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreUiState.kt
> +    val novelCount: Long = 0,
novels.count와 다른 친구인가요?

2024-06-25 08:51 UTC, s9hn commented on app/src/main/res/layout/item_normal_explore.xml
> +            name="novelItemClickListener"
c: 얘가 오히려 onClick이란 이름과 더 어울릴것 같아요!

2024-06-25 08:51 UTC, s9hn commented on app/src/main/res/layout/item_normal_explore.xml
> +            android:text='@{String.format("%.1f", novel.rating) + " (" + novel.ratingCount + ")"}'
c: string리소스에 %연산자 활용해서 novel.rating과 novel.ratingCount만 전달하는 방법은 어떤가요?

2024-06-25 09:12 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/main/explore/ExploreFragment.kt
> +            val intent = NormalExploreActivity.from(requireContext())
수욜에 같이 얘기나누면 될 듯욥!

2024-06-25 09:14 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +            binding.etNormalExploreSearchContent.text.clear()
넴 반영했습니다. 
양방향 데이터를 사용해서editText의 text값을 비울 수 있나요??
지금 생각나는 건 뷰모델에 텍스트값 비우는 로직 만들어서 뷰모델 이벤트 호출?... 모르겠어요

2024-06-25 09:23 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.etNormalExploreSearchContent.requestFocus()
홈 (탐색) 뷰에서 검색 바 눌러서 액티비티 진입하자마자 포커스 줘서 키보드 올리게 한 건데...... 잘못 알고 있나여?

2024-06-25 09:28 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.rvNormalExploreResult.setHasFixedSize(true)
리사이클러뷰의 크기가 동적으로 변하는지 아닌지 명시해주는 역할인데 저 같은 경우에는 검색 결과에 따라서 매우 동적으로 변하니 false가 되것죠?
True가 되면 안 되는데 너무 습관처럼 true로 설정해버린

2024-06-25 09:29 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
> +) : RecyclerView.Adapter<NormalExploreViewHolder>() {
넵 ㅜ 다 해봤슴다

2024-06-25 09:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +            binding.etNormalExploreSearchContent.text.clear()
엇.. 무엇을 반영한거죠?
editText는 양방향 데이터바인딩을 사용하고 있다는 가정하에, 해당 editText와 바인딩되어있는 livedata를 비워주면 될 것 같습니다.

2024-06-25 09:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.rvNormalExploreResult.setHasFixedSize(true)
?
그냥 무슨코드인지 개념물어본거였는데 ㅋㅋ 오히려 좋네요 굿

2024-06-25 09:34 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
> +) : RecyclerView.Adapter<NormalExploreViewHolder>() {
로그찍어봤을 때 데이터 변화가 감지되고 리스트 변경사항이 있던가요?

2024-06-25 09:34 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
> +    fun fetchNormalExploreResult() {
전 fatch 조은데여....
라고 할랬는데 서버에서 데이터 불러올 때 prefix 컨벤션에서 fetch를 쓰는 이유는 그냥 데이터를 "가져온다"는 의미에서 쓴 거고 뷰모델에서는 결과물을 항상 가져온다보단 검색어에 의해 결과물 업데이트한다라는 게 더 맞겠네요 반영합니다 ~

2024-06-25 09:45 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.etNormalExploreSearchContent.requestFocus()
이건 진짜 무슨함수인지 몰라서 물어본거였씁니다 굿 
근데 한줄이면 굳이 함수분리안해도될듯

2024-06-25 09:45 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
> +    fun fetchNormalExploreResult() {
제 생각과 정확히 일치합니다 굿

2024-06-26 00:30 UTC, junseo511 approved these changes
고생하셨슴다~~👍 근데 초기에 xml 그리다보면 코드 줄 훌쩍 넘어가는거 어쩔 수 없는거같아요 ㅠ

2024-06-26 00:30 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.onClick = onClickNormalExploreButton()
c: 뷰모델을 바인드하는 부분에 포함되나요?

2024-06-26 00:30 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +                uiState.error -> throw IllegalStateException()
저희 근데 웬만해서는 안튕기게 한다고 하지 않았나여?

2024-06-26 00:30 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
> +) : RecyclerView.Adapter<NormalExploreViewHolder>() {
저도 비슷한 이슈가 있었는데 변화가 감지가 안되었더라구요...🥲

2024-06-26 02:11 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +                uiState.error -> throw IllegalStateException()
아직 에러 처리 제대로 안 정해서 IllegalState 예외 날려주고 있슴니다 ~

2024-06-26 02:13 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
> +) : RecyclerView.Adapter<NormalExploreViewHolder>() {
@s9hn 넵 uiState 옵저빙하는 것도 잘 되고, adapter에서 submitList 메서드 단에서도 로그 찍어봤는데 잘 들어오더라구요 ㅠ 근데 DiffCallback 쪽에서 로그가 안 찍혀서 이것 문제인 것 같아요

2024-06-26 02:19 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreUiState.kt
> +    val novelCount: Long = 0,
`novels.count`로 사용하면 되긴 하겠지만 서버에서 `resultCount` 로 내려줘서 uiState에서 사용했슴다!

2024-06-26 02:29 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.onClick = onClickNormalExploreButton()
조은 피드백 👍

2024-06-26 04:00 UTC, yeonjeen approved these changes
수고많으셨습니당!! 역시 짱짱띵지👍🏻

2024-06-26 04:00 UTC, yeonjeen commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +            finish()
```suggestion
            override fun onBackButtonClick() = finish()
```
c: 이렇게 작성할 수도 있지 않을까요?

2024-06-26 04:00 UTC, yeonjeen commented on app/src/main/res/layout/activity_normal_explore.xml
> +            android:background="?attr/selectableItemBackgroundBorderless"
a:  attr은 뭔가용?

2024-06-26 04:00 UTC, yeonjeen commented on app/src/main/res/layout/activity_normal_explore.xml
> +            android:visibility="visible"
a: 따로 visibility를 visible 처리하신 이유가 있으신가용?

2024-06-26 04:00 UTC, yeonjeen commented on app/src/main/res/layout/activity_normal_explore.xml
> +                android:clipToPadding="false"
a: 이 속성은 어떤 역학을 하나요?

2024-06-26 04:00 UTC, yeonjeen commented on app/src/main/res/layout/activity_normal_explore.xml
> +                android:contentDescription="@null"
a: 헉... 맨날 커밋할 때마다 이미지뷰 에러로 떴었는뎅.. 이런 방법이!! 저도 써볼게용

2024-06-26 04:04 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +            finish()
약간 코드 스타일에 따라 다를 것 같은데 저는 = 보다 중괄호 사용을 더 선호하긴 해요! 
메서드들이 다 { } 로 통일성 있게 가져가는 것을 좋아해섭 ㅎ.ㅎ

2024-06-26 04:05 UTC, m6z1 commented on app/src/main/res/layout/activity_normal_explore.xml
> +            android:background="?attr/selectableItemBackgroundBorderless"
백그라운드에 `?attr/selectableItemBackgroundBorderless` 요걸 넣어주면 리플 효과를 가질 수 있슴다
PR 영상에 나와있어요!

2024-06-26 04:06 UTC, m6z1 commented on app/src/main/res/layout/activity_normal_explore.xml
> +            android:visibility="visible"
요 부분은 추후에 수정할 예정인데, 이 layout 자체가 검색 결과가 없을 때 뜨는 거라 초기엔 visibility가 gone으로 되어있어야해서욥!
visible로 처리한 건 ui 테스트 땜시루 설정해놨을 거예요

2024-06-26 04:09 UTC, m6z1 commented on app/src/main/res/layout/activity_normal_explore.xml
> +                android:clipToPadding="false"
리사이클러뷰에서 padding이 있을 경우에 아이템이 패딩 영역을 포함해서 스크롤이 되지 않아요! 근데 패딩 영역 포함해서 스크롤 되게 설정해주는 속성입니다! 설명이 좀 이상한데 참고할 만한 블로그 첨부해드릴게요
[clipToPadding 블로그](https://youngest-programming.tistory.com/73)

2024-06-26 06:24 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/adapter/NormalExploreAdapter.kt
> +) : RecyclerView.Adapter<NormalExploreViewHolder>() {
@junseo511  변화감지 문제는 라이브데이터의 상태값에 대한 문제입니다.
라이브데이터 값을 업데이트하는 로직에 문제가 있을 가능성이 높습니다.
라이브데이터가 값을 어떻게 감지하는지 내부 로직을 한번 살펴보시죠

@m6z1 id비교로직이 문제가 되었으려나요 나중에 이슈파면 그때 다시 봐드리겠씀다

2024-06-26 06:26 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreUiState.kt
> +    val novelCount: Long = 0,
uistate는 서버를 알던가요?

2024-06-26 06:27 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +                uiState.error -> throw IllegalStateException()
@junseo511 예외를 터뜨리는것이 꼭 튕기는건 아닙니다

2024-06-26 06:28 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +            finish()
@yeonjeen 일반적으로 '='는 코틀린에서 반환형 함수를 나타냅니다!

저는 반환값이 없는 함수는 중괄호, 반환값이 있으며 한줄로 작성이 가능한 경우에 =을 활용합니다.

2024-06-26 06:30 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/model/NormalExploreUiState.kt
> +    val novelCount: Long = 0,
서버를 모르지만, 레포지토리에서 받아온 결과값을 뷰모델에서 uiState에 넘겨주고 있는데 뭐가 문제인지는 잘 모르겠슴다. 서버를 안다라기 보다는 uiState에서 데이터 레이어의 entity 내에 작품 개수를 알려주는 값이 있다는 걸 알 필요가 있나? 본인이 스스로 처리할 수 있는데 인가요?

2024-06-26 07:00 UTC, s9hn approved these changes

2024-06-26 07:00 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
>          setupUI()
r: "Ui"

2024-06-26 07:00 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> -        binding.onClick = onClickNormalExploreButton()
a: 디테일하네여

2024-06-26 07:00 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.rvNormalExploreResult.setHasFixedSize(false)
a: false가 디폴트일겁니다? maybe.. 찾아주세여

2024-06-26 07:00 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
> +    fun clearSearchWord() {
a: updateSearchWordEmpty 이런건 어때염

2024-06-26 07:00 UTC, s9hn commented on app/src/main/res/layout/item_normal_explore.xml
> +            android:text="@{@string/normal_explore_novel_rating(novel.rating, novel.ratingCount)}"
a: 잘 찾아오셨네요 b

2024-06-26 07:04 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> -        binding.onClick = onClickNormalExploreButton()
준서오빠가 리뷰 달아줬삼요

2024-06-26 07:09 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreViewModel.kt
> +    fun clearSearchWord() {
전 clear가 좋은데염.....

2024-06-26 07:13 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/normalExplore/NormalExploreActivity.kt
> +        binding.rvNormalExploreResult.setHasFixedSize(false)
그렇네엽. . . . . . . .. . . . . .....

2024-06-26 07:29 UTC, merged