refactor: 작품정보 뷰 키워드 리사이클러뷰 마이그레이션
Team-WSS/WSS-Android pull request #69
Opened 2024-06-26 18:11 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #56

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 작품정보 뷰 키워드 리사이클러뷰 마이그레이션

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
<img width="285" alt="image" src="https://github.com/Team-WSS/WSS-Android/assets/127238018/fa2d855b-37b3-427b-a359-a9b4f0754879">

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
이것도 아키텍처랑 디자인패턴은 이슈 새로 파서 진행하겠습니다~~

2024-06-27 00:35 UTC, s9hn requested changes

2024-06-27 00:35 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    val dummyNovelInfo: MutableLiveData<NovelInfoResponseDto> get() = _dummyNovelInfo
a: 이게 되는군요 _dummyNovelInfo가 아랫줄에 선언되어있는데 참조가 되던가요?
r: public 프로퍼티는 LiveData로 바꿔주어야 백킹 프로퍼티를 사용하는 의미가 있습니다.
전반적으로 백킹프로퍼티가 잘못된거 같아요

2024-06-27 00:35 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    private val _dummyNovelInfo = MutableLiveData<NovelInfoResponseDto>()
r: 타입명시바랍니다

2024-06-27 00:35 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    fun initViewMoreTextVisibility(
c: 너무 UI에 의존적인 네이밍같아요 뷰 상태관리에 맞는 네이밍 바랍니다

2024-06-27 00:35 UTC, s9hn commented on app/src/main/res/layout/fragment_novel_info.xml
> +                        android:layout_width="wrap_content"
a: 수평스크롤때문에 칩그룹을 hsv로 감싼것같은데 이 친구 width는 왜 wrap인가요?

2024-06-27 00:52 UTC, junseo511 commented on app/src/main/res/layout/fragment_novel_info.xml
> +                        android:layout_width="wrap_content"
```kotlin
This com.teamwss.websoso.ui.common.customView.WebsosoChipGroup should use android:layout_width="wrap_content"
```
라는 메시지가 나오더라구요

2024-06-27 00:52 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    val dummyNovelInfo: MutableLiveData<NovelInfoResponseDto> get() = _dummyNovelInfo
아하! 너무 생각없이 쓰고있었나봐요 😢 근데 이게 되네요 ㄷㄷ

2024-06-27 00:52 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    fun initViewMoreTextVisibility(
initExpandTextToggleVisibility로 바꾸겠습니다~~ 괜찮나요?

2024-06-27 00:55 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    fun initViewMoreTextVisibility(
updateViewMoreTextVisibility는 어떠신가요?

2024-06-27 00:56 UTC, s9hn commented on app/src/main/res/layout/fragment_novel_info.xml
> +                        android:layout_width="wrap_content"
그냥 칩그룹으로 바꿔도 동일하게 나오나요?(궁금)

2024-06-27 00:59 UTC, s9hn approved these changes
굿

2024-06-27 01:00 UTC, junseo511 commented on app/src/main/res/layout/fragment_novel_info.xml
> +                        android:layout_width="wrap_content"
칩그룹의 문제보다는 hsv의 width가 0dp로 되어있어서 나오는 메시지같습니다!

2024-06-27 01:01 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    fun initViewMoreTextVisibility(
updateExpandTextToggleVisibility 정도 딱 좋은거같습니다 ㅋㅋ

2024-06-27 01:12 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    fun initViewMoreTextVisibility(
liveData 프로퍼티명도 바꿔주셨나요?

2024-06-27 01:13 UTC, s9hn commented on app/src/main/res/layout/fragment_novel_info.xml
> +                        android:layout_width="wrap_content"
hsv영역내에서 wrap된 칩그룹자체를 스크롤하는 원리인가보군요
gravity가 디폴트로 start인가;

2024-06-27 01:14 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +    fun initViewMoreTextVisibility(
네넵 전반적으로 바꿨습니다!!

2024-06-27 02:37 UTC, m6z1 approved these changes
굿 👍  수정 한 번 해주시구 노티주시면 어프루브 드리겟스무니다

2024-06-27 02:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoFragment.kt
> +                }.also { websosoChip -> binding.wcgNovelInfoKeyword.addChip(websosoChip) }
c: 지금은 옵저빙 함수가 하나 밖에 없어서 구냥 로직도 같이 쓴 것 같은데, 분리하기로 했슴요!

2024-06-27 02:37 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
>      fun onViewMoreClicked() {
r: 어제 저도 리뷰 받았던 건데( ~~clearSearchWord~~ ), 뷰모델 보다는 뷰에서 가지고 있을 만한 함수 네이밍인 것 같아요!
실질적으로 하는 역할로 네이밍 해주면 어떨지

2024-06-27 02:39 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
>      fun onViewMoreClicked() {
아 위에 리뷰에서 다른거 바꿨는데 이친구를 안바꿨군요 ㅋㅋㅋㅋㅋ 감사합니다

2024-06-27 08:06 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
>          const val DEFAULT_MAX_LINES = 3
이것도 이 화면에서 사용한다면 접근 제한자를 붙여봅시다

2024-06-27 08:07 UTC, librarywon approved these changes
리뷰 하나만 반영부탁드립니다!

2024-06-28 04:41 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
>          const val DEFAULT_MAX_LINES = 3
아 자꾸 private을 빼먹네요 ㅋㅋㅋㅋㅋ

2024-06-28 04:42 UTC, merged