feat: 작품상세 뷰 구글 권장 아키텍처 및 레포지토리 패턴 적용
Team-WSS/WSS-Android pull request #73
Opened 2024-06-27 03:12 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #71

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 작품상세 뷰 구글 권장 아키텍처 적용
- 작품상세 뷰 레포지토리 패턴 적용

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
<img width="326" alt="image" src="https://github.com/Team-WSS/WSS-Android/assets/127238018/7412c72b-95c2-4e7a-8c98-ffc2057f3a6c">

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-06-27 05:19 UTC, s9hn requested changes

2024-06-27 05:19 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/remote/response/NovelDetailResponseDto.kt
> +    val novelRatingCount: Int = 0,
r: 여기 초깃값이 왜 필요한가요?

2024-06-27 05:19 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
> +    constructor() {
r: 아니 이건 무슨 개행이죠 ;;?

2024-06-27 05:19 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +class GetNovelDetailUseCase
a: 유즈케이스 왜 만드셨을까요?

2024-06-27 05:19 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +        fun fetchNovelDetail(novelId: Long) {
c: update !

2024-06-27 05:19 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiModel.kt
> +        val formattedNovelRating: String
c: 클래스 내부에 둔 이유가 있나요?

2024-06-27 05:19 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +            NovelDetailModel.UserNovelModel(
c: 좀 더 가독성을 개선할 수 있는 방법은 없을까요

2024-06-27 05:19 UTC, s9hn commented on app/src/main/res/layout/menu_novel_detail_popup.xml
> +            app:isVisible="@{userNovelId != 0}"
c: 로직..?

2024-06-27 05:35 UTC, m6z1 requested changes
리뷰 확임부탁드려요>.< 수정 후에 노티주시면 어프루브 해드리겟슴니다

2024-06-27 05:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
> +    @Inject
r: 여기는 개행 왜??

2024-06-27 05:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
> +        suspend fun getNovelDetail(novelId: Long): NovelDetailEntity {
r: 컨벤션에 따르면 서버에서 데이터 가져오는 메서드 prefix는 fetch 입니다

2024-06-27 05:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +class GetNovelDetailUseCase
a: 도메인 레이어를 둔 이유가 무엇인지 궁금!

2024-06-27 05:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    @Inject
r: 수정 부탁해요

2024-06-27 05:35 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                        )
c: 우리가 uiState를 dataClass로 사용하는 이유에 대해서 한 번 공부하시구 수정하시면 좋을 것 같슴니다. (저도 이 코드 보고 생각나서 다시 공부 중) 지금 상태는 dataClass를 uiState로 사용하는 장점 중 일부가 없는 것 가타여

[참고할 블로그](https://medium.com/@laco2951/android-ui-state-modeling-어떤게-좋을까-7b6232543f25)

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/remote/response/NovelDetailResponseDto.kt
> +    val novelRatingCount: Int = 0,
null인 경우에 서버에서 요구한 사항인데 괜찮지 않을까요...?

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
> +    constructor() {
진짜 억울함쓰 이거때매 ktlint 꺼버림 ;;;

클래스명이 길어서 일케된듯요

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
> +    @Inject
ㅋㅋㅋㅋㅋㅋ 아 진짜 킹받네

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/repository/FakeNovelDetailRepository.kt
> +        suspend fun getNovelDetail(novelId: Long): NovelDetailEntity {
아 뷰모델에 적는게 아니었군요

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    @Inject
울면서 수정중...

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +            NovelDetailModel.UserNovelModel(
개행하면서 변수명을 표시해야 할만큼 중요한 부분은 아니라 ktlint 끄고 줄바꿈만 지웠습니당

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiModel.kt
> +        val formattedNovelRating: String
데이터 바인딩에서 바로 사용할 방법이 없을까 고민하다가 클래스 내부에 함께 두었습니다...!

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                        )
저도 이 아티클을 봤었는데 uiState를 다른 뷰들과 일관성 있게 가져가고 싶었어요...!

가독성이나 성능 부분에서 큰 영향이 있지 않다고 생각하는데 꼭 수정해야할 부분일까요?

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +class GetNovelDetailUseCase
진짜 왜뒀을까요 필요 없어보이는데 ..ㅎㅎ 지우고 추후 필요하면 추가하겠습니다
아직 도메인에 익숙하지가 않아요 😢

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/domain/usecase/GetNovelDetailUseCase.kt
> +class GetNovelDetailUseCase
지금 보니까 필요 없는거같아서 지우려고 합니다...ㅎ
코틀린 왕초보는 갈길이 멉니다 ㅠ

2024-06-27 06:02 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/data/remote/response/NovelDetailResponseDto.kt
> +    val novelRatingCount: Int = 0,
아 생각해보니까 어차피 서버에서 0으로 주는거니까 상관이 없겠네요 뭔가 이해를 잘못했나 봅니다

2024-06-27 06:04 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiModel.kt
> +        val formattedNovelRating: String
생성자쪽에 위치해도 되지 않나요?

2024-06-27 06:04 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +            NovelDetailModel.UserNovelModel(
내부의 기본 생성자들 말한겁니다!

2024-06-27 06:10 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                        )
정말 성능에 영향이 없나요?

2024-06-27 06:17 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiModel.kt
> +        val formattedNovelRating: String
그쪽이 더 좋을거같군요...! 생각해보니 큰 로직이 없어서 괜찮을 것 같습니다 :)

2024-06-27 06:17 UTC, junseo511 commented on app/src/main/res/layout/menu_novel_detail_popup.xml
> +            app:isVisible="@{userNovelId != 0}"
여기서 뭔가 깨달음 +1 하고 갑니다

2024-06-27 06:18 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +            NovelDetailModel.UserNovelModel(
음 무슨 내용인지는 이해했습니다!! 근데 0이나 null을 표현해주는 값들을 각각 어떤 변수인지 읽는 사람이 알아야 하는 이유가 뭔지 궁금합니다

2024-06-27 06:24 UTC, s9hn commented on app/src/main/res/layout/menu_novel_detail_popup.xml
> +            app:isVisible="@{userNovelId != 0}"
c: xml에는 가급적 로직을 없애주세요

2024-06-27 06:25 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                        )
일회적인 state에서는 오히려 data class가 단점이 많군요...!

일관성하고는 상관 없다는 점 배워갑니다 😮

2024-06-27 07:20 UTC, s9hn requested changes

2024-06-27 07:20 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +sealed class NovelDetailUiState {
a: sealed 'class'를 선택하신 이유는 무엇인가요?

2024-06-27 07:20 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                    _novelDetail.value = this.novelDetail
c: 구조가 조금 이해되지 않는데 Success에 novelDetailModel이 있는데, novelDetailModel 라이브데이터는 또 무엇인가요?

2024-06-27 07:22 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +sealed class NovelDetailUiState {
하나의 객체로 묶어서 관리하고 싶었습니다...! 가독성이 일단 좋아요 👍

2024-06-27 07:24 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                    _novelDetail.value = this.novelDetail
음 차라리 이 부분은 아예 분리하는게 나은 것 같기도 하네요

2024-06-27 07:38 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +sealed class NovelDetailUiState {
sealed interface는요?

2024-06-27 07:39 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                    _novelDetail.value = this.novelDetail
같은 모델을 두 프로퍼티로 나눠서 사용하는 구조가 조금 어색합니다

2024-06-27 07:50 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                    _novelDetail.value = this.novelDetail
흠 🧐

2024-06-27 07:50 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +sealed class NovelDetailUiState {
오 이런 친구도 있었군요

2024-06-27 07:56 UTC, s9hn requested changes

2024-06-27 07:56 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +        _uiState.value = NovelDetailUiState.Loading
r: 얘가 왜 있는건가요? 이미 _uiState는 NovelDetailUiState.Loading로 초기화되어있습니다.

2024-06-27 07:56 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    val novelDetail: NovelDetailModel?
c: 얘가 지금 왜 있는지를 모르겠어요

2024-06-27 07:56 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +sealed interface NovelDetailUiState {
a: 무작정 적용이 아니라 차이점을 알려주세요 :(

2024-06-27 07:59 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +sealed class NovelDetailUiState {
아 추가 코멘트를 안달았네요 ㅋㅋㅋㅋ
https://medium.com/hongbeomi-dev/sealed-class와-sealed-interface-db1fff634860
이 글 보고왔었어요

최상위 클래스가 인터페이스가 될 수 없었으며, 하위 클래스로 확장하기가 어려웠던 Sealed Class를 Interface로 전환하면서 해결되었다네요 🤔 제 뷰같은 경우에는 하위 클래스가 존재하니 저쪽이 맞지 않을까용

2024-06-27 08:04 UTC, librarywon requested changes
고생하셨습니다 uiState 어려울텐데 화이팅하고 반영해봅시다!

2024-06-27 08:04 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        novelDetailViewModel.updateNovelDetail(1)
R: 이 1이 필요한 상수라면 상수화를 진행해주시면 좋을 것 같습니다.

2024-06-27 08:04 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +        MutableLiveData(NovelDetailUiState.Loading)
a: init상태를 두지 않고 기본값으로 loading을 하신 이유가 궁금합니다. 

ps. 저도 굳이굳이 init을 두어야한다고 생각하진 않아요!

2024-06-27 08:04 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +                    _novelDetail.value = this.novelDetail
동의합니다

2024-06-27 08:04 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    }
r: 기본값을 배정해주었는데 init에서 중복으로 설정을 해주고 있습니다.

2024-06-27 08:04 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiModel.kt
> +        val formattedNovelRating: String = "$novelRating ($novelRatingCount)",
a: 제가 생각하지 못한 방식에 ui Model 방식이라 배우고 갑니다.
val hasUserNovelInfo: Boolean = userNovelId != null, 라던지
val formattedNovelRating: String = "$novelRating ($novelRatingCount)",
같은 것

2024-06-27 08:07 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/model/NovelDetailUiState.kt
> +sealed class NovelDetailUiState {
[sealed class vs sealed interface](https://velog.io/@mendel/%EC%BD%94%ED%8B%80%EB%A6%B0-enum-class-vs-sealed-class-vs-sealed-interface-%EC%96%B8%EC%A0%9C-%EB%AD%98-%EC%8D%A8%EC%95%BC%ED%95%A0%EA%B9%8C)
이쪽이 좀 더 이해하기 편하실 것 같습니다

2024-06-27 08:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
> +        novelDetailViewModel.updateNovelDetail(1)
필요한 상수가 아니라서 그대로 두었습니다!!

2024-06-27 08:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +        MutableLiveData(NovelDetailUiState.Loading)
저는 당연히 기본값으로 loading이 되어야 하는줄 알았습니다...!

2024-06-27 08:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    val novelDetail: NovelDetailModel?
고민의 흔적이랄까...☆

2024-06-27 08:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +        _uiState.value = NovelDetailUiState.Loading
지금 너무 많이맞아서 뇌가 안움직이나봐요

2024-06-27 08:26 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailViewModel.kt
> +    }
ㅠㅠ

2024-06-27 09:29 UTC, s9hn approved these changes
이만하면 충분히 고민하신 것 같습니다! 
고생하셨습니다 !

2024-06-27 10:17 UTC, m6z1 approved these changes

2024-06-28 04:28 UTC, librarywon approved these changes

2024-06-28 04:30 UTC, merged