feat: float to dp 확장함수 추가
Team-WSS/WSS-Android pull request #78
Opened 2024-06-27 15:39 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #77

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- float to dp 확장함수 추가

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
```kotlin
fun Float.floatToDp(): Float = this / Resources.getSystem().displayMetrics.density

fun Float.floatToPx(): Float = this * Resources.getSystem().displayMetrics.density

fun Int.intToPx(): Int = this * Resources.getSystem().displayMetrics.density.toInt()
```

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
원래 이슈는 웹소소칩까지 적용이었는데 생각보다 안예쁘게 나오더라구요?
그냥 씁시다~~ 혹시 toPx도 겸사겸사 넣어도 될까요~~ popupWindow 쓰면서 사용하는거같던데

2024-06-28 01:13 UTC, m6z1 approved these changes
LGTMSAMSUNGTM

2024-06-28 06:15 UTC, librarywon approved these changes
LGTM 감사합니다

2024-06-28 16:01 UTC, s9hn requested changes

2024-06-28 16:01 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Float.floatToDp(): Float = this / Resources.getSystem().displayMetrics.density
r: floatToDp는 반환값으로 DP를 기대하지만 사실상 반환타입은 Float입니다.
뿐만아니라, 커스텀뷰에선 Float 타입의 인자를 기대하는데, FloatToDp를 넘겨주는건 어색해보여요
'Float를 Dp로 조정한 Float'라는 이름을 가지는건 어떨까요

2024-06-28 16:01 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Int.intToPx(): Int = (this * Resources.getSystem().displayMetrics.density).toInt()
c: 얘는 어디서 사용하나요?

2024-07-04 05:12 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Int.intToPx(): Int = (this * Resources.getSystem().displayMetrics.density).toInt()
뷰 위치를 조정하면서 사용하고 있습니당

2024-07-04 05:13 UTC, junseo511 commented
리뷰반영 완료해쑴당

2024-07-04 05:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Int.intToPx(): Int = (this * Resources.getSystem().displayMetrics.density).toInt()
여기있는 함수 모두 사용중인거죠?

2024-07-05 14:55 UTC, s9hn approved these changes
마땅히 안떠오른다데스..

2024-07-05 14:55 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Float.toDpFloat(): Float = this / Resources.getSystem().displayMetrics.density
a: toScaledByDp 같은건 어떰요? @all

2024-07-05 20:31 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Float.toDpFloat(): Float = this / Resources.getSystem().displayMetrics.density
굳이 확장함수로 있어야 할까라는 근본적이 생각이 들기도 하는..

2024-07-06 15:56 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Float.toDpFloat(): Float = this / Resources.getSystem().displayMetrics.density
@librarywon 날릴까용? 근데 이정도는 있어도 괜찮다싶긴 한데

2024-07-07 04:48 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Float.toDpFloat(): Float = this / Resources.getSystem().displayMetrics.density
toScaledByDp 좋음요 ~ 확장함수는 있는 게 좋을 것 같아요

2024-07-08 01:15 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/util/ExtentionFuction.kt
> +fun Float.toDpFloat(): Float = this / Resources.getSystem().displayMetrics.density
toFloatScaledByDp()

2024-07-09 06:09 UTC, merged