feat: 작품상세 뷰 구글 권장 아키텍처 및 레포지토리 패턴 적용
Team-WSS/WSS-Android pull request #85
Opened 2024-07-03 09:45 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #70

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 작품상세 뷰 구글 권장 아키텍처 및 레포지토리 패턴 적용

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
로직이 좀 많아질거같아서 한번 끊고갑니다.
빠른 리뷰해주시면 감사 🙏

2024-07-03 10:18 UTC, m6z1 approved these changes
LGTM~ 로직 자세히는 못 보고 슥 봤는데 깔끔한 것 같아요! 글고 전체적으로 let 사용할 때 그냥 it. 으로 사용하기 보다는 수신객체 네이밍 사용하는 건 어떨지 의견이 궁금함다!

2024-07-03 10:18 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +            kotlin.runCatching {
```suggestion
            runCatching {
```

2024-07-03 10:18 UTC, m6z1 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/model/ReadStatus.kt
> +    WATCHING, WATCHED, QUIT
r: 트레일링 콤마

2024-07-03 11:20 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelDetail/novelInfo/NovelInfoViewModel.kt
> +            kotlin.runCatching {
엥 이거 뭐지 ㅋㅋ

2024-07-03 19:44 UTC, librarywon approved these changes
고생하셨습니다 리뷰확인해주세요

2024-07-03 19:44 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
>                  setWebsosoChipTextAppearance(R.style.body2)
a: 코틀린스러워서 마음에 드네요

2024-07-03 19:44 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
> +                    expandTextUiModel.bodyMaxLines = Int.MAX_VALUE
a: 이 MAX_VALUE는 뭐죠?

2024-07-03 19:44 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
> +}
c: 개인적으로 UiModel를  이렇게 다 쪼개서 쓰는게 맞는지 잘 모르겠네요 (진짜로 모름) 제가 생각하는 UiModel은 단일 클래스였거든요

2024-07-03 19:44 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/ReadStatus.kt
> +    WATCHING, WATCHED, QUIT,
a: 트레일링 콤마 디테일 좋습니다.

2024-07-04 01:33 UTC, s9hn requested changes

2024-07-04 01:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
>                  setWebsosoChipText(keyword.keywordName + " " + keyword.keywordCount)
c: 스트링 추출 궈궈

2024-07-04 01:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
> +        _uiState.value?.let {
a: 사용하는 uistate는 _uistate가 아닌 uistate가 맞을 것 같아요

2024-07-04 01:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
> +) {
r: what?????????? 이거 노란줄 안뜹니까? data class의 가변 생성자는 불가능입니다 필히 수정 부탁드려요

2024-07-04 01:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
> +) {
r: 여기도 수정 바랍니다.

2024-07-04 01:33 UTC, s9hn commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
> +}
uistate가 복잡하면 개발자 역량에 따라서 모델을 분리하고 조합하는건 좋은 접근이라고 생각합니다!
다만 진짜 복잡하긴하네요 ㅋㅋ 어캐생겼는지는 가늠이안됨

2024-07-04 02:18 UTC, junseo511 reviewed
반영 완료했습니다!! 어푸해주심 감사하겠슴다 👏

2024-07-04 02:18 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoFragment.kt
>                  setWebsosoChipText(keyword.keywordName + " " + keyword.keywordCount)
화긴입니다

2024-07-04 02:18 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/NovelInfoViewModel.kt
> +                    expandTextUiModel.bodyMaxLines = Int.MAX_VALUE
Int에 기본으로 내장되어 있는 확장함수인듯 합니다. 저도 이름이 불편해서 바꾸려했는데 ㅋㅋㅋㅋㅋ

Int가 가질 수 있는 최댓값을 리턴해주는 것 같습니다.

2024-07-04 02:18 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
> +) {
아하!

2024-07-04 02:18 UTC, junseo511 commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
> +}
해당 UiModel 내에서만 처리되는 로직이고 화면에 출력되는 부분이라 모델에서 했는데,
진짜 복잡하긴 한데 실제로 전체적인 로직도 복잡해서 저도 슬픕니다...😢
서버에서 받아오는 수치에 따라 크기, 색깔이 유동적으로 움직여야 해서요 ㅋㅋㅋㅋㅋㅋㅋ..

2024-07-04 03:46 UTC, librarywon commented on app/src/main/java/com/teamwss/websoso/ui/novelInfo/model/NovelInfoUiModel.kt
> +}
문제는 이걸 받아서 다른 사람이 개발해야한다는거

2024-07-04 04:54 UTC, s9hn requested changes
열심히하네요 굿 LGTM

2024-07-04 04:55 UTC, s9hn approved these changes

2024-07-06 15:54 UTC, merged